split events
owncloud/ocis pull request #10049
Opened 2024-09-13 10:12 UTC by dragonchaser

2024-09-16 12:15 UTC, kobergj requested changes

2024-09-16 12:15 UTC, kobergj commented on services/activitylog/pkg/service/response.go
> +	MessageResourceInSpaceMoved    = l10n.Template("{user} moved {resource} to {space}")
I don't think we need these at all now. Apparently there was a misunderstanding with translation text. I'd recommend to use `{folder}` everywhere.

2024-09-17 11:31 UTC, saw-jan commented on tests/acceptance/features/apiActivities/activities.feature
> +                      "required": ["resource","folder","user"],
only the message template is change, so the property name will still be `space` not a `folder`
```json
"variables": {
          "resource": {
            "id": "cb2e3f6d-4e13-42de-ba61-4a1b7ff6f374$2503e6a8-54fb-4e0f-b002-e43c90a15b35!e0800c08-092f-41e7-a5a3-332b1d6b7532",
            "name": "lorem.txt"
          },
          "space": {
            "id": "2503e6a8-54fb-4e0f-b002-e43c90a15b35!2503e6a8-54fb-4e0f-b002-e43c90a15b35",
            "name": "Admin"
          },
          "user": {
            "id": "2503e6a8-54fb-4e0f-b002-e43c90a15b35",
            "displayName": "admin"
          }
        }
```
```suggestion
                      "required": ["resource","space","user"],
```

2024-09-17 11:35 UTC, saw-jan commented on tests/acceptance/features/apiActivities/activities.feature
> +                      "required": ["resource","folder","user"],
`"required": [` field should not be changed

2024-09-17 11:53 UTC, saw-jan commented on tests/acceptance/features/apiActivities/activities.feature
now just need to update all the messages:
```diff
-to {space}
+to {folder}

-from {space}
+from {folder}
```

2024-09-18 04:09 UTC, saw-jan commented
build:https://drone.owncloud.com/owncloud/ocis/38989/58/10
web e2e test is failing because the activity message is not right:

![Screenshot from 2024-09-18 09-50-07](https://github.com/user-attachments/assets/ad44a3c1-be6e-42d9-8ea5-41d0453d857c)

2024-09-18 06:34 UTC, mmattel commented
I was asked to take a look on Transifex. Two comments:
* The screenshot above shows the original language (English) from the source code and not something translated. This means, TX is not involved --> We have to look if there is a processing issue somewhere in the chain. Have a detailed look, the name of the space is called `.space` (dot space) and the filename is not resolved at all.
* I have taken a look into the German and also other translations and it looks fine, see screenshot below.

![image](https://github.com/user-attachments/assets/967a1012-17a1-40bc-b190-b6625da2d056)

2024-09-18 06:43 UTC, saw-jan commented
@mmattel the screenshot that I provided above is for web issue and maybe not related to translation.

The problem with translation is that with this PR the message has changed:
en: `{user} added {resource} to {folder}`
so I think we need change in other translations as well. e.g.:
de: `{user} hat {resource} zu {folder} hinzugefügt`

Note: `{space}` is changed to `{folder}`.

But I don't know how translation works and how to bring changes without merging the PR

2024-09-18 07:01 UTC, mmattel commented
@saw-jan when looking into TX, there are no open translations for German for activitylog. So everything is up to date there. Note that the sync happens once a night. If there are string changes/additions here in the repo and they are urgently needed, you need to ask Phil for a manual sync, ping me for a translation and Phil needs to trigger sync afterwards again. Then you have the translation down here in this repo.

2024-09-18 07:15 UTC, saw-jan commented
So that means if we merge this PR then the translation will be changed accordingly the next day?

2024-09-18 07:18 UTC, mmattel commented
@saw-jan we need to mak the tests working if one changes translatable text that is not merged.

@dragonchaser Q, for couriosity: Why is the target redefined from space to file and not added so we have messages for space and file?

2024-09-18 07:41 UTC, dragonchaser commented
> @saw-jan we need to make the tests working if one changes translatable text that is not merged. 🐔 🥚
> 
> @dragonchaser Q, for couriosity: Why is the target redefined from space to file and not added so we have messages for space and file?

https://github.com/owncloud/ocis/pull/10049#discussion_r1761034777 miscommunication :)

2024-09-18 07:41 UTC, mmattel commented
Attention #10072 is adding `MessageResourceUpdated` based on `{space}`... we need to take care 😱

2024-09-18 08:04 UTC, kobergj submitted a review, later dismissed

2024-09-20 11:05 UTC, merged