implement tracing in the account service
owncloud/ocis pull request #1017
Opened 2020-12-03 13:12 UTC by C0rby

Added tracing to the accounts service.

2020-12-03 14:11 UTC, kulmann commented on accounts/pkg/service/v0/tracing.go
> +	ctx, span := trace.StartSpan(ctx, "Accounts.CreateAccoutn")
Typo in `CreateAccount`

2020-12-03 14:18 UTC, C0rby commented on accounts/pkg/service/v0/tracing.go
> +	ctx, span := trace.StartSpan(ctx, "Accounts.CreateAccoutn")
Nice catch!

2020-12-03 17:42 UTC, kulmann requested changes
Please have a look at `ocis/pkg/command/settings.go` and `ocis/pkg/command/accounts.go`. You can see a TODO in the accounts command, that should be fixed in this PR by applying the ocis tracing config to the accounts tracing config, the same way as done in the settings command.

2020-12-04 14:27 UTC, kulmann approved these changes
❤️

2020-12-04 14:32 UTC, merged