fix impersonated request user mismatch
owncloud/ocis pull request #10550
Opened 2024-11-12 11:07 UTC by 2403905

## Description

We fixed a user id and mane mismatch in the impersonated auth-app API request

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2024-11-12 13:52 UTC, kobergj requested changes
usual nitpicking...

2024-11-12 13:52 UTC, kobergj commented on changelog/unreleased/fix-auth-app.md
> +We fixed a user id and mane mismatch in the impersonated auth-app API request
```suggestion
We fixed a user id and name mismatch in the impersonated auth-app API request
```

2024-11-12 13:52 UTC, kobergj commented on services/auth-app/pkg/service/service.go
> +			if strings.Contains(err.Error(), "requested user does not match") {
use a dedicated error type if you want to react on it. String matching will always end up in bugs :)

2024-11-12 15:59 UTC, micbar approved these changes

2024-11-13 09:39 UTC, kobergj approved these changes

2024-11-13 09:39 UTC, merged