[tests-only][full-ci] Tests for listing drives after sharing resource with Denied role
owncloud/ocis pull request #10721
Opened 2024-12-04 04:21 UTC by anon-pradip

## Description

This PR adds acceptance tests to verify drive listing behavior when resources are shared with denied permission role.

Key test scenarios:
- Verifies that users can only see their own personal spaces when sharing with denied permissions
- Ensures correct JSON response structure for drive listings including driveType, name and id

## Related Issue

- Related to: https://github.com/owncloud/ocis/issues/10656

## Motivation and Context

## How Has This Been Tested?

- CI
- Locally

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2024-12-16 07:24 UTC, anon-pradip commented
This PR is subsequent to the PR: https://github.com/owncloud/ocis/pull/10696. So waiting for that to be merged.

2025-01-06 06:44 UTC, anon-pradip commented
Making it ready for review since #10703 is merged.

2025-01-06 08:25 UTC, nabim777 commented on tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
> +      | permissionsRole | Denied     |
```suggestion
      | resource        | textfile.txt |
      | space           | Personal   |
      | sharee          | Brian      |
      | shareType       | user       |
      | permissionsRole | Denied     |
```

need to correct the intendation

2025-01-06 08:27 UTC, nabim777 commented on tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
> +            "enum": ["Brian Murphy"]
```suggestion
            "const": "Brian Murphy"
```

2025-01-06 08:32 UTC, nabim777 commented on tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
> +    And user "Alice" has created folder "FolderToShare"
```suggestion
    And user "Alice" has created folder "FolderToShare"
```

Is this step needed?

2025-01-06 09:08 UTC, SagarGi commented on tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
> +  @env-config
is this needed?
does this test use ocis wrapper or any ENV configs? cause i do not see one.

2025-01-06 10:14 UTC, anon-pradip commented on tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
> +  @env-config
IMHO, for the step: `And the administrator has enabled the permissions role "Denied"`, we need ocis-wrapper, isn't it?

2025-01-06 10:15 UTC, anon-pradip commented on tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
> +    And user "Alice" has created folder "FolderToShare"
Yes. Added :+1:

2025-01-06 10:22 UTC, anon-pradip commented on tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
> +            "enum": ["Brian Murphy"]
Should I go same for `"driveType"`?

2025-01-06 11:12 UTC, SagarGi commented on tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
> +  @env-config
Oh cool. did not know about that.

2025-01-07 04:22 UTC, nabim777 commented on tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
> +            "enum": ["Brian Murphy"]
Yes

2025-01-07 04:23 UTC, SagarGi reviewed
LGTM :+1:

2025-01-07 04:23 UTC, saw-jan commented on tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
> +  Scenario Outline: list all drives after sharing a resource with denied permission role
Please, move denied role test scenarios to its own feature file

2025-01-07 04:24 UTC, saw-jan commented on tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
> +  Scenario Outline: list all drives after sharing a resource with denied permission role
But can be in separate PRs

2025-01-07 06:55 UTC, anon-pradip commented on tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
> +  Scenario Outline: list all drives after sharing a resource with denied permission role
Okeii :rocket:

2025-01-07 07:02 UTC, nabim777 approved these changes
LGTM :+1:

2025-01-07 08:26 UTC, saw-jan requested changes

2025-01-07 08:26 UTC, saw-jan commented on tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
> +            "enum": ["%space_id%"]
this is a pattern
```suggestion
            "oattern": "%space_id%"
```

2025-01-07 10:42 UTC, saw-jan requested changes

2025-01-07 10:42 UTC, saw-jan commented on tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
> +    And the JSON response should contain space called "Brian Murphy" and match
you should check whether the share exists or not. checking personal drive is out of the scope of this scenario

2025-01-07 10:42 UTC, saw-jan commented on tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
> +    And the JSON response should contain space called "Alice Hansen" and match
these should not be needed in this scenario

2025-01-07 10:42 UTC, saw-jan commented on tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
> +    And the JSON response should contain space called "Brian Murphy" and match
sorry for being vague in the ticket. I have updated the point https://github.com/owncloud/ocis/issues/10656

2025-01-07 10:42 UTC, saw-jan commented on tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
> +  Scenario Outline: list all drives after sharing a resource with denied permission role
```suggestion
  Scenario Outline: sharee lists all drives after getting a share with a denied permission role
```

2025-01-20 11:25 UTC, amrita-shrestha commented on tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
> +    And the json response should not contain a space with name "Brian Murphy"
```suggestion
    And the json response should not contain a space with name "<resource>"
```

2025-01-21 09:39 UTC, anon-pradip commented on tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
> +    And the json response should not contain a space with name "Brian Murphy"
IMHO, since we are dealing with list the `resources`,  using:
`And the json response should not contain the following shares:` 
could be more clear.

2025-01-21 09:44 UTC, amrita-shrestha reviewed
lgtm me but how about adding coverage for resource inside project/space

2025-01-21 10:52 UTC, anon-pradip commented
> lgtm me but how about adding coverage for resource inside project/space

Added :rocket:

2025-01-22 04:12 UTC, S-Panta approved these changes
lgtm

2025-01-22 10:12 UTC, saw-jan approved these changes

2025-01-22 10:13 UTC, merged