Add filtering of userlog based on settings
owncloud/ocis pull request #10779
Opened 2024-12-17 16:07 UTC by bastianbeier

## Description

Add filtering of userlog based on settings. Should be merged after https://github.com/owncloud/ocis/pull/10706

## Related Issue

- Closes https://github.com/owncloud/ocis/issues/10769

## How Has This Been Tested?

- test environment: localhost
- test case 1: unshare space with user that has in-app notifications for space unshared disabled

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2024-12-18 08:19 UTC, 2403905 commented on services/userlog/pkg/service/filter.go
> +			ulf.log.Error().Err(err).Msg("cannot get user event setting")
Please add the user ID and setting ID log.Error().Err(err).Str("userid", userid).Msg...

2024-12-18 09:45 UTC, kobergj requested changes
some nitpicking as always. Rest looks :+1:

2024-12-18 09:45 UTC, kobergj commented on services/userlog/pkg/service/filter.go
> +func (ulf UserlogFilter) Filter(ctx context.Context, event events.Event, executant *user.UserId, users []string) []string {
This method would be called as `filter.Filter`. That stutters. Maybe rename it to `Execute`? So it'd be called like `filter.Execute`.

2024-12-18 09:45 UTC, kobergj commented on services/userlog/pkg/service/filter.go
> +type UserlogFilter struct {
exported struct `UserlogFilter` should have a comment or be unexported

2024-12-18 09:45 UTC, kobergj commented on services/userlog/pkg/service/filter.go
> +func NewUserlogFilter(l log.Logger, vc settingssvc.ValueService) *UserlogFilter {
exported func `NewUserlogFilter` should have a comment or be unexported

2024-12-18 11:14 UTC, bastianbeier commented
Thanks for the review!
Findings should be fixed @2403905 @kobergj

2024-12-18 14:40 UTC, mmattel commented on changelog/unreleased/enhancement-add-events-setting.md
> +Enhancement: The user settings was extended by the notifications preferences
```suggestion
Enhancement: The user settings are extended by notifications preferences
```

2024-12-18 14:44 UTC, mmattel commented on changelog/unreleased/enhancement-add-events-setting.md
> +The user settings was extended, that a user can store their notifications preferences
```suggestion
Users can now store their notifications preferences in the user settings
```

2024-12-23 09:43 UTC, kobergj approved these changes
Nice :heart:

2024-12-23 10:00 UTC, merged