[tests-only][full-ci] add tests for checking the header location for tus upload
owncloud/ocis pull request #10807
Opened 2024-12-24 10:39 UTC by nabim777

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2025-01-02 11:03 UTC, PrajwolAmatya commented on tests/acceptance/features/apiSpacesShares/shareUploadTUS.feature
> +    When the public uploads file "filesForUpload/zerobyte.txt" to "textfile.txt" via TUS inside last link shared folder with password "%public%" using the WebDAV API
```suggestion
    When the public uploads file "filesForUpload/zerobyte.txt" to "textfile.txt" via TUS inside last link shared folder with password "%public%" using the WebDAV API
    Then the HTTP status code should be "201"
```

2025-01-02 11:03 UTC, PrajwolAmatya commented on tests/acceptance/features/apiSpacesShares/shareUploadTUS.feature
> +    When the public uploads file "filesForUpload/zerobyte.txt" to "textfile.txt" via TUS inside last link shared folder with password "%public%" using the WebDAV API
```suggestion
    When the public uploads file "filesForUpload/zerobyte.txt" to "textfile.txt" via TUS inside last link shared folder with password "%public%" using the WebDAV API
    Then the HTTP status code should be "201"
```

2025-01-03 03:52 UTC, saw-jan requested changes

2025-01-03 03:52 UTC, saw-jan commented on tests/acceptance/TestHelpers/TusClientWrapper.php
`TusClientWrapper.php` -> `TusClient.php`

2025-01-03 03:52 UTC, saw-jan commented on tests/acceptance/TestHelpers/TusClientWrapper.php
> +class TusClientWrapper extends Client {
```suggestion
class TusClient extends Client {
```

2025-01-03 03:52 UTC, saw-jan commented on tests/acceptance/TestHelpers/TusClientWrapper.php
> + * A helper class where TUS is wrapped and done API requests
```suggestion
 * A TUS client based on TusPhp\Tus\Client
```

2025-01-03 03:52 UTC, saw-jan commented on tests/acceptance/TestHelpers/TusClientWrapper.php
> +		$this->client = new Client($baseUri, $options);
why do you need to instantiate Client if you are extending Client?

2025-01-03 04:14 UTC, nabim777 commented on tests/acceptance/TestHelpers/TusClientWrapper.php
> +		$this->client = new Client($baseUri, $options);
Oh my mistake :sweat_smile:

2025-01-07 04:44 UTC, PrajwolAmatya commented on tests/acceptance/TestHelpers/TusClient.php
> +		$data    = $this->getData($offset, $bytes);
```suggestion
		$data = $this->getData($offset, $bytes);
```

2025-01-07 08:34 UTC, SagarGi reviewed
There are lots of line breaks. May be fix them also.

2025-01-07 08:34 UTC, SagarGi commented on tests/acceptance/TestHelpers/TusClient.php
> +		}
No need to catch exception other then the three?

2025-01-07 08:34 UTC, SagarGi commented on tests/acceptance/TestHelpers/TusClient.php
> +	 * @throws TusException
```suggestion
	 * @throws TusException | ConnectionException
```

2025-01-07 08:34 UTC, SagarGi commented on tests/acceptance/TestHelpers/TusClient.php
> +
```suggestion
```

2025-01-07 08:34 UTC, SagarGi commented on tests/acceptance/TestHelpers/TusClient.php
> +
```suggestion
```

2025-01-07 08:34 UTC, SagarGi commented on tests/acceptance/TestHelpers/TusClient.php
> +
```suggestion
```

2025-01-07 08:34 UTC, SagarGi commented on tests/acceptance/TestHelpers/TusClient.php
> +
```suggestion
```

2025-01-07 09:39 UTC, S-Panta commented on tests/acceptance/bootstrap/SpacesTUSContext.php
> +        $this->featureContext->setResponse($response);
```suggestion
		$response = $this->tusContext->uploadFileUsingTus($user, $source, $destination, $spaceId);
		$this->featureContext->setLastUploadDeleteTime(\time());
                $this->featureContext->setResponse($response);
```

2025-01-22 10:26 UTC, saw-jan commented on tests/acceptance/TestHelpers/TusClient.php
> +	public function createUploadWithResponse(string $key, int $bytes = -1): ResponseInterface {
since we want to reflect the existing methods but return differently, I recommend appending a char like this.
```suggestion
	public function createWithUploadR(string $key, int $bytes = -1): ResponseInterface {
```

2025-01-22 10:26 UTC, saw-jan commented on tests/acceptance/TestHelpers/TusClient.php
> +	public function uploadWithResponse(int $bytes = -1): ResponseInterface {
```suggestion
	public function uploadR(int $bytes = -1): ResponseInterface {
```

2025-01-22 10:26 UTC, saw-jan commented on tests/acceptance/TestHelpers/TusClient.php
> +			}
this usage is incorrect. method doesn't return url

2025-01-22 10:28 UTC, saw-jan commented on tests/acceptance/TestHelpers/TusClient.php
> +		try {
https://docs.guzzlephp.org/en/stable/request-options.html#http-errors

2025-01-23 07:03 UTC, nabim777 commented on tests/acceptance/TestHelpers/TusClient.php
> +		}
I think not needed

2025-01-23 10:19 UTC, amrita-shrestha commented on tests/acceptance/TestHelpers/TusClient.php
> +	public function createWithUploadR(string $key, int $bytes = -1): ResponseInterface {
```suggestion
	public function createUploadWithResponse(string $key, int $bytes = -1): ResponseInterface {
```

2025-01-23 10:22 UTC, saw-jan commented on tests/acceptance/TestHelpers/TusClient.php
> +	public function createWithUploadR(string $key, int $bytes = -1): ResponseInterface {
`createUploadWithResponse` is not a good name here. `create with response` seems a bit odd.
we are mimicking `createWithUpload` method from parent class but this time it retruns response. So, either `createWithUploadR` or `createWithUploadRR` - return response

2025-01-23 10:25 UTC, saw-jan commented on tests/acceptance/TestHelpers/TusClient.php
> +	public function createWithUploadR(string $key, int $bytes = -1): ResponseInterface {
you can have a comment for the method

2025-01-23 10:31 UTC, nabim777 commented on tests/acceptance/TestHelpers/TusClient.php
> +	public function createWithUploadR(string $key, int $bytes = -1): ResponseInterface {
Okay :+1:

2025-01-23 10:53 UTC, nabim777 commented on tests/acceptance/TestHelpers/TusClient.php
> +	public function createWithUploadR(string $key, int $bytes = -1): ResponseInterface {
can i have comment like this
`creates a resources with a post request and returns response`

2025-01-23 11:18 UTC, nabim777 commented on tests/acceptance/TestHelpers/TusClient.php
> +		try {
@saw-jan 
First of all thanks for the docs.
As  documet you have given
can I add `'http_errors' => false,` on post ?
it says it'll disable throwing exceptions on an HTTP protocol errors (i.e., 4xx and 5xx responses).

```bash
$response = $this->getClient()->post(
	$this->apiPath,
	[
	'body' => $data,
	'headers' => $headers,
	'http_errors' => false,
	]
);
```

2025-01-27 03:36 UTC, amrita-shrestha commented on tests/acceptance/TestHelpers/TusClient.php
> +	public function createWithUploadRR(string $key, int $bytes = -1): ResponseInterface {
this name sounds so odd createWithUploadRR
```suggestion
	public function createWithUploadRR(string $key, int $bytes = -1): ResponseInterface {
```

2025-02-07 04:11 UTC, saw-jan approved these changes

2025-02-10 08:25 UTC, merged