[docs-only] add monitoring and tracing for ocis_traefik
owncloud/ocis pull request #1159
Opened 2020-12-23 12:19 UTC by wkloucek

2020-12-28 13:21 UTC, butonic requested changes

2020-12-28 13:21 UTC, butonic commented on deployments/examples/cs3_users_ocis/.env
> +# you need to enable
enable what? reads like something is missing...

2020-12-28 13:21 UTC, butonic commented on deployments/examples/ocis_keycloak/.env
> +# you need to enable
same

2020-12-28 13:21 UTC, butonic commented on deployments/examples/ocis_traefik/.env
> +# you need to enable
same

2020-12-28 13:21 UTC, butonic commented on deployments/examples/owncloud10_with_oc_web/.env
> +# you need to enable
same

2020-12-30 17:48 UTC, micbar approved these changes
LGTM

2020-12-30 17:51 UTC, merged