Functionality to map home directory to different storage providers
owncloud/ocis pull request #1186
Opened 2021-01-07 09:38 UTC by ishank011

Functionality to map home directory to different storage providers

cs3org/reva#1142 added a parameter in reva that allows us to redirect /home requests to different storage providers based on a mapping derived from the user attributes, which was previously not possible since we hardcode the /home path for all users. This PR adds the config for that parameter.

2021-01-07 10:31 UTC, butonic requested changes
Cool, I love this! AFAICT it might allows us to dynamically register a storage provider for every user and use the userid in the home path.

Just update the usage with an example of what the value could look like so admins get an idea of what they can put there.

The failing UI test is somthing @kulmann or @LukasHirt might have an idea about.

2021-01-07 10:31 UTC, butonic commented on storage/pkg/flagset/gateway.go
> +			Usage:       "mapping template for user home paths to user-specific mount points",
can you add an example here and in the changelog on how to use it. here an `eg. /home/{{...}}` is good enough.

2021-01-07 11:01 UTC, ishank011 commented
Thanks for the review @butonic! Added the example

2021-01-08 11:33 UTC, labkode commented
@butonic can we get this in?

2021-01-18 11:03 UTC, ishank011 commented
@butonic can you take a look?

2021-01-29 09:43 UTC, butonic approved these changes

2021-01-29 19:16 UTC, merged