Added labels for username and password input in idp service
owncloud/ocis pull request #1794
Opened 2021-03-11 08:34 UTC by JanAckermann

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2021-03-11 08:41 UTC, JanAckermann commented
TDB aria

2021-03-11 11:00 UTC, kulmann requested changes
Cool! Especially accessibility wise good solution 👍  Some minor proposals as comments. Also: please run `make generate` again with the final source version.

2021-03-11 11:00 UTC, kulmann commented on changelog/unreleased/add-labels-and-aria-labelled-by-on-login.md
> +https://github.com/owncloud/ocis/tree/issues/WEB-105
Branch will be deleted after merge. Could you link to the web github issue instead? Also: why also the empty newlines? ;-)

2021-03-11 11:00 UTC, kulmann commented on idp/ui/src/app.css
> +.oc-login-form div:first-of-type {
```suggestion
.oc-login-form div:not(:last-of-type) {
```
If we would add more inputs in the future (haha, for a login page probably not gonna happen) the margin-bottom is needed for all except the last.

2021-03-11 12:18 UTC, JanAckermann commented
:) :+1: resolved

2021-03-12 09:44 UTC, JanAckermann commented
Also fixes https://jira.owncloud.com/browse/WEB-107

2021-03-12 10:34 UTC, JanAckermann commented
@kulmann 
Added red borders on error state
Changed transplation texts

2021-03-12 14:37 UTC, kulmann approved these changes
Ultra nitpick: there is some wrong whitespace (see comment). Other than that: 😍

2021-03-12 14:37 UTC, kulmann commented on idp/ui/src/containers/Login/Login.js
> +      return (
Whitespace doesn't look intentional. Happened by accident?

2021-03-12 15:46 UTC, merged