[docs-only] Add warning about firewall configuration.
owncloud/ocis pull request #1821
Opened 2021-03-18 12:28 UTC by dragotin

## Description
Adds a short warning about firewall. An activated firewall that does not allow mDNS breaks oCIS.

2021-03-18 13:19 UTC, kulmann approved these changes

2021-03-18 13:19 UTC, refs approved these changes

2021-03-18 13:20 UTC, refs requested changes

2021-03-18 13:20 UTC, refs commented on docs/ocis/getting-started.md
> +oCIS internally uses mDNS. If your system has a firewall, make sure mDNS is allowed in your active zone.
```suggestion
oCIS out of the box relies in Multicast DNS (mDNS) by default. If your system has a firewall, make sure mDNS is allowed in your active zone.
```

2021-03-19 08:07 UTC, butonic approved these changes

2021-03-19 08:31 UTC, refs approved these changes

2021-03-19 08:31 UTC, merged