Use ocis registry for refresh
owncloud/ocis pull request #2120
Opened 2021-06-05 19:10 UTC by IljaN

## Description
The go-micro registry-singleton ignores the ocis config and defaults to mdns

## Related Issue

- Fixes #2119

## Motivation and Context
The storage was always advertised via mdns, ignoring the registry configuration

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2021-06-06 18:00 UTC, dragotin requested changes
Please consider a more speaking variable name for `r` such as ocisRegistry.

2021-06-07 08:50 UTC, IljaN commented
@dragotin https://www.reddit.com/r/golang/comments/8wxwgv/why_does_go_encourage_short_variable_names/

2021-06-07 09:51 UTC, dragotin commented
Yes, I am very well aware. But here we have a different case.

If you look at the rule of thumb from the first link you sent (which is **A name's length should not exceed its information content.**) this one is mainly true for local 'helper' variables that do not have a deep intersection with the code around. But that is not the case in this PR: Here we have two *different* registries that can be confused. Your whole bugfix is about choosing the right one - but with shortening the var name that drastically, I think the confusion for the next reader of this code is pre set. 

Thus my ask to make it somehow visible that this is about the oCIS registry.

I have to admit that in times of auto completion  I am not so much convinced of the the short-name convention that  is described in the links you referenced. But ok. However, in this case, I am even convinced that the rules they make do not even apply.

2021-06-07 10:05 UTC, refs approved these changes

2021-06-07 12:15 UTC, dragotin approved these changes

2021-06-07 14:32 UTC, micbar commented
@IljaN please rebase, Settings UI tests were fixed in master.

2021-06-07 16:43 UTC, merged