Update exp failure file dpakach
owncloud/ocis pull request #2158
Opened 2021-06-10 07:24 UTC by dpakach

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2021-06-15 08:47 UTC, jasson99 requested changes

2021-06-15 08:47 UTC, jasson99 commented on tests/acceptance/expected-failures-API-on-OCIS-storage.md
> +
Why did we move it here?

2021-06-15 08:47 UTC, jasson99 commented on tests/acceptance/expected-failures-API-on-OCIS-storage.md
>  #### [sharing with group not available](https://github.com/owncloud/product/issues/293)
This is a closed issue. Lets not add here.

2021-06-15 08:47 UTC, jasson99 commented on tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
> +#### [href in trashbin PROPFIND response is wrong](https://github.com/owncloud/ocis/issues/1120)
this issue is closed. Lets not add here

2021-06-16 03:07 UTC, kiranparajuli589 reviewed
lgtm 👍🏼

2021-06-16 03:23 UTC, Talank reviewed
LGTM

2021-06-16 11:26 UTC, jasson99 approved these changes

2021-06-16 11:31 UTC, phil-davis approved these changes

2021-06-16 11:31 UTC, merged