Archiver app provider capabilities
owncloud/ocis pull request #2529
Opened 2021-09-22 10:02 UTC by wkloucek

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2021-09-22 10:58 UTC, pascalwengerter commented on storage/pkg/command/frontend.go
> +			appproviders := []map[string]interface{}{
```suggestion
			appProviders := []map[string]interface{}{
```

Line 75 suggests we're using camelCase here? If so, please also see line 82 ofc

2021-09-23 09:04 UTC, jvillafanez commented
For the archiver, it has a maximum number of files and a maximum size that I think they should be in the capabilities. The client could prevent requests that we know that will fail.

2021-09-23 09:47 UTC, wkloucek commented
> For the archiver, it has a maximum number of files and a maximum size that I think they should be in the capabilities. The client could prevent requests that we know that will fail.

Good point :+1: Needs changes in REVA though...

2021-09-23 11:21 UTC, kulmann commented
> > For the archiver, it has a maximum number of files and a maximum size that I think they should be in the capabilities. The client could prevent requests that we know that will fail.
> 
> Good point 👍 Needs changes in REVA though...

Yes, good idea for improvement 👍  but please let's get this PR merged first, then improve it (IMO right away ;-) ).

2021-09-23 11:27 UTC, jvillafanez approved these changes
I'm not sure about the changes in the go.mod file, but the rest looks good to me.

2021-09-23 14:24 UTC, kulmann requested changes

2021-09-23 14:24 UTC, kulmann commented on storage/pkg/flagset/frontend.go
> +			Usage:       "URL where the archiver is reachable",
```suggestion
			Usage:       "URL where the app listing of the app provider is reachable",
```

2021-09-23 14:24 UTC, kulmann commented on storage/pkg/flagset/frontend.go
> +			Usage:       "URL where the archiver is reachable",
```suggestion
			Usage:       "URL where files can be handed over to an application from the app provider",
```

2021-09-23 15:15 UTC, kulmann approved these changes
LGTM 👍

2021-09-23 15:40 UTC, merged