Fix claim selector based routing for basic auth
owncloud/ocis pull request #2779
Opened 2021-11-16 11:58 UTC by wkloucek

## Description
We've fixed the claim selector based routing for requests using basic auth.
Previously requests using basic auth have always been routed to the DefaultPolicy
when using the claim selector despite the set cookie because the basic auth
middleware fakes some OIDC claims.

Now the cookie is checked before routing to the DefaultPolicy and therefore 
set cookie will also be respected for requests using basic auth.

## Related Issue

- Unblocks

## Motivation and Context
Using basic auth

## How Has This Been Tested?

- locally

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2021-11-17 09:09 UTC, phil-davis commented
CI fails: https://drone.owncloud.com/owncloud/ocis/7852/11/6
```
=== RUN   TestClaimsSelector
    selector_test.go:162: Expected Policy cookie got 
--- FAIL: TestClaimsSelector (0.00s)
```

needs a unit test adjustment?

2021-11-18 07:09 UTC, ownclouders commented
:boom: Acceptance test [<strong>Web-Tests-ocis-smoke-ocis-storage-2</strong>](https://drone.owncloud.com/owncloud/ocis/7936/33/1) failed. Further test are cancelled...
<!-- id: pr-2779 -->

2021-11-25 13:11 UTC, refs requested changes

2021-11-25 13:11 UTC, refs commented on proxy/pkg/proxy/policy/selector.go
> +				// TODO check we know the routing policy?
should this TODO be addressed?

2021-12-06 10:00 UTC, refs approved these changes

2021-12-06 10:01 UTC, merged