Try to rely on web's acceptance test deps
owncloud/ocis pull request #2791
Opened 2021-11-18 09:07 UTC by pascalwengerter

## Description
Draft PR to see if we can remove the acceptance test dependencies we pull & install from `web` anyways

## Motivation and Context

## Types of changes
- [X] Tests only (no source changes)

2021-11-18 09:15 UTC, ownclouders commented
:boom: Acceptance test [<strong>accountsUITests</strong>](https://drone.owncloud.com/owncloud/ocis/7944/34/1) failed. Further test are cancelled...
<!-- id: pr-2791 -->

2021-11-19 07:27 UTC, individual-it requested changes

2021-11-19 07:27 UTC, individual-it commented on settings/ui/tests/run-acceptance-test.sh
> +cucumber-js --retry 1 \
it does not find cucumber-js
I tried to use cucumber-js from `${TEST_INFRA_DIRECTORY}/node_modules/@cucumber/cucumber/bin/cucumber-js` (after `yarn install` there) and also from `${WEB_PATH}/tests/acceptance//node_modules/@cucumber/cucumber/bin/cucumber-js`

and in both cases I get the message
```
Error: 
      You appear to be executing an install of cucumber (most likely a global install)
      that is different from your local install (the one required in your support files).
      For cucumber to work, you need to execute the same install that is required in your support files.
      Please execute the locally installed version to run your tests.
```

So I think we do depend on the deps in the acceptance tests folder

2021-12-09 09:32 UTC, pascalwengerter commented
Superseded by the more promising #2851

2021-12-09 09:32 UTC, closed without merging