Delete group memberships when deleting a user
owncloud/ocis pull request #3080
Opened 2022-02-01 13:38 UTC by rhafer

## Description

Upon deleting a User from the LDAP backend, we also need to cleanup
the user's group memberships as LDAP itself doesn't make any promises
about referential integrity.

## Related Issue
- Fixes #3027

2022-02-01 13:48 UTC, C0rby approved these changes
~~LGTM~~ Approved to soon.

2022-02-01 13:49 UTC, C0rby requested changes

2022-02-01 13:49 UTC, C0rby commented on graph/pkg/identity/ldap.go
> +	groupEntries, err := i.getLDAPGroupsByFilter(fmt.Sprintf("(%s=%s)", i.groupAttributeMap.member, e.DN), true, false)
This error needs to be checked.

2022-02-02 09:24 UTC, rhafer commented on graph/pkg/identity/ldap.go
> +	groupEntries, err := i.getLDAPGroupsByFilter(fmt.Sprintf("(%s=%s)", i.groupAttributeMap.member, e.DN), true, false)
Fixed.

2022-02-02 10:00 UTC, C0rby approved these changes

2022-02-02 11:10 UTC, merged