ADR: Add first draft for readonly external user management
owncloud/ocis pull request #3131
Opened 2022-02-08 12:32 UTC by rhafer

ADR about integrating with external read-only identity management solutions.

cc @micbar @butonic

2022-02-08 13:06 UTC, butonic requested changes
just minor edits, nothing conceptually different

2022-02-08 13:06 UTC, butonic commented on docs/ocis/adr/0017-allow-read-only-external-user-management.md
> +
```suggestion
* Bad, because without caching we will hammer the identity management system with lookup requests

```

2022-02-08 13:06 UTC, butonic commented on docs/ocis/adr/0017-allow-read-only-external-user-management.md
> +* IdP is read only and does not provide an API to query users
```suggestion
* External identity management system is read only and does NOT provide an API to query users
```

2022-02-08 13:06 UTC, butonic commented on docs/ocis/adr/0017-allow-read-only-external-user-management.md
> +* External identity management system is read only and provides an interface to query users (e.g.
```suggestion
* External identity management system is read only and provides an interface to query users
```

2022-02-08 13:06 UTC, butonic commented on docs/ocis/adr/0017-allow-read-only-external-user-management.md
> +### IdP is read only and does not provide an API to query users
```suggestion
### External identity management system is read only and does NOT provide an API to query users
```

2022-02-08 13:06 UTC, butonic commented on docs/ocis/adr/0017-allow-read-only-external-user-management.md
> +* Good, because this has very little external requirements
```suggestion
* Good, because this has very little external requirements
* Good, because we have accounts fully under our control
```

2022-02-24 11:35 UTC, micbar commented on docs/ocis/adr/0017-allow-read-only-external-user-management.md
> +Usually oCIS will no have administrative access to such a system and we will not be allowed to
```suggestion
Usually oCIS will have no administrative access to such a system and we will not be allowed to
```

2022-02-24 11:36 UTC, micbar commented on docs/ocis/adr/0017-allow-read-only-external-user-management.md
> +reconfigure it suite our needs (e.g. we will not be able to enhance the schema of an already existing
```suggestion
reconfigure it to suit our needs (e.g. we will not be able to enhance the schema of an already existing
```

2022-02-24 11:36 UTC, micbar commented on docs/ocis/adr/0017-allow-read-only-external-user-management.md
> +LDAP Directory). In most case our access will be read-only.
```suggestion
LDAP Directory). In most of the cases our access will be read-only. 
```

2022-02-24 11:37 UTC, micbar commented on docs/ocis/adr/0017-allow-read-only-external-user-management.md
> +identities whith which he can authenticate, e.g. his facebook, twitter, microsoft or google
```suggestion
identities which he can authenticate with, e.g. his facebook, twitter, microsoft or google
```

2022-02-24 11:38 UTC, micbar commented on docs/ocis/adr/0017-allow-read-only-external-user-management.md
> +- When no other services (LDAP, SCIM, ...) is available that could be used look up a user UUID
```suggestion
- When no other services (LDAP, SCIM, ...) are available that could be used look up a user UUID
```

2022-02-24 11:40 UTC, micbar commented on docs/ocis/adr/0017-allow-read-only-external-user-management.md
> +* Good, because there is only an single source of truth (the external IdM) and we don't need to
```suggestion
* Good, because there is only a single source of truth (the external IdM) and we don't need to
```

2022-02-24 11:43 UTC, butonic approved these changes

2022-02-24 11:53 UTC, merged