initial events draft
owncloud/ocis pull request #3146
Opened 2022-02-10 09:00 UTC by kobergj

Signed-off-by: jkoberg <jkoberg@owncloud.com>

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2022-02-10 09:01 UTC, kobergj commented on storage/pkg/command/storageusers.go
> +	if cfg.Reva.StorageShares.ReadOnly {
Revert!

2022-02-11 14:42 UTC, butonic requested changes
some c'n'p leftovers

2022-02-11 14:42 UTC, butonic commented on nats/pkg/config/log.go
> +	File   string `mapstructure:"file" env:"OCIS_LOG_FILE;SETTINGS_LOG_FILE"`
SETTINGS_ -> NATS_ or EVENTS_?

2022-02-11 14:42 UTC, butonic commented on nats/pkg/config/http.go
> +	CacheTTL  int    `ocisConfig:"cache_ttl" env:"SETTINGS_CACHE_TTL"`
SETTINGS_ -> NATS_ or EVENTS_?

2022-02-11 14:42 UTC, butonic commented on nats/pkg/config/http.go
> +	CORS      CORS   `ocisConfig:"cors"`
does nats even have an http endpoint?

2022-02-11 14:42 UTC, butonic commented on nats/pkg/config/grpc.go
> +	Addr      string `ocisConfig:"addr" env:"SETTINGS_GRPC_ADDR"`
SETTINGS_ -> NATS_ or EVENTS_?

2022-02-11 14:42 UTC, butonic commented on nats/pkg/config/grpc.go
> +type GRPC struct {
does nats even have a grpc endpoint?

2022-02-11 14:42 UTC, butonic commented on nats/pkg/config/http.go
> +type CORS struct {
unneded?

2022-02-11 14:42 UTC, butonic commented on nats/pkg/config/reva.go
> +	JWTSecret string `ocisConfig:"jwt_secret" env:"OCIS_JWT_SECRET;SETTINGS_JWT_SECRET"`
SETTINGS_ -> NATS_ or EVENTS_?

2022-02-11 14:42 UTC, butonic commented on nats/pkg/config/reva.go
> +type TokenManager struct {
does nats need to make grpc calls? does it need the token?

2022-02-11 14:42 UTC, butonic commented on nats/pkg/config/tracing.go
> +	Collector string `ocisConfig:"collector" env:"OCIS_TRACING_COLLECTOR;SETTINGS_TRACING_COLLECTOR"`
SETTINGS_ -> NATS_ or EVENTS_?

2022-02-11 14:42 UTC, butonic commented on nats/pkg/config/config.go
> +	TokenManager TokenManager `ocisConfig:"token_manager"`
unneeded?

2022-02-11 15:06 UTC, butonic approved these changes

2022-02-11 15:06 UTC, butonic commented on nats/pkg/config/tracing.go
> +type Tracing struct {
nats does not need tracing

2022-02-11 15:53 UTC, micbar approved these changes

2022-02-11 16:14 UTC, merged

2022-02-16 17:01 UTC, rhafer commented on nats/pkg/config/defaultconfig.go
> +			Port: 4222,
@kobergj I know this is the NATS default port. But it seems we have a policy to only listen on a specific port range. (See https://github.com/owncloud/ocis/wiki/Official-Port-Ranges). Yeah, I also know I am a bit late to the party for this PR but I also just learned about that document ;-)