NATS integration fixes
owncloud/ocis pull request #3268
Opened 2022-03-04 14:04 UTC by wkloucek

## Description
- makes NATS killable by passing a context from the runtime (`ocis kill nats`)

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2022-03-04 14:13 UTC, wkloucek commented on nats/pkg/server/nats/nats.go
> +		if err := n.server.LastError(); err != nil {
```
// LastError returns the last fatal error the server experienced.
```

Therefore it should now be killed if an error like in CI occurs:
```
{"level":"fatal","service":"nats","time":"2022-03-04T01:04:43Z","message":"STREAM: Failed to start: read tcp 127.0.0.1:53876->127.0.0.1:9233: i/o timeout"}
```

2022-03-04 14:15 UTC, wkloucek commented
@kobergj could you please check if that makes sense? :-) That PR also doesn't pull NATS through REVA anymore, which I find good. Any objections?

2022-03-04 14:23 UTC, kobergj requested changes
Yes, much better :+1: Just some minors

2022-03-04 14:23 UTC, kobergj commented on nats/pkg/server/nats/nats.go
> +		time.Sleep(1 * time.Second)
Should we make this configurable? Or move it to a global var so we can at least overwrite on build?

2022-03-04 14:23 UTC, kobergj commented on nats/pkg/server/nats/nats.go
> +func NewNATSServer(ctx context.Context, opts ...Option) (*NATSServer, error) {
Mind adding some comments for the exported funcs in this file?

2022-03-07 05:15 UTC, individual-it commented
please run with `full-ci` and best multiple times to prove that it actually helps

2022-03-07 08:41 UTC, kobergj approved these changes

2022-03-07 08:59 UTC, merged