[tests-only] ApiTests: sharing subItems inside of space
owncloud/ocis pull request #3354
Opened 2022-03-21 12:14 UTC by ScharfViktor

added tests sharing subItems inside of the space:
- via sharing
- via public link

Only users with the **manager space role** can be able to share resources within the space
Users with editor and viewer space role cannot be able to share resources within the space. 
They get 404 Error with "No share permission" message. for client would certainly be better to get 403. 
code here:
https://github.com/cs3org/reva/blob/9e040c93d60ec5faf6c8b0347ce9ecf8d6c6ab70/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/shares.go#L192-L196

2022-03-23 10:35 UTC, individual-it requested changes
Additionally to the comments I would suggest to check if the share was created
e.g. checking if Brian can see the received share
Otherwise the server might just return "200" without doing anything and we would not notice

P.S. If you are using intelliJ Ctrl+Alt+L will format the Gherkin tables

2022-03-23 10:35 UTC, individual-it commented on tests/acceptance/features/bootstrap/SpacesContext.php
> +		$fullUrl = $this->baseUrl . "/ocs/v2.php/apps/files_sharing/api/v1/shares";
should we put `/ocs/v2.php/apps/files_sharing/api/v1/shares` into a const?

2022-03-23 10:35 UTC, individual-it commented on tests/acceptance/features/apiSpaces/shareSubItemOfSpace.feature
> +      | folder/file.txt | editor     |    200     |
statusCode column is not used
```suggestion
      | entity          | role       |
      | folder          | viewer     |
      | folder          | editor     |
      | folder/file.txt | viewer     |
      | folder/file.txt | editor     |
```

2022-03-23 22:40 UTC, ScharfViktor commented
> Additionally to the comments I would suggest to check if the share was created e.g. checking if Brian can see the received share Otherwise the server might just return "200" without doing anything and we would not notice

I tryed to add checking from core so as not to duplicate code in ocis
```
When user "Brian" accepts share "<entity>" offered by user "Alice" using the sharing API
Then as "Brian" file "<entity>" should exist
```
but it doesn't work for me, I get `Sharing::userReactsToShareOfferedBy could not find share folder, offered by Alice to Brian
        Failed asserting that null is not null.` although share is created (I'm sure of it).  @individual-it how do you think, what is wrong?

2022-03-24 04:56 UTC, individual-it commented
if Alice has shared `folder/file.txt`, when Brian lists his shares he only sees `/file.txt`. I guess that is correct because Brian does not need to know what the parent folder for Alice is

2022-03-24 10:31 UTC, ownclouders commented
:boom: Acceptance test [<strong>localApiTests-apiSpaces-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/10126/21/1) failed. Further test are cancelled...
<!-- id: pr-3354 -->

2022-03-24 11:35 UTC, ScharfViktor commented
@individual-it thanks for review. I fixed it and PR is ready

2022-03-25 08:13 UTC, individual-it approved these changes

2022-03-25 08:16 UTC, individual-it approved these changes

2022-03-27 19:36 UTC, merged