[tests-only] add acceptance tests for Graph API
owncloud/ocis pull request #3404
Opened 2022-03-28 07:45 UTC by kiranparajuli589

- GraphHelper
- GraphContext

- apiGraphUser
- apiGraphGroup

2022-04-12 11:57 UTC, kiranparajuli589 commented
ci failed with:
```
curl: (22) The requested URL returned error: 502 Bad Gateway
Server on https://ocis-server:9200 is down or not working correctly.
```
ocis log:
```
{"level":"debug","service":"proxy","policy":"ocis","prefix":"/status.php","path":"/status.php","routeType":"prefix","time":"2022-04-12T11:34:30Z","message":"director found"}
{"level":"debug","service":"idm","scope":"ldap","time":"2022-04-12T11:34:31Z","message":"http: proxy error: unsupported protocol scheme \"\""}
{"level":"info","service":"proxy","proto":"HTTP/1.1","request":"da7b97d95be4/USecxB3iyy-000001","remote-addr":"192.168.61.3:44818","method":"GET","status":502,"path":"/status.php","duration":101.529124,"bytes":0,"time":"2022-04-12T11:34:31Z","message":"access-log"}
could not select ocdav service from the registry: not found
```
cc @rhafer

2022-04-13 05:46 UTC, individual-it approved these changes

2022-04-13 09:00 UTC, ownclouders commented
:boom: Acceptance test [<strong>cs3ApiTests-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/10650/20/1) failed. Further test are cancelled...
<!-- id: pr-3404 -->

2022-04-13 10:35 UTC, kiranparajuli589 commented
@saw-jan will look on this pR from now.

2022-04-19 09:44 UTC, saw-jan commented
@rhafer Could you review it?

2022-04-19 09:48 UTC, saw-jan commented on .codacy.yml
> +  - 'tests/TestHelpers/**'
I excluded `tests/TestHelpers` from codacy because I saw that the `bootstrap` folder has already been excluded.
Someone, please provide your opinion

2022-04-19 09:48 UTC, phil-davis commented on .drone.star
> +def ocisServer(storage, accounts_hash_difficulty = 4, volumes = [], depends_on = [], testing_parallel_deploy = False, testing_graph_api = False):
```suggestion
def ocisServer(storage, accounts_hash_difficulty = 4, volumes = [], depends_on = [], testing_parallel_deploy = False):
```

`testing_graph_api` is not used.

2022-04-19 09:48 UTC, phil-davis commented on .drone.star
> +    expectedToFailuresFile = "/drone/src/tests/acceptance/expected-failures-graphAPI-on-OCIS-storage.md"
```suggestion
    expectedFailuresFile = "/drone/src/tests/acceptance/expected-failures-graphAPI-on-OCIS-storage.md"
```

2022-04-19 09:48 UTC, phil-davis commented on .drone.star
> +                    "EXPECTED_FAILURES_FILE": expectedToFailuresFile,
```suggestion
                    "EXPECTED_FAILURES_FILE": expectedFailuresFile,
```

2022-04-19 09:48 UTC, phil-davis commented on tests/acceptance/expected-failures-graphAPI-on-OCIS-storage.md
> +TODO: group list of expected failures to their respective issues.
I guess that the failures should be similar to `expected-failures-API-on-OCIS-storage.md`

Maybe you can just copy that and then make a few changes for any extra/different failures.

2022-04-20 10:00 UTC, saw-jan commented on tests/acceptance/expected-failures-graphAPI-on-OCIS-storage.md
> +- [apiShareReshareToShares3/reShareUpdate.feature:115](https://github.com/owncloud/core/blob/master/tests/acce
Need to find out what happened.

2022-04-20 11:55 UTC, saw-jan commented on tests/acceptance/expected-failures-graphAPI-on-OCIS-storage.md
> +- [apiShareReshareToShares3/reShareUpdate.feature:115](https://github.com/owncloud/core/blob/master/tests/acce
Need some investigation

2022-04-20 12:47 UTC, saw-jan commented
Few things need to be fixed in testhelpers: https://github.com/owncloud/core/pull/39987

2022-04-20 15:05 UTC, rhafer requested changes

2022-04-20 15:05 UTC, rhafer commented on .drone.star
> +        "LDAP_GROUP_SCHEMA_GROUPNAME": "cn",
```suggestion
        "LDAP_GROUP_SCHEMA_GROUPNAME": "cn",
        "LDAP_GROUP_SCHEMA_MEMBER": "member",
```

This should fix a couple of group sharing related failures e.g. `tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature:66`

2022-04-21 05:01 UTC, saw-jan commented
TUS upload tests still fail with `cURL error 7: Failed to connect to localhost port 9200` error
https://drone.owncloud.com/owncloud/ocis/10786/69/6

2022-04-21 06:36 UTC, rhafer commented
> TUS upload tests still fail with `cURL error 7: Failed to connect to localhost port 9200` error https://drone.owncloud.com/owncloud/ocis/10786/69/6

Weird. I had this running yesterday. Will take a look.

2022-04-21 06:58 UTC, saw-jan commented on .drone.star
> +        "OCIS_URL": "https://ocis-server:9200",
the reason for the TUS tests failing was due to not having `OCIS_URL` pointed to `https://ocis-server:9200`

2022-04-21 06:59 UTC, saw-jan commented on .drone.star
> +        "OCIS_URL": "https://ocis-server:9200",
Now the CI is green: https://drone.owncloud.com/owncloud/ocis/10789

2022-04-21 07:09 UTC, saw-jan commented
depends on PR https://github.com/owncloud/core/pull/39987.

2022-04-21 12:14 UTC, rhafer approved these changes

2022-04-21 12:16 UTC, merged