Align service naming
owncloud/ocis pull request #3606
Opened 2022-04-27 15:14 UTC by butonic

We now reflect the configured service names when listing them in the ocis runtime.

Follow up PRs:
- [ ] rename `storage-metadata` -> just `metadata`
- [ ] rename ocis commands to reflect changed names, eg `storageapprovider.go` -> `approvider.go` with the command name `storage-app-provider` -> `app-provider`

partly fixes https://github.com/owncloud/ocis/issues/3603

2022-04-28 14:41 UTC, ownclouders commented
:boom: Acceptance test [<strong>localApiTests-apiAccountsHashDifficulty-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/11051/21/1) failed. Further test are cancelled...
<!-- id: pr-3606 -->

2022-04-29 03:38 UTC, phil-davis approved these changes
Looks reasonable

2022-04-29 06:21 UTC, wkloucek commented
We should then also rename the respective config in `ocis-pkg/config/config.go`

2022-04-29 06:22 UTC, wkloucek requested changes
We should then also rename the respective config in `ocis-pkg/config/config.go`

2022-04-29 06:38 UTC, butonic commented
@wkloucek like so: https://github.com/owncloud/ocis/pull/3606/commits/c3826ac72dcab6459a4ba4ac3ed46710ec802f80

and what about `graph_explorer` in `extensions/graph-explorer/pkg/config/config.go`

2022-04-29 08:21 UTC, C0rby approved these changes
Looks good to me.

2022-05-02 08:51 UTC, kobergj approved these changes

2022-05-02 08:53 UTC, wkloucek approved these changes

2022-05-02 10:44 UTC, merged