More fixes to searching in shares
owncloud/ocis pull request #3725
Opened 2022-05-06 13:25 UTC by aduffeck

This PR fixes a problem when searching in sharey by making the search results relative to the mountpoint space instead of the grant space.
It also adds more debug logs and changes the search to still continue and return whatever it can find in case there's a problem searching within one space.

2022-05-06 13:42 UTC, ownclouders commented
:boom: Acceptance test [<strong>Core-API-Tests-ocis-storage-4</strong>](https://drone.owncloud.com/owncloud/ocis/11538/44/1) failed. Further test are cancelled...
<!-- id: pr-3725 -->

2022-05-11 08:33 UTC, kobergj requested changes
Just some open questions, rest looks :+1:

2022-05-11 08:33 UTC, kobergj commented on extensions/search/pkg/search/index/index.go
> +	NameMapping.Analyzer = "lowercaseKeyword"
Maybe Lowercase naming for `nameMapping`? Or you have a special reason for uppercase?

2022-05-11 08:33 UTC, kobergj commented on extensions/search/pkg/search/provider/events.go
> +		p.logger.Error().Err(err).Interface("authRes", authRes).Msg("error using machine auth")
We want to `return` here, right?

2022-05-11 09:31 UTC, merged