Actually use the sharing configuration from the config file
owncloud/ocis pull request #4019
Opened 2022-06-23 09:10 UTC by aduffeck

This PR fixes a problem with the `migrate` command where the settings from the ocis configuration file were not being used.

2022-06-23 09:21 UTC, kobergj approved these changes
Works now for me :+1: @ScharfViktor do you want to try too?

2022-06-23 09:36 UTC, ScharfViktor commented
> Works now for me 👍 @ScharfViktor do you want to try too?

sure, I'll try to test it again

2022-06-23 10:16 UTC, ScharfViktor commented
I tried run command localy:
![Screenshot 2022-06-23 at 12 15 14](https://user-images.githubusercontent.com/84779829/175276320-d09cccc5-2e22-445a-980a-d54867325edb.png)

2022-06-23 10:23 UTC, kobergj requested changes
@aduffeck I have the same error as @ScharfViktor 

please check publicshares command again

2022-06-23 12:12 UTC, micbar commented
This is blocking the beta.4 release

2022-06-27 08:41 UTC, micbar approved these changes

2022-06-27 08:44 UTC, kobergj approved these changes

2022-06-27 09:13 UTC, merged