ApiTests. refactoring apiSpace suite
owncloud/ocis pull request #4121
Opened 2022-07-06 21:31 UTC by ScharfViktor

- "creating project space" moved to background
- many scenarios are combined into one
- added test re-sharing to the group

2022-07-06 21:49 UTC, ownclouders commented
:boom: Acceptance test [<strong>localApiTests-apiSpaces-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/13136/38/1) failed. Further test are cancelled...
<!-- id: pr-4121 -->

2022-07-07 07:36 UTC, individual-it requested changes

2022-07-07 07:36 UTC, individual-it commented on tests/acceptance/features/apiSpaces/restoreSpaces.feature
> +      | Bob   |
I think we can save time by not having examples but multiple Then steps
```suggestion
    Then for user "Alice" the space "restore a space" should contain these entries:
      | test.txt   |
      | mainFolder |
    And for user "Brian" the space "restore a space" should contain these entries:
      | test.txt   |
      | mainFolder |
    And for user "Bob" the space "restore a space" should contain these entries:
      | test.txt   |
      | mainFolder |      
```

2022-07-07 07:36 UTC, individual-it commented on tests/acceptance/features/apiSpaces/shareSubItemOfSpace.feature
> +    And user "Brian" accepts share "/<entity>" offered by user "Alice" using the sharing API
this sounds like a When step

2022-07-07 07:36 UTC, individual-it commented on tests/acceptance/features/apiSpaces/shareSubItemOfSpace.feature
> +    And user "Bob" accepts share "/<entity>" offered by user "Brian" using the sharing API
When step?

2022-07-08 03:18 UTC, individual-it commented on tests/acceptance/features/bootstrap/SpacesContext.php
> +	 * @Then /^the user "([^"]*)" should have a space called "([^"]*)" (?:owned by|granted to) "([^"]*)" (?:with description file|with space image) "([^"]*)" with these key and value pairs:$/
enjoying regex :-)

2022-07-08 03:18 UTC, individual-it approved these changes

2022-07-08 03:18 UTC, merged