[full-ci] [tests-only] Check cache clear by name
owncloud/ocis pull request #4311
Opened 2022-08-02 10:35 UTC by grgprarup

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2022-08-03 10:38 UTC, ownclouders commented
:boom: Acceptance test [<strong>cs3ApiTests-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/14096/40/1) failed. Further test are cancelled...
<!-- id: pr-4311 -->

2022-08-10 15:32 UTC, grgprarup commented
Rebuild: cache uploaded to `cache` bucket 
`time="2022-08-10T14:50:18Z" level=info msg="file uploaded" bucket=cache`
https://drone.owncloud.com/owncloud/ocis/14343/3/5
https://drone.owncloud.com/owncloud/ocis/14343/4/3
https://drone.owncloud.com/owncloud/ocis/14343/4/4

Restore: cache restored using `cache` bucket
`time="2022-08-10T14:53:48Z" level=info msg="downloading file"`
https://drone.owncloud.com/owncloud/ocis/14343/44/2
https://drone.owncloud.com/owncloud/ocis/14343/44/5
https://drone.owncloud.com/owncloud/ocis/14343/44/6

Purge: cache purged
https://drone.owncloud.com/owncloud/ocis/14343/77/2
```
time="2022-08-10T15:21:44Z" level=info msg="found objects" bucket=cache count=3 key=owncloud/ocis/a436afb82d634dc721faaeced09e3a17a680192f-14343
time="2022-08-10T15:21:44Z" level=info msg="deleting object" bucket=cache key=owncloud/ocis/a436afb82d634dc721faaeced09e3a17a680192f-14343/ocis-binary-amd64_build_artifact_cache.tar
time="2022-08-10T15:21:44Z" level=info msg="deleting object" bucket=cache key=owncloud/ocis/a436afb82d634dc721faaeced09e3a17a680192f-14343/testing_app_build_artifact_cache.tar
time="2022-08-10T15:21:44Z" level=info msg="deleting object" bucket=cache key=owncloud/ocis/a436afb82d634dc721faaeced09e3a17a680192f-14343/testrunner_build_artifact_cache.tar
time="2022-08-10T15:21:44Z" level=info msg="Cache flushed"
```

2022-08-10 15:40 UTC, grgprarup commented
After the merge of this PR:
TODO:
- [ ] old cache in bucket `owncloud` must be cleaned up

2022-08-12 11:26 UTC, SwikritiT commented
> Rebuild: cache uploaded to `cache` bucket `time="2022-08-10T14:50:18Z" level=info msg="file uploaded" bucket=cache` https://drone.owncloud.com/owncloud/ocis/14343/3/5 https://drone.owncloud.com/owncloud/ocis/14343/4/3 https://drone.owncloud.com/owncloud/ocis/14343/4/4
> 
> Restore: cache restored using `cache` bucket `time="2022-08-10T14:53:48Z" level=info msg="downloading file"` https://drone.owncloud.com/owncloud/ocis/14343/44/2 https://drone.owncloud.com/owncloud/ocis/14343/44/5 https://drone.owncloud.com/owncloud/ocis/14343/44/6
> 
> Purge: cache purged https://drone.owncloud.com/owncloud/ocis/14343/77/2
> 
> ```
> time="2022-08-10T15:21:44Z" level=info msg="found objects" bucket=cache count=3 key=owncloud/ocis/a436afb82d634dc721faaeced09e3a17a680192f-14343
> time="2022-08-10T15:21:44Z" level=info msg="deleting object" bucket=cache key=owncloud/ocis/a436afb82d634dc721faaeced09e3a17a680192f-14343/ocis-binary-amd64_build_artifact_cache.tar
> time="2022-08-10T15:21:44Z" level=info msg="deleting object" bucket=cache key=owncloud/ocis/a436afb82d634dc721faaeced09e3a17a680192f-14343/testing_app_build_artifact_cache.tar
> time="2022-08-10T15:21:44Z" level=info msg="deleting object" bucket=cache key=owncloud/ocis/a436afb82d634dc721faaeced09e3a17a680192f-14343/testrunner_build_artifact_cache.tar
> time="2022-08-10T15:21:44Z" level=info msg="Cache flushed"
> ```

Yarn cache are also in `long-term` artifacts?

2022-08-12 12:52 UTC, grgprarup commented
> > Rebuild: cache uploaded to `cache` bucket `time="2022-08-10T14:50:18Z" level=info msg="file uploaded" bucket=cache` https://drone.owncloud.com/owncloud/ocis/14343/3/5 https://drone.owncloud.com/owncloud/ocis/14343/4/3 https://drone.owncloud.com/owncloud/ocis/14343/4/4
> > Restore: cache restored using `cache` bucket `time="2022-08-10T14:53:48Z" level=info msg="downloading file"` https://drone.owncloud.com/owncloud/ocis/14343/44/2 https://drone.owncloud.com/owncloud/ocis/14343/44/5 https://drone.owncloud.com/owncloud/ocis/14343/44/6
> > Purge: cache purged https://drone.owncloud.com/owncloud/ocis/14343/77/2
> > ```
> > time="2022-08-10T15:21:44Z" level=info msg="found objects" bucket=cache count=3 key=owncloud/ocis/a436afb82d634dc721faaeced09e3a17a680192f-14343
> > time="2022-08-10T15:21:44Z" level=info msg="deleting object" bucket=cache key=owncloud/ocis/a436afb82d634dc721faaeced09e3a17a680192f-14343/ocis-binary-amd64_build_artifact_cache.tar
> > time="2022-08-10T15:21:44Z" level=info msg="deleting object" bucket=cache key=owncloud/ocis/a436afb82d634dc721faaeced09e3a17a680192f-14343/testing_app_build_artifact_cache.tar
> > time="2022-08-10T15:21:44Z" level=info msg="deleting object" bucket=cache key=owncloud/ocis/a436afb82d634dc721faaeced09e3a17a680192f-14343/testrunner_build_artifact_cache.tar
> > time="2022-08-10T15:21:44Z" level=info msg="Cache flushed"
> > ```
> 
> Yarn cache is also in `long-term` artifacts?

@SwikritiT Yeah. The cache of the web is used as a long-term cache, and the yarn cache for web e2e and acceptance goes under the web cache. Which are implemented by this pr https://github.com/owncloud/ocis/pull/4309

2022-08-15 04:06 UTC, individual-it requested changes

2022-08-15 06:37 UTC, kiranparajuli589 reviewed
other than the existing comments, lgtm :+1:

2022-08-15 08:30 UTC, phil-davis commented on .drone.star
> +            flush_path = "%s/%s" % ("cache", ctx.repo.slug)
I there is an ordinary build that happens to be running when the nightly cron build runs, then what is going to happen? The cache of that ordinary PR build might unexpectedly disappear.

We could set the `flush_age` (line 2209) to `1` day - "random rubbish" will sit for an extra day before being cleaned up, but we avoid accidentally breaking a running PR  build.

2022-08-15 08:31 UTC, phil-davis commented
`This branch is [2 commits ahead](https://github.com/owncloud/ocis/compare/master...check-flush-cache), [31 commits behind](https://github.com/owncloud/ocis/compare/check-flush-cache...master) master.`

Please rebase when you address the comments, so that we get up-to-date CI.

2022-08-16 06:41 UTC, grgprarup commented on .drone.star
> +PLUGINS_S3_CACHE = "plugins/s3-cache:latest"
This plugin has images `plugins/s3-cache:1` and `plugins/s3-cache:1.4` which are 3 years old, there are no other latest specific versions except `plugins/s3-cache:latest` which is 17 month old image. 
![plugins_image](https://user-images.githubusercontent.com/8559121/184810390-6bbeb13d-301c-4cb1-b8af-04ed95fe751e.png)
Versions 1 and 1.4 are similar with no major changes. The latest tag version has a better output log than versions 1 and 1.4. 
Which version should we use 1 or the latest? @individual-it

2022-08-16 08:17 UTC, phil-davis approved these changes

2022-08-16 09:53 UTC, merged