ensure a linebreak after config validation errors and do not parse config for help
owncloud/ocis pull request #4405
Opened 2022-08-17 12:04 UTC by wkloucek

## Description
This PR:
- ensures that a line break is printed after the config validation error output
- ensures that configuration is not parsed for help topics (but only on execution of the command)

## Related Issue

- Fixes #4402

## Motivation and Context

make oCIS intuitive to use

## How Has This Been Tested?

have a non configured oCIS (`rm -rf ~/.ocis`)
- run `ocis storage-users uploads list --help`, it succeeds with this PR but not with master
- run `ocis server`, it has a proper linebreak at the end of the error message
- run `ocis migrate shares --help`, it succeds with this PR but not with master
- run `ocis migrate publicshares --help`, it succeds with this PR but not with master

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2022-08-17 12:12 UTC, mmattel commented
Great, thanks 👍

2022-08-18 11:52 UTC, kobergj requested changes

2022-08-18 11:52 UTC, kobergj commented on CHANGELOG.md
> +   https://github.com/owncloud/ocis/pull/3419
Where are these changes to `CHANGELOG.md` coming from?

2022-08-18 11:52 UTC, kobergj commented on ocis/pkg/command/migrate.go
> +				fmt.Printf("%v", err)
Isn't the point of this PR to have a newline in `Printf` statements?

2022-08-18 11:52 UTC, kobergj commented on ocis/pkg/command/migrate.go
> +				fmt.Printf("%v", err)
same question here

2022-08-18 11:52 UTC, kobergj commented on ocis/pkg/command/migrate.go
> +				fmt.Printf("%v", err)
and here

2022-08-18 11:52 UTC, kobergj commented on ocis/pkg/command/migrate.go
> +				fmt.Printf("%v", err)
and here

2022-08-18 13:55 UTC, butonic approved these changes

2022-08-18 14:00 UTC, kobergj approved these changes

2022-08-18 14:00 UTC, kobergj commented on ocis-pkg/config/configlog/log.go
> +func LogError(err error) {
Great. But they stutter as they are callled like `configlog.LogError` maybe just call them `Error` `ReturnErrror` `ReturnFatal`? So then they would be used like `configlog.Error`

Obviously not critical as some things just stutter....

2022-08-22 08:15 UTC, mmattel commented
Maybe to re-kick CI to see if it turns green post the not starting issue last week...?

2022-08-22 09:12 UTC, merged