[WIP] add email templating
owncloud/ocis pull request #4564
Opened 2022-09-13 06:13 UTC by dragonchaser

refs #4303

2022-09-15 13:07 UTC, ownclouders commented
:boom: Acceptance test [<strong>Core-API-Tests-ocis-storage-6</strong>](https://drone.owncloud.com/owncloud/ocis/15514/50/1) failed. Further test are cancelled...
<!-- id: pr-4564 -->

2022-09-19 06:52 UTC, dragonchaser commented
/cc @mmattel  https://github.com/dragonchaser/ocis/blob/email-template/services/notifications/pkg/config/config.go#L29

2022-09-21 12:42 UTC, C0rby requested changes
Found a few small issues.

2022-09-21 12:42 UTC, C0rby commented on services/notifications/pkg/email/email.go
> +	writer := bytes.NewBufferString("")
You can just do `var writer bytes.Buffer` here

2022-09-21 12:42 UTC, C0rby commented on services/notifications/pkg/email/email.go
> +	if emailTemplatePath != "" {
Is this check really necessary? I would imagine that if the path is empty then you would receive a ErrNotExist and then `templateHasBeenFound` would still be false.

2022-09-21 12:42 UTC, C0rby commented on services/notifications/pkg/service/service.go
> +		UserId: e.Creator,
Shouldn't this be `e.Grantee`?

2022-09-21 12:42 UTC, C0rby commented on services/notifications/pkg/service/service.go
> +	if authRes.GetStatus().GetCode() != rpcv1beta1.Code_CODE_OK {
This code is unreachable since you check the response code in line 105

2022-09-21 12:42 UTC, C0rby commented on services/notifications/pkg/service/service.go
> +	if md.Status.Code != rpcv1beta1.Code_CODE_OK {
Here again, this code would not be reached if status != ok

2022-09-21 12:42 UTC, C0rby commented on services/notifications/pkg/service/service.go
> +	if authRes.GetStatus().GetCode() != rpcv1beta1.Code_CODE_OK {
Here again.

2022-09-21 12:42 UTC, C0rby commented on services/notifications/pkg/service/service.go
> +	if md.Status.Code != rpcv1beta1.Code_CODE_OK {
And here.

2022-09-22 11:13 UTC, C0rby approved these changes
Just one small nitpick

2022-09-22 11:13 UTC, C0rby commented on services/notifications/pkg/service/service.go
> +	if err != nil || authRes.GetStatus().GetCode() != rpcv1beta1.Code_CODE_OK {
You missed this spot. ;)

2022-09-22 12:02 UTC, merged