[full-ci] add default search fields
owncloud/ocis pull request #4585
Opened 2022-09-14 14:50 UTC by fschade

## Description
till now search only respects the "name" field when using the search, this pr extends the fields to "Content" (tika), "Tags" and "Name". It also introduces a simple lexer which supports the ios query [dictonary](https://github.com/owncloud/ios-app/pull/933)

## Related Issue

- Fixes https://github.com/owncloud/enterprise/issues/5307

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2022-09-14 15:09 UTC, kobergj requested changes

2022-09-14 15:09 UTC, kobergj commented on services/search/pkg/query/lexer.go
> +func (l *Lexer) Scan() (Token, string) {
Linter checks are now in place. This will fail because of no comment

2022-09-15 11:50 UTC, fschade commented on services/search/pkg/engine/bleve.go
> +		if tok == sq.T_FIELD {
i wanna avoid for label to break the loop... i keep the if flow

2022-09-15 12:43 UTC, kobergj commented on services/search/pkg/engine/bleve.go
> +		if tok == sq.T_FIELD {
Yes, better. I oversaw you are breaking the loop. Sorry!

2022-09-15 12:48 UTC, kobergj approved these changes

2022-09-16 11:38 UTC, merged