[full-ci] Add activities service
owncloud/ocis pull request #4626
Opened 2022-09-21 10:41 UTC by fschade

## Description
On the experimental branch we offered the ability to use icap and clamav as virus scan engine,

virus scanning can happen via:
* on upload
* on download
* on demand

for "on upload" and "on download" its easy for the user to determine if a virus is detected:
* on upload -> no file gets listed, virus detected
* on download -> no file gets downloaded, virus detected
* on demand -> problematic because of asynchronous uploading (processing pipeline runs in the background).

the problem with "on demand" scanning is that the user has no clear indication what happens next or happened in the past. We cannot guarantee how long virus scanning will take... so scenarios like "my file is gone, i don't know what happened" can happen.

This is the reason why we've now introduced a dedicated application to visually inform the user what happened and what not. If a file is gone because of infection this now can be seen in the timeline.

## Related Issue
- *experimental

## Motivation and Context
see description above

## How Has This Been Tested?
- local installation and ecigar files
- ...

## Screenshots:
<img width="1512" alt="Bildschirmfoto 2022-09-21 um 12 31 25" src="https://user-images.githubusercontent.com/49308105/191483718-3ff185ef-f3d8-455c-b40c-b785eb1e8ed3.png">
<img width="1512" alt="Bildschirmfoto 2022-09-21 um 12 30 58" src="https://user-images.githubusercontent.com/49308105/191483757-3c14ee36-3777-4643-b068-744c5eee7f84.png">

## Types of changes
- [x] New feature (non-breaking change which adds functionality)
- [x] Technical debt

2022-09-21 11:07 UTC, kobergj requested changes

2022-09-21 11:13 UTC, fschade commented on services/experimental/pkg/activities/activities.go
> +						}{
it is only used there... and it will differ from other events data structs... do you still want it defined outside?

2022-09-22 09:53 UTC, kobergj requested changes

2022-09-22 09:53 UTC, kobergj commented on go.mod
> +replace github.com/cs3org/reva/v2 => github.com/kobergj/reva/v2 v2.0.0-20220919125358-e230a6883013
I needed to rebase the branch, sorry. We need to update the commitID otherwise this won't build

2022-09-28 07:20 UTC, kobergj approved these changes

2022-09-28 07:44 UTC, merged