add requestID middleware
owncloud/ocis pull request #4974
Opened 2022-11-03 23:00 UTC by micbar

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2022-11-03 23:15 UTC, ownclouders commented
:boom: Acceptance test [<strong>Web-Tests-ocis-smoke-ocis-storage-1</strong>](https://drone.owncloud.com/owncloud/ocis/16657/57/1) failed. Further test are cancelled...
<!-- id: pr-4974 -->

2022-11-04 08:14 UTC, mmattel commented
Something to be added in the documentation?

2022-11-04 08:45 UTC, micbar commented
> Something to be added in the documentation?

there is a ticket https://github.com/owncloud/docs-ocis/issues/266

2022-11-04 10:20 UTC, butonic requested changes

2022-11-04 10:20 UTC, butonic commented on services/ocdav/pkg/config/config.go
> +// RequestID configures reva http auth middleware.
```suggestion
// RequestID configures reva requestid middleware.
```

2022-11-04 10:48 UTC, rhafer approved these changes

2022-11-04 10:48 UTC, mmattel commented
This needs a rebase to get it green because of a fix in CI

2022-11-04 10:49 UTC, butonic requested changes
there is no use in adding the config struct here as the ocdav micre service does not use the config options, yet

2022-11-04 10:49 UTC, butonic commented on services/ocdav/pkg/config/config.go
> +	RequestID RequestID `yaml:"request_id"`
unused
```suggestion
	RequestID RequestID `yaml:"request_id"`
```

2022-11-04 10:49 UTC, butonic commented on services/ocdav/pkg/config/config.go
> +
unused
```suggestion
```

2022-11-04 10:51 UTC, butonic commented
Actually, the whole Middleware config is unused. CredentialsByUserAgent  is not used by the micro ocdav service, yet: https://github.com/cs3org/reva/blob/1bc292816a55e7a83fd5967a5baa25a5899d5194/pkg/micro/ocdav/service.go#L142-L156

2022-11-04 10:58 UTC, butonic commented on services/ocdav/pkg/config/config.go
> +
```suggestion
```

2022-11-04 11:02 UTC, butonic commented
to clarify the requestid middleware is always enabled when using dhe microfied ocdav: https://github.com/cs3org/reva/blob/1bc292816a55e7a83fd5967a5baa25a5899d5194/pkg/micro/ocdav/service.go#L195-L199

2022-11-04 11:03 UTC, butonic approved these changes

2022-11-04 11:16 UTC, rhafer approved these changes

2022-11-04 12:01 UTC, merged