Filter hidden files
owncloud/ocis pull request #5018
Opened 2022-11-09 07:36 UTC by aduffeck

With this PR hidden files (dotfiles) will no longer be part of the search results.

2022-11-09 07:55 UTC, ownclouders commented
:boom: Acceptance test [<strong>localApiTests-apiSpaces-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/16746/42/1) failed. Further test are cancelled...
<!-- id: pr-5018 -->

2022-11-09 11:20 UTC, mmattel commented
Just a question, should this be set by default or maybe defined via a env var? Because you do not restrict searching but filtering the results?

2022-11-09 14:10 UTC, aduffeck commented
@mmattel the e2e test suite also wasn't happy about filtering hidden files by default. We'll now index the hidden state so it's available for future changes but we don't filter by default. So the search behaves exactly the same as before.

2022-11-10 09:57 UTC, butonic approved these changes

2022-11-10 09:58 UTC, butonic requested changes

2022-11-10 09:58 UTC, butonic commented on services/search/pkg/search/index/index_test.go
> +				assertDocCount(ref.ResourceId, `Name:*hidden* +Hidden:true`, 0)
shouldnt this be 1?

2022-11-10 16:05 UTC, butonic approved these changes

2022-11-10 16:05 UTC, merged