Add depreaction annotations to variables
owncloud/ocis pull request #5143
Opened 2022-11-28 17:04 UTC by dragonchaser

2022-11-28 22:18 UTC, mmattel commented
Huston, we have a problem...

I updated the adoc.tmpl file so it has no general rendering issues - this is ok now, see the outcome (beside other improvements for readbility)

```
a|`NATS_HOST_ADDRESS` +
`NATS_NATS_HOST` +
:is-deprecated: true
ifeval::[{is-deprecated} == true] 
xref:deprecation-note[Deprecation Note] 
endif::[]
```

BUT

our attempt to define the attribute _inside_ the table does not work. I have tested for hours and post a chat with Antora dev I have the answer why its not working. Note that ifeval is working fine if you have defined the attribute outside the table. You just cant set the attribute inside.

> The preprocessor directives are applied on a table before the lines are processed (that's because before we parse the table, we don't know where AsciiDoc table cells are in the table). Therefore, the preprocessor directives will not see the outcome of the attribute entries in the table cell.

2022-11-29 09:30 UTC, kobergj requested changes
Just small question

2022-11-29 09:30 UTC, kobergj commented on docs/helpers/adoc-generator.go.tmpl
> +			}
Is this necessary? I'd expect `deprecationVersion` to be empty if `ok == false`?

2022-11-29 10:15 UTC, kobergj approved these changes

2022-11-29 10:15 UTC, mmattel approved these changes
Tested together with @dragonchaser 
Runs and renders fine - ouput is great 👍

2022-11-29 10:44 UTC, merged

2022-11-29 10:44 UTC, mmattel commented
As it is merged now, some documentation needs to be added to the dev docs...