[test-only] Apitest. check Copy response headers test
owncloud/ocis pull request #5263
Opened 2022-12-20 17:00 UTC by ScharfViktor

- I check the value of the response headers in the test
- I did not add a folder copy test because there is no folder ID in the response headers.
- I'm not sure which items I should test (maybe hint in the review process): 
<img width="329" alt="Screenshot 2022-12-20 at 17 37 42" src="https://user-images.githubusercontent.com/84779829/208720042-734f0541-3e66-4866-bfb5-931028d3a14e.png">
- `content-length = 0` though file isn't 0 bytes - Probably it's bug

and I have lint error `make: *** [test-php-style] Error 8` when I run `make test-php-style-fix`

2022-12-21 03:21 UTC, individual-it requested changes
the linting issue is about the indention of the switch statement
![image](https://user-images.githubusercontent.com/2425577/208812975-af36cc75-eb42-46fd-b5fb-7843cd9a5e28.png)

2022-12-21 03:21 UTC, individual-it commented
do we need to test the headers here at all? Is there any client that relies on them?
And if yes, what about testing them where we test the copy operation itself?

2022-12-21 08:48 UTC, ScharfViktor commented
> do we need to test the headers here at all? Is there any client that relies on them? And if yes, what about testing them where we test the copy operation itself?

I forgot to mention why I created this test. https://github.com/owncloud/ocis/issues/5039

2022-12-21 09:01 UTC, ScharfViktor commented
> the linting issue is about the indention of the switch statement

Yes, I know. but I don't know how solve it


https://user-images.githubusercontent.com/84779829/208863985-eb25a92d-8e57-4c5a-a588-9a7cc51471d2.mov

2022-12-22 04:13 UTC, SagarGi commented
> > the linting issue is about the indention of the switch statement
> 
> Yes, I know. but I don't know how solve it
> 
>  Screen.Recording.2022-12-21.at.09.58.41.mov


i had the same problem like this before

2022-12-22 06:37 UTC, individual-it commented
wouldn't it be enough to test that the header is there and not checking the UUID itself?
```
And the following headers should match these regular expressions
      | Oc-Fileid | /^"[a-f0-9!\$-]{64}"$/ |
```

2022-12-22 07:04 UTC, ScharfViktor commented
> wouldn't it be enough to test that the header is there and not checking the UUID itself?
> 
> ```
> And the following headers should match these regular expressions
>       | Oc-Fileid | /^"[a-f0-9!\$-]{64}"$/ |
> ```

I think that will be enough. and I solve lint problem because I will delete `switch`
Thanks for the suggestion

2022-12-22 09:33 UTC, individual-it approved these changes

2022-12-28 13:50 UTC, micbar approved these changes

2022-12-28 13:50 UTC, merged

2023-01-05 06:33 UTC, phil-davis commented
Port to master is PR #5333