[tests-only][full-ci] Backport PR#5575
owncloud/ocis pull request #5671
Opened 2023-02-28 03:50 UTC by saw-jan

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2023-02-28 09:34 UTC, amrita-shrestha commented
@saw-jan Assign role via graph is added in oCIS master only. Please visit this link for verification https://github.com/owncloud/web/issues/8325 
I think there is no need of  backporting this PR https://github.com/owncloud/ocis/pull/5579 and https://github.com/owncloud/ocis/pull/5629

2023-02-28 10:00 UTC, saw-jan commented
> @saw-jan Assign role via graph is added in oCIS master only. Please visit this link for verification [owncloud/web#8325](https://github.com/owncloud/web/issues/8325) I think there is no need of backporting this PR #5579 and #5629

We can make the differences feature files
But the php codes need to be almost similar

2023-02-28 10:17 UTC, saw-jan commented
@grgprarup Please, review whether I have brought back the tests/codes that you have cleaned

2023-02-28 11:30 UTC, amrita-shrestha commented
> > @saw-jan Assign role via graph is added in oCIS master only. Please visit this link for verification [owncloud/web#8325](https://github.com/owncloud/web/issues/8325) I think there is no need of backporting this PR #5579 and #5629
> 
> We can make the differences in feature files But the php codes need to be almost similar. Making them similar makes it easier for future porting as well

If we not going to use such php code then does it even create problems in backporting?

2023-03-01 07:25 UTC, grgprarup reviewed
lgtm for me.

2023-03-01 09:16 UTC, saw-jan commented
> If we not going to use such php code then does it even create problems in backporting?

There should not be any issue if the file changes are in different lines. But mostly we will change Graph and Space related files so that will increase the chances of conflicts

2023-03-01 09:50 UTC, amrita-shrestha reviewed
i know you just cherry-pick other pick but i think there is some place where we can improve

2023-03-01 09:50 UTC, amrita-shrestha commented on tests/TestHelpers/GraphHelper.php
> +	public static function deleteGroup(
Now I know from which PR this method removed 😄

2023-03-01 09:50 UTC, amrita-shrestha commented on tests/acceptance/features/apiSpaces/changeSpaces.feature
> +      | role      | editor |
```suggestion
      | shareWith | Brian    |
      | role      | editor   |
```

2023-03-01 09:50 UTC, amrita-shrestha commented on tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
> +    And user "Alice" creates a share inside of space "share sub-item" with settings:
```suggestion
    When user "Alice" creates a share inside of space "share sub-item" with settings:
```

2023-03-01 09:50 UTC, amrita-shrestha commented on tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
> +      | file.txt | file   | editor |                          |            |
```suggestion
      | entity   | type   | role   | 
      | folder   | folder | viewer |  
      | file.txt | file   | viewer |         
      | file.txt | file   | editor |      
```

2023-03-01 09:56 UTC, amrita-shrestha requested changes
> As we discussed today with @ScharfViktor and @individual-it, we will maintain similar test (php) codes and feature files as well - and we tag skipOnStable2.0 to the scenarios that are not implemented in the stable branch.

> Key points:

>  - Maintain possible similar php codes
>   - tag scenarios that are not implemented in stable branch with skipOnStable2.0

This PR has not added scenario with skipOnStable2.0 tag . Please add that also

2023-03-02 09:26 UTC, grgprarup commented on tests/TestHelpers/GraphHelper.php
> +	public static function getGroup(
`deleteGroup` is not deleted, just line number is changed.

2023-03-03 04:29 UTC, individual-it commented
> i know you just cherry-pick other commit but i think there is some place where we can improve

I would suggest to have those small improvements in a separate PR, because if you do them in this PR, you have to port them again into master, so with a separate PR it would be cleaner and easier

2023-03-03 06:04 UTC, saw-jan reviewed
LGTM

2023-03-03 06:58 UTC, amrita-shrestha approved these changes
lgtm

2023-03-03 08:56 UTC, ScharfViktor approved these changes
LGTM :thumbsup:

2023-03-06 06:55 UTC, phil-davis approved these changes

2023-03-06 06:55 UTC, phil-davis commented on tests/acceptance/features/apiSpaces/spaceManagement.feature
> +@api @skipOnOcV10
I thought that we already deleted all the `skipOnOcV10` tags.
I will do that as a separate PR.

2023-03-06 06:57 UTC, phil-davis commented
The docker-arm pipeline https://drone.owncloud.com/owncloud/ocis/19870/85 does not start because there are no drone agents for that any more.

I will have a look and probably this PR just needs a rebase against the latest `stable-2.0`

2023-03-06 07:40 UTC, merged