graph: Use userType property to distinguish between Member and Guest accounts
owncloud/ocis pull request #5800
Opened 2023-03-10 12:43 UTC by Excds

## Description
Adding support for distinguishing member and guest users via userType property.

- Calling POST /graph/v1.0/users with userType not set will create a user as "Member"
- Calling POST /graph/v1.0/users with userType set as "Member" or "Guest" will create a user as "Member" or "Guest"
- Calling POST /graph/v1.0/users with userType set as anything but "Member" or "Guest" returns error
- Calling POST /graph/v1.0/education/users with userType not set will create a user as "Member"
- Calling POST /graph/v1.0/education/users with userType set as "Member" will create a user as "Member" and primary role as parameter specifies
- Calling POST /graph/v1.0/education/users with userType set as "Guest" will create a user as "Guest" and primary role as parameter specifies
- Calling POST /graph/v1.0/education/users with userType not set as anything but "Member" or "Guest" returns error
- Calling PATCH on /users or /education/users will update attribute in the same way as for POST

## Related Issue
- Fixes #5603 

## How Has This Been Tested?
Tested manually with curl and added unit tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2023-03-10 13:17 UTC, mmattel commented on services/graph/pkg/config/config.go
> +	UserTypeAttribute        string `yaml:"user_type_attribute" env:"LDAP_USER_SCHEMA_USER_TYPE;GRAPH_LDAP_USER_TYPE_ATTRIBUTE" desc:"LDAP Attribute to distinguish between 'Member' and 'Guest' users."`
ok, we can distinguish, but:
* to be added: `Supported values are 'ownCloudUserType'.`
* what are beside the default other possible values?

2023-03-13 10:20 UTC, butonic approved these changes

2023-03-13 10:38 UTC, rhafer requested changes
Please do not merge yet. I am still looking at this ...

2023-03-13 12:01 UTC, rhafer requested changes
A GET on https://localhost:9200/graph/v1.0/users/ does currently return an empty `userType` value for all users. (It does not seem to request the usertype LDAP attribute)

```
curl -k  -u admin:admin 'https://localhost:9200/graph/v1.0/users/
"value": [
    {
      "accountEnabled": true,
      "givenName": "Ralf",
      "id": "8c1d4734-2e96-102f-8b3b-970f196e2695",
      "onPremisesSamAccountName": "rhafer",
      "surname": "Haferkamp",
      "userType": ""
    },
...
```

When using an external LDAP server for which we cannot define a useful mapping for the `userType` property to an LDAP Attribute. We currently return an empty `userType` value. We should either always return `Member` in that case. Or not return the property at all.

2023-03-15 11:05 UTC, rhafer approved these changes

2023-03-15 11:05 UTC, merged