update ocis-accounts
owncloud/ocis pull request #591
Opened 2020-09-17 09:03 UTC by C0rby

This will include the password hash change.

2020-09-17 11:51 UTC, IljaN approved these changes

2020-09-18 08:22 UTC, refs approved these changes

2020-09-18 08:24 UTC, kulmann approved these changes

2020-09-23 08:59 UTC, refs requested changes
master on ocis-accounts is broken. Do mot merge yet.

2020-10-05 11:30 UTC, C0rby commented
Obsolete.

2020-10-05 11:30 UTC, closed without merging