[api-test] first notification test
owncloud/ocis pull request #5958
Opened 2023-03-29 13:45 UTC by ScharfViktor

2023-03-29 14:07 UTC, ScharfViktor commented on tests/acceptance/features/apiSpaces/notification.feature
> +                  "type": "string"
I don't check spaceUuid here. maybe this is unnecessary since there is also a name check

2023-03-29 14:07 UTC, ScharfViktor commented on tests/acceptance/features/bootstrap/NotificationContext.php
> +					"parameter" => [$spaceName]
it doesn't work and `[$this->spaceContext, "getSpaceIdByNameFromResponse"]` fails also.
previosly I met same in the `GraphContext`. I moved `getUserByName` and `getGroupByName` to `FeatureContext.php`.

of course I can move `getSpaceIdByNameFromResponse` but it causes a big refactoring. 
For now, I just wouldn't check spaceId.

2023-03-30 07:45 UTC, individual-it requested changes

2023-03-30 12:26 UTC, ScharfViktor commented on tests/acceptance/features/apiSpaces/notification.feature
> +                  "type": "string"
I check regex here in the feature file. I took an obscene amount of time to check this in featureContext but couldn't

2023-03-31 07:24 UTC, individual-it approved these changes

2023-03-31 07:42 UTC, merged