Disable Email Notifications
owncloud/ocis pull request #6137
Opened 2023-04-25 10:32 UTC by kobergj

Adds new setting to disable email  notifications

2023-04-25 11:02 UTC, ownclouders commented
E2E tests failed: https://drone.owncloud.com/owncloud/ocis/21745/68/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/ocis/21745/tracing/space-members-can-be-invited-with-an-expiration-date-alice-2023-4-25-10-57-58.zip 


</p></details>

<!-- id: pr-6137 -->

2023-04-26 09:17 UTC, mmattel commented
Needs webui documentation.
Will appear as item (when impemented by the web team) in the users personal settings.
Same location where the GDPR report request.

2023-04-26 13:47 UTC, 2403905 approved these changes

2023-04-26 16:13 UTC, micbar approved these changes

2023-04-26 20:56 UTC, kulmann commented on services/settings/pkg/store/defaults/defaults.go
> +				Name:        "disable email notifications",
Possible to use `disable-email-notifications` here? I'd prefer to keep blanks out of identifiers that are referenced in code. The web ui uses this name to identify the setting.

2023-04-26 20:58 UTC, kulmann commented on services/settings/pkg/store/defaults/defaults.go
> +	DisableEmailNotificationsPermissionName string = "disable-email-notifications"
If I recall correctly there was some decision to go with permission names like `EmailNotifications.Disable` in the future (first one was `PublicLink.Write`). Don't know the details of the decision and how to form permission names then, but this caught my eye...

2023-04-26 21:01 UTC, kulmann requested changes
Would love to see my two comments being discussed. Putting a `request changes` here to prevent accidental merges. If my comments are bogus please dismiss my review.

2023-04-27 05:01 UTC, JanAckermann requested changes

2023-04-27 05:01 UTC, JanAckermann commented on services/settings/pkg/store/defaults/defaults.go
> +	// DisableEmailNotificationsPermissionID is the hardcoded setting UUID for the language read write permission
The description is wrong -  not language

2023-04-27 05:01 UTC, JanAckermann commented on services/settings/pkg/store/defaults/defaults.go
> +	// DisableEmailNotificationsPermissionName is the hardcoded setting name for the language read write permission
Same here ^

2023-04-27 08:45 UTC, JanAckermann approved these changes

2023-04-27 11:35 UTC, merged