Storage Index [WIP]
owncloud/ocis pull request #624
Opened 2020-09-29 07:23 UTC by IljaN

2020-10-08 14:19 UTC, kulmann commented on accounts/pkg/service/v0/service.go
> +	if err := idx.AddIndex(&proto.Account{}, "OnPremisesSamAccountName", "Id", "accounts", "non_unique"); err != nil {
This needs to be a `unique` index.

2020-10-08 14:20 UTC, kulmann commented on accounts/pkg/service/v0/service.go
> +	if err := idx.AddIndex(&proto.Account{}, "DisplayName", "Id", "accounts", "unique"); err != nil {
This needs to be a `non_unique` index.

2020-10-08 14:27 UTC, IljaN commented on accounts/pkg/service/v0/service.go
> +	if err := idx.AddIndex(&proto.Account{}, "OnPremisesSamAccountName", "Id", "accounts", "non_unique"); err != nil {
:+1:

2020-10-08 14:27 UTC, IljaN commented on accounts/pkg/service/v0/service.go
> +	if err := idx.AddIndex(&proto.Account{}, "DisplayName", "Id", "accounts", "unique"); err != nil {
:+1:

2020-10-09 14:56 UTC, kulmann requested changes
So cool 😍 Some comments for tiny improvements. 😃

2020-10-23 09:51 UTC, IljaN commented
Merged via https://github.com/owncloud/ocis/pull/709

2020-10-23 09:51 UTC, closed without merging