[test-only] Api-test for sharing personal space
owncloud/ocis pull request #6242
Opened 2023-05-05 10:13 UTC by ScharfViktor

related #6238

- User cannot create share for personal space to user/group
- User cannot create public link for personal space

2023-05-05 10:30 UTC, ownclouders commented
:boom: Acceptance test [<strong>localApiTests-apiSpacesShares-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/22142/53/1) failed. Further test are cancelled...
<!-- id: pr-6242 -->

2023-05-12 05:52 UTC, individual-it requested changes

2023-05-12 05:52 UTC, individual-it commented on tests/acceptance/features/apiSpacesShares/shareSpaces.feature
> +  Scenario Outline: user cannot share a personal to user
```suggestion
  Scenario Outline: user cannot share the personal space to an other user
```

2023-05-12 05:52 UTC, individual-it commented on tests/acceptance/features/apiSpacesShares/shareSpaces.feature
> +  Scenario: user cannot share a personal to group
```suggestion
  Scenario: user cannot share the personal space to a group
```

2023-05-12 05:52 UTC, individual-it commented on tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
> +  Scenario: user cannot share a personal space to public via link
```suggestion
  Scenario: user cannot create a public link from the personal space
```

2023-05-12 08:23 UTC, individual-it approved these changes

2023-05-12 08:23 UTC, merged