Create README for settings service
owncloud/ocis pull request #6274
Opened 2023-05-10 14:19 UTC by rhafer

The just moves over the contents from  docs/services/settings/_index.md.

2023-05-10 14:21 UTC, rhafer commented
@kobergj Am I right to assume that the dev docs index page for settings (https://owncloud.dev/services/settings/) will be regenerated from this PR once it is merged?

2023-05-10 14:25 UTC, mmattel commented on services/settings/README.md
>  - Extensions can query ocis-settings for *settings values* of a user.
```suggestion
## Settings Usage
Services can query ocis-settings for *settings values* of a user.
```

2023-05-10 15:47 UTC, mmattel commented
> assume that the dev docs index page for settings will be regenerated from this PR

Just locally tested and as expected it gets regenerated 😃

2023-05-11 07:45 UTC, kobergj commented
@rhafer yes. Doc pages will be created automatically from the `README.md`

2023-05-12 16:56 UTC, mmattel commented
There are issues with the mermaid image:

* Though you can fix the codacy complains by defining this block as mermaid, it will then no longer be rendered as such in hugo. This needs a different approach.
* The mermaid content itself is wrong as it still uses the accounts service which was removed last year.

The cache definition text is imho wrong. On top you write about `SETTINGS_CACHE_STORE` but below in item 4 you define `STORAGE_USERS_STAT_CACHE_STORE_NODES` and
`STORAGE_USERS_FILEMETADATA_CACHE_STORE_NODES`. Beside the envvars used here (storage vs settings) if you have two items in redis-sentinel, you also must provide two on top. This is a 1:1 match.

2023-05-15 14:13 UTC, rhafer commented
> * Though you can fix the codacy complains by defining this block as mermaid, it will then no longer be rendered as such in hugo. This needs a different approach
The mermaid diagram would still be rendered correctly. `hugo` know abouth the ` ```mermaid ` syntax. But I have commented out the  diagram for now. It's outdated, as you already mentioned. And I can't make much sense of it anyway.

I've tried to update the contents to the best of my knowledge and fixed the copy'n paste error  for the variable names.

2023-05-15 15:22 UTC, micbar approved these changes

2023-05-15 16:57 UTC, mmattel requested changes
While reviewing, the following catched my eyes, copying text snipplets for the first two items:

* `metadata`: The default. This backend persists the settings data via the `storage-system` service.
* ...the settings service caches the results of queries to the `system-storage` for providing faster responses.
* When checking the `storage-system` service, this service has caching implemented.

Reading the items one will ask: why is there caching in the `settings` service if data is handed over to the `storage-system` service that already has caching? We must provide a sufficient answer for this.

2023-05-16 07:26 UTC, mmattel commented
Clarified with @rhafer what it is about, writing a small clarification, commit coming asap.

2023-05-16 07:46 UTC, mmattel approved these changes

2023-05-16 07:47 UTC, mmattel commented
I would like to ask @EParzefall for a language review as this is needed in the admin docs anyways.

2023-05-16 08:13 UTC, EParzefall approved these changes

2023-05-16 08:13 UTC, EParzefall commented on services/settings/README.md
> +The `settings` service provides functionality for other services to register new settings as well as storing and retrieving the respective settings values.
```suggestion
The `settings` service provides functionality for other services to register new settings as well as storing and retrieving the respective settings' values.
```

2023-05-16 08:13 UTC, EParzefall commented on services/settings/README.md
> +*   users' `profile` settings like the language and the Email notification settings,
```suggestion
*   users' `profile` settings like the language and the email notification settings,
```

2023-05-16 08:13 UTC, EParzefall commented on services/settings/README.md
> +*   possible user roles and their respecitve permssions,
```suggestion
*   possible user roles and their respective permissions,
```

2023-05-16 08:13 UTC, EParzefall commented on services/settings/README.md
> +As an example, user profile settings that can be changed in the Web UI must be persisted.
```suggestion
As an example, user profile settings that can be changed in the Web UI must be persistent.  
```

2023-05-16 08:13 UTC, EParzefall commented on services/settings/README.md
> +The settings service supports two different backends for persisting the data. The backend can be set using `SETTINGS_STORE_TYPE` environment variable. Supported values are:
```suggestion
The settings service supports two different backends for persisting the data. The backend can be set via the `SETTINGS_STORE_TYPE` environment variable. Supported values are:
```

2023-05-16 08:13 UTC, EParzefall commented on services/settings/README.md
> +When using `SETTINGS_STORE_TYPE=metadata`, the settings service caches the results of queries against the storage backend for providing faster responses. The content of this cache is independent of t
```suggestion
When using `SETTINGS_STORE_TYPE=metadata`, the `settings` service caches the results of queries against the storage backend to provide faster responses. The content of this cache is independent of the cache used in the `storage-system` service as it caches directory listing and settings content stored in files.
```

2023-05-16 08:13 UTC, EParzefall commented on services/settings/README.md
> +oCIS services can register *settings bundles* with the settings service.
```suggestion
Infinite Scale services can register *settings bundles* with the settings service.
```

2023-05-16 08:25 UTC, phil-davis approved these changes

2023-05-16 09:43 UTC, merged