[doc] Document running tests using ociswrapper
owncloud/ocis pull request #6283
Opened 2023-05-11 11:45 UTC by saw-jan

## Description
Added documentation on running tests with ociswrapper for env config test features

- [x] readme for ociswrapper
- [ ] add doc in testing section
- [ ] update docker-compose test setup

## Related Issue
Follow up https://github.com/owncloud/ocis/pull/6062

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2023-05-15 13:48 UTC, saw-jan commented on tests/ociswrapper/README.md
> +A tool to wraps the oCIS binary and provides a way to re-configure the running oCIS instance.
```suggestion
A tool to wrap the oCIS binary and provides a way to re-configure the running oCIS instance.
```

2023-05-15 15:02 UTC, ScharfViktor commented on tests/ociswrapper/README.md
> +1. Build
`[list-item-indent] Incorrect list-item indent: add 1 space`

2023-05-16 03:36 UTC, saw-jan commented on tests/ociswrapper/README.md
> +   ./bin/ociswrapper serve --bin=<path-to-ocis-binary>
Yeah, we can change it to other than `5000`

2023-05-16 03:54 UTC, saw-jan commented on tests/ociswrapper/README.md
> +   ./bin/ociswrapper serve --bin=<path-to-ocis-binary>
Changed it to `5200`. WIll it be suitable?

2023-05-16 05:04 UTC, phil-davis reviewed
Just some minor English edits. I haven't actually tried all the instructions.

2023-05-16 05:04 UTC, phil-davis commented on docs/ocis/development/testing.md
> +Test suites tagged with `@env-config` are used to test the environment variables that are used to configure oCIS. These tests are special tests that require oCIS server to be run using [ociswrapper](
```suggestion
Test suites tagged with `@env-config` are used to test the environment variables that are used to configure oCIS. These tests are special tests that require the oCIS server to be run using [ociswrapper](https://github.com/owncloud/ocis/blob/master/tests/ociswrapper/README.md).
```

2023-05-16 05:04 UTC, phil-davis commented on docs/ocis/development/testing.md
> +While writing tests for a new oCIS ENV configuration, please make sure to follow the below guidelines:
```suggestion
While writing tests for a new oCIS ENV configuration, please make sure to follow these guidelines:
```

2023-05-16 05:04 UTC, phil-davis commented on docs/ocis/development/testing.md
> +2. Use `OcisConfigHelper.php` for helper functions - provides functions to reconfigure running oCIS instance.
```suggestion
2. Use `OcisConfigHelper.php` for helper functions - provides functions to reconfigure the running oCIS instance.
```

2023-05-16 05:04 UTC, phil-davis commented on docs/ocis/development/testing.md
> +Test suites that are tagged with `@email` require email service. We use inbucket as the email service in our tests.
```suggestion
Test suites that are tagged with `@email` require an email service. We use inbucket as the email service in our tests.
```

2023-05-16 05:04 UTC, phil-davis commented on tests/ociswrapper/README.md
> +A tool to wrap the oCIS binary and provides a way to re-configure the running oCIS instance.
```suggestion
A tool that wraps the oCIS binary and provides a way to re-configure the running oCIS instance.
```

2023-05-16 05:49 UTC, individual-it requested changes
1. changes that are not related to the ociswrapper should be in an other PR
2. `WITH_WRAPPER=true` should be the default setting, so that developers who run the tests can run any test without having to think about it (separate PR)

2023-05-16 05:52 UTC, ScharfViktor commented on tests/ociswrapper/README.md
> +   ./bin/ociswrapper serve --bin=<path-to-ocis-binary>
Yes, port 5200 is free. Thanks

<img width="713" alt="image" src="https://github.com/owncloud/ocis/assets/84779829/03b3dbb4-9e0a-4640-8004-ba8f4b3cbb56">

2023-05-16 06:03 UTC, saw-jan commented on tests/ociswrapper/README.md
> +   ./bin/ociswrapper serve --bin=<path-to-ocis-binary>
I have made some changes in this PR to make it easy to review.
So, I will change the port number in next PR

2023-05-16 06:11 UTC, saw-jan commented on docs/ocis/development/testing.md
> +OCIS_WRAPPER_URL=https://localhost:5000 \
Will be done in the next PR

2023-05-16 06:21 UTC, individual-it requested changes

2023-05-16 06:21 UTC, individual-it commented on docs/ocis/development/testing.md
> +But some test suites that are tagged `@env-config` require the oCIS server to be run with ociswrapper. So, running those tests require `WITH_WRAPPER=true`.
```suggestion
But test suites that are tagged with `@env-config` require the oCIS server to be run with ociswrapper. So, running those tests require `WITH_WRAPPER=true` (default setting).
```

2023-05-16 06:21 UTC, individual-it commented on tests/acceptance/docker/Makefile
> +# runn tests with ociswrapper by default
```suggestion
# run tests with ociswrapper by default
```

2023-05-16 06:29 UTC, individual-it approved these changes

2023-05-16 08:54 UTC, merged