Release template
owncloud/ocis pull request #6501
Opened 2023-06-12 14:35 UTC by ScharfViktor

- I created release template like in the client https://github.com/owncloud/client/blob/master/.github/release_template.md
Separately, I put the out existing smoke tests to https://github.com/owncloud/QA and link it
Note: some links will be available after merging https://github.com/owncloud/QA/pull/813

2023-06-12 14:41 UTC, mmattel commented on .github/release_template.md
> +* [ ] Migration Doc @mmattel
```suggestion
* [ ] Release Notes + Breaking Changes @tbsbdr
* [ ] Migration + Breaking Changes Admin Doc @mmattel
* [ ] Migration + Breaking Changes Helm Chart Doc @wkloucek @mmattel
```

2023-06-13 05:08 UTC, individual-it requested changes
just small formatting to make it clear that the mac/win/linux belongs to "desktop"
The rest looks good :+1:

2023-06-13 05:08 UTC, individual-it commented on .github/release_template.md
> +  * [ ] QA: against linux (use auto tests)
```suggestion
  * [ ] QA: desktop (define version) https://github.com/owncloud/client/releases
      * [ ] QA: against mac - smoke test
      * [ ] QA: against windows - smoke test
      * [ ] QA: against linux (use auto tests)
```

2023-06-13 05:25 UTC, phil-davis commented on .github/release_template.md
> +* [ ] QA: [Perfomance test](https://github.com/owncloud/cdperf/tree/main/packages/k6-tests/src)
```suggestion
* [ ] QA: [Performance test](https://github.com/owncloud/cdperf/tree/main/packages/k6-tests/src)
```

2023-06-13 10:31 UTC, mmattel commented on .github/release_template.md
> +* [ ] DEV: Create stable-3.0 branch from final tag
```suggestion
### Post-Release Communication
* [ ] DEV: Create a docs-stable-x.y branch based on the docs folder in the ocis repo @micbar 
* [ ] DEV: Create a x.y.z release in the ocis-helm repo (frozen state) @wkloucek
* [ ] DEV/QA: Ping documentation in RC about the new release tag (for ocis/helm chart version bump in docs)
* [ ] DEV/QA: Ping marketing to update all download links (download mirrors are updated at the full hour, wait with ping until download is actually available)
* [ ] DEV/QA: Ping @hodyroff once the demo instances are running this release
* [ ] DEV/QA: notify @michaelstingl @hosy @fmoc @jesmrec to publish client finals
* [ ] DEV: Merge back release branch
* [ ] DEV: Create stable-x.y branch in the ocis repo from final tag
```
Some small improvements and clarifications.

2023-06-13 10:54 UTC, phil-davis approved these changes

2023-06-13 11:37 UTC, mmattel commented on .github/release_template.md
> +* [ ] DEV: bump released deployments to `v3.0.0-rc.1`
```suggestion
* [ ] DEV: Create signed tag `vx.y.z-rc.1`
* [ ] DEV: Check successful CI run on `vx.y.z-rc.1` tag / BLOCKING for all further activity
* [ ] DEV: Merge back release branch
* [ ] DEV: bump released deployments to `vx.y.z-rc.1`
```

2023-06-13 11:59 UTC, mmattel approved these changes

2023-06-14 07:24 UTC, individual-it approved these changes

2023-06-14 07:30 UTC, merged