[tests-only] [full-ci] Refactoring example table dav-version text
owncloud/ocis pull request #6697
Opened 2023-07-03 10:59 UTC by S-Panta

## Description
This PR refactors the feature files text so that everywhere the word "dav-path-version" is coherent rather than using different variations of that phrase. 

## Related Issue
- Part of <https://github.com/owncloud/ocis/issues/5337>

## How Has This Been Tested?

- locally:
- ci:

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2023-07-04 03:53 UTC, SwikritiT commented
Note if we are doing this here we might need to do this in core as well
cc @amrita-shrestha @grgprarup

2023-07-04 05:45 UTC, amrita-shrestha requested changes
please format table

2023-07-04 05:45 UTC, amrita-shrestha commented on tests/acceptance/features/coreApiWebdavLocks/exclusiveLocks.feature
>        | spaces   | exclusive  |
FORMAT TABLE

2023-07-04 05:45 UTC, amrita-shrestha commented on tests/acceptance/features/coreApiWebdavLocks/exclusiveLocks.feature
>        | spaces   | exclusive  |
same here

2023-07-04 05:45 UTC, amrita-shrestha commented on tests/acceptance/features/coreApiWebdavLocks/exclusiveLocks.feature
>        | spaces   | exclusive  |
same here

2023-07-04 05:45 UTC, amrita-shrestha commented on tests/acceptance/features/coreApiWebdavLocks/exclusiveLocks.feature
>        | spaces   | exclusive  |
here too

2023-07-04 05:45 UTC, amrita-shrestha commented on tests/acceptance/features/coreApiWebdavLocksUnlock/unlock.feature
>        | spaces   |
same here

2023-07-04 05:45 UTC, amrita-shrestha commented on tests/acceptance/features/coreApiWebdavLocksUnlock/unlock.feature
>        | spaces   | exclusive  |
here too

2023-07-04 05:49 UTC, amrita-shrestha commented
> Note if we are doing this here we might need to do this in core as well cc @amrita-shrestha @grgprarup

If our customer care about core and why not sure 😄

2023-07-04 07:14 UTC, grgprarup commented on tests/acceptance/features/apiAsyncUpload/delayPostprocessing.feature
> +    When user "Alice" requests "<dav-path-version>" with "GET" without retrying
Let it be dav_path, it's different. `dav_path` is used for the path of endpoints, whereas `dav-path`, `dav-path-version`, and `dav_version` are used for the WebDAV versions.

2023-07-04 07:17 UTC, grgprarup requested changes
Do not need to change `dav_path`, it's different. dav_path is used for the path of endpoints, whereas dav-path, dav-path-version, and dav_version are used for the WebDAV versions.

2023-07-04 09:32 UTC, amrita-shrestha reviewed
lgtm

2023-07-04 10:18 UTC, saw-jan reviewed
LGTM. there are come conflicts

2023-07-05 03:36 UTC, saw-jan requested changes
Rebasing was not correct

2023-07-05 03:36 UTC, saw-jan commented on tests/acceptance/features/coreApiTrashbinRestore/trashbinRestore.feature
> +>>>>>>> c36920bf6c (Corrected the issues)
```suggestion
      | dav-path-version |
      | old              |
      | new              |
```

2023-07-05 03:36 UTC, saw-jan commented on tests/acceptance/features/coreApiVersions/fileVersions.feature
> +    And user "Alice" has uploaded file with content "Content Test Updated." to "/davtest.txt"old
```suggestion
    And user "Alice" has uploaded file with content "Content Test Updated." to "/davtest.txt"
```

2023-07-05 03:36 UTC, saw-jan commented on tests/acceptance/features/coreApiWebdavLocksUnlock/unlockSharingToShares.feature
> +      | new              | exclusive  |
```suggestion
      | dav-path-version | lock-scope |
      | old              | shared     |
      | old              | exclusive  |
      | new              | shared     |
      | new              | exclusive  |
```

2023-07-05 03:36 UTC, saw-jan commented on tests/acceptance/features/coreApiWebdavLocksUnlock/unlockSharingToShares.feature
> +>>>>>>> c36920bf6c (Corrected the issues)
```suggestion
      | dav-path-version | lock-scope |
      | spaces           | shared     |
      | spaces           | exclusive  |
```

2023-07-05 03:36 UTC, saw-jan commented on tests/acceptance/features/coreApiWebdavLocksUnlock/unlockSharingToShares.feature
> +      | new              | exclusive  |
```suggestion
      | dav-path-version | lock-scope |
      | old              | shared     |
      | old              | exclusive  |
      | new              | shared     |
      | new              | exclusive  |
```

2023-07-05 03:36 UTC, saw-jan commented on tests/acceptance/features/coreApiWebdavLocksUnlock/unlockSharingToShares.feature
> +>>>>>>> c36920bf6c (Corrected the issues)
```suggestion
      | dav-path-version | lock-scope |
      | spaces           | shared     |
      | spaces           | exclusive  |
```

2023-07-05 03:36 UTC, saw-jan commented on tests/acceptance/features/coreApiWebdavLocksUnlock/unlockSharingToShares.feature
> +      | new              | exclusive  | /parent.txt        |
```suggestion
      | dav-path-version | lock-scope |
      | old              | shared     |
      | old              | exclusive  |
      | new              | shared     |
      | new              | exclusive  |

    @skipOnRevaMaster
    Examples:
      | dav-path-version | lock-scope |
      | spaces           | shared     |
      | spaces           | exclusive  |
```

2023-07-05 03:36 UTC, saw-jan commented on tests/acceptance/features/coreApiWebdavLocksUnlock/unlockSharingToShares.feature
> +>>>>>>> c36920bf6c (Corrected the issues)
```suggestion
```

2023-07-05 03:36 UTC, saw-jan commented on tests/acceptance/features/coreApiWebdavOperations/propfind.feature
> +      | dav-path-version            | depth    |
```suggestion
      | dav-path-version            | depth    |
```

2023-07-05 03:36 UTC, saw-jan commented on tests/acceptance/features/coreApiWebdavOperations/propfind.feature
> +>>>>>>> 82922a1211 (Corrected the api naming into 'dav_path')
```suggestion
```

2023-07-05 03:38 UTC, SagarGi commented on tests/acceptance/features/coreApiVersions/fileVersions.feature
> +    And user "Alice" has uploaded file with content "Content Test Updated." to "/davtest.txt"old
```suggestion
    And user "Alice" has uploaded file with content "Content Test Updated." to "/davtest.txt"
```
by mistake?

2023-07-05 03:38 UTC, SagarGi commented on tests/acceptance/features/coreApiWebdavLocksUnlock/unlockSharingToShares.feature
> +>>>>>>> c36920bf6c (Corrected the issues)
unhandled conflict

2023-07-05 03:38 UTC, SagarGi commented on tests/acceptance/features/coreApiWebdavLocksUnlock/unlockSharingToShares.feature
> +>>>>>>> c36920bf6c (Corrected the issues)
unresolved conflict

2023-07-05 03:38 UTC, SagarGi commented on tests/acceptance/features/coreApiWebdavLocksUnlock/unlockSharingToShares.feature
> +>>>>>>> c36920bf6c (Corrected the issues)
unresolved conflict

2023-07-05 03:38 UTC, SagarGi commented on tests/acceptance/features/coreApiWebdavOperations/propfind.feature
> +>>>>>>> 82922a1211 (Corrected the api naming into 'dav_path')
unresloved conflict

2023-07-05 05:32 UTC, saw-jan approved these changes
LGTM

2023-07-06 04:16 UTC, amrita-shrestha approved these changes
lgtm

2023-07-10 07:05 UTC, saw-jan approved these changes

2023-07-10 07:14 UTC, grgprarup commented on drone
Remove this file.

2023-07-10 07:18 UTC, grgprarup commented
Refactor `dav_version` to `dav-path-version` too, in the same PR.

2023-07-10 07:21 UTC, saw-jan requested changes
Please, address the reviews

2023-07-10 11:34 UTC, saw-jan commented on tests/acceptance/features/coreApiWebdavProperties1/setFileProperties.feature
> +      | action_dav-path-version | other_dav-path-version |
```suggestion
      | action-dav-path-version | other-dav-path-version |
```

2023-07-10 11:34 UTC, saw-jan commented on tests/acceptance/features/coreApiWebdavProperties1/setFileProperties.feature
> +      | action_dav-path-version | other_dav-path-version |
```suggestion
      | action-dav-path-version | other-dav-path-version |
```

2023-07-11 04:04 UTC, saw-jan reviewed
LGTM

2023-07-11 06:12 UTC, grgprarup reviewed
LGTM

2023-07-11 06:13 UTC, grgprarup commented
Backport to stable-3.0 after this PR gets merged.

2023-07-11 06:13 UTC, grgprarup approved these changes

2023-07-12 06:57 UTC, saw-jan approved these changes

2023-07-12 06:57 UTC, merged