[tests-only][full-ci]add test for sharee searches project spaces files using a tag
owncloud/ocis pull request #7036
Opened 2023-08-15 08:57 UTC by nabim777

## Description
This PR adds the API tests for searching project space files by sharee using a tag. The scenarios added in this PR are
- sharee searches shared project spaces files using a tag

## Related Issue
- https://github.com/owncloud/ocis/issues/6606#event-9635806756

## Motivation and Context
- there was no test coverage for the API test for Sharee searches project files using a tag. so, this PR covers the require scenario test case

## How Has This Been Tested?
- test environment:
- locally
- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2023-08-16 06:50 UTC, saw-jan commented on tests/acceptance/features/apiGraph/fullSearch.feature
> +      | spacesFileInsideSubFolder.txt |
PLease, use full path
```suggestion
    And the search result of user "Alice" should contain only these files:
      | spacesFile.txt                |
      | spacesFolderWithFile/spacesFileInsideFolder.txt    |
      | spacesFolderWithFile/spacesSubFolder/spacesFileInsideSubFolder.txt |
```

2023-08-16 06:54 UTC, saw-jan commented on tests/acceptance/features/apiGraph/fullSearch.feature
> +  Scenario Outline: sharee searches shared project spaces files using a tag
```suggestion
  Scenario Outline: sharee searches shared project space files using a tag
```

2023-08-16 09:08 UTC, saw-jan approved these changes
LGTM

2023-08-17 03:24 UTC, SwikritiT requested changes
the brach is a lot of commits behind master https://github.com/owncloud/ocis/tree/search-project-spaces-by-sharee-using-tag
please rebase and push

2023-08-17 04:19 UTC, SagarGi reviewed
LGTM :+1:  please rebase it.

2023-08-18 04:21 UTC, SwikritiT approved these changes

2023-08-18 04:43 UTC, merged