support AD FS
owncloud/ocis pull request #7140
Opened 2023-08-29 12:38 UTC by butonic

AD FS `/adfs/.well-known/openid-configuration` has an optional `access_token_issuer` which, in violation of the OpenID Connect spec, takes precedence over `issuer`.

2023-08-29 13:59 UTC, rhafer approved these changes
**sigh** :disappointed: :skull_and_crossbones: :hankey: :bomb:

I guess we have to ...

2023-08-29 14:04 UTC, kobergj requested changes

2023-08-29 14:04 UTC, kobergj commented on ocis-pkg/oidc/client.go
> +	if !validIssuer {
```suggestion
	issuer := c.issuer
	if c.provider.AccessTokenIssuer != "" {
		// AD FS .well-known/openid-configuration has an optional `access_token_issuer` which takes precedence over `issuer`
		// See https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-oidce/586de7dd-3385-47c7-93a2-935d9e90441c
		issuer = c.provider.AccessTokenIssuer
	}

	if !claims.VerifyIssuer(issuer, true) {
```

Can we avoid unnecessary `else` statements please? They are nothing but complicated.

2023-08-30 07:13 UTC, kobergj approved these changes

2023-09-01 13:25 UTC, merged