[tests-only][full-ci]Update expected to failure based on correct issue
owncloud/ocis pull request #7211
Opened 2023-09-05 04:08 UTC by SagarGi

### Description
Since this issue https://github.com/owncloud/ocis/issues/4393 was closed so that needs to be updated according to this issue linke for it. https://github.com/owncloud/ocis/issues/4393#issuecomment-1672885146. But New issue is created according to the actual behavior since the expected behavior is unknown. So This PR updates the expected to failure with the new issue created for the same failing test.

### Related Issue:
https://github.com/owncloud/ocis/issues/4393#issuecomment-1672885146

2023-09-05 04:29 UTC, SwikritiT approved these changes
LGTM

2023-09-05 05:51 UTC, SwikritiT requested changes
let's wait till decision from dev team

2023-09-05 06:01 UTC, saw-jan approved these changes

2023-09-12 11:19 UTC, SagarGi commented
This PR is put on hold since this issue has been in look by the development team. So this PR can be waited till some notice from them.

2023-09-15 05:58 UTC, SwikritiT approved these changes

2023-09-15 06:00 UTC, SwikritiT commented
let's merge this PR. as this is not adding new test but updating the issue only. The test will probably be removed in the PR where the bug is fixed

2023-09-15 08:51 UTC, merged