[docs-only]Remove deprecated env
owncloud/ocis pull request #7376
Opened 2023-09-28 06:25 UTC by amrita-shrestha

## Description
Now core tests have been transferred to ocis repo so we don't need `TEST_OCIS` env. So removing `TEST_OCIS`

## Related Issue
- Fixes https://github.com/owncloud/ocis/issues/7300

## Motivation and Context

## How Has This Been Tested?

- Locally

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2023-09-28 07:22 UTC, saw-jan commented on tests/acceptance/run.sh
>  	# Tell the tests to wait 1 second between each upload/delete action
if block can be removed

2023-09-29 03:37 UTC, individual-it approved these changes

2023-09-29 03:50 UTC, saw-jan commented on tests/acceptance/run.sh
> +export UPLOAD_DELETE_WAIT_TIME=1
what I meant was the whole if block is not required.
```suggestion
```

2023-09-29 03:51 UTC, saw-jan requested changes

2023-09-29 03:51 UTC, saw-jan commented on tests/acceptance/run.sh
> +export UPLOAD_DELETE_WAIT_TIME=1
what I meant was the whole if block is not required.
```suggestion
```

2023-09-29 10:09 UTC, saw-jan approved these changes
LGTM

2023-09-29 10:19 UTC, phil-davis approved these changes

2023-09-29 10:19 UTC, merged