feature(thumbnails): add the ability to define custom image processors
owncloud/ocis pull request #7409
Opened 2023-10-04 11:12 UTC by fschade

## Description
detailed description follows

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2023-10-04 15:00 UTC, mmattel commented
@fschade pls add your description to the readme of the thumbnail service, thx

2023-10-05 08:47 UTC, mmattel commented on services/thumbnails/README.md
> +* thumbnail
```suggestion
*   resize
*   fit
*   fill
*   thumbnail
```
Fixing codacy complains

2023-10-05 13:47 UTC, kobergj requested changes

2023-10-05 13:47 UTC, kobergj commented on services/thumbnails/pkg/thumbnail/generator.go
> -func (g GifGenerator) GenerateThumbnail(size image.Rectangle, img interface{}) (interface{}, error) {
exported func `Generate` should have comment or be unexported

2023-10-05 13:47 UTC, kobergj commented on services/thumbnails/pkg/thumbnail/processor.go
> +func ProcessorFor(id, fileType string) (Processor, error) {
Imho this should return a `DefinableProcessor` (return structs, expect interfaces) But this is very nitpicky I admit

2023-10-05 13:48 UTC, kobergj requested changes

2023-10-05 13:48 UTC, kobergj commented on services/thumbnails/pkg/thumbnail/generator.go
> +func (g GifGenerator) Generate(size image.Rectangle, img interface{}, processor Processor) (interface{}, error) {
exported func Generate should have comment or be unexported

2023-10-12 06:24 UTC, tbsbdr commented
@kobergj If you have the chance, could you (or someone else) review this PR? (I'm really looking forward having this improvement/fix). thanks @fschade for the implementation!

2023-10-16 07:18 UTC, mmattel commented on services/thumbnails/README.md
> +to apply one of those, a query parameter has to be added to the request, e.g. `?processor=fit`
```suggestion
*   `resize`
*   `fit`
*   `fill`
*   `thumbnail`

To apply one of those, a query parameter has to be added to the request, e.g. `?processor=fit`
```
Just a minor finding I missed before

2023-10-16 07:25 UTC, mmattel commented
LGTM from a docs pov 👍

2023-10-16 12:42 UTC, mmattel commented on services/thumbnails/README.md
> +To apply one of those, a query parameter has to be added to the request, e.g. `?processor=fit`
If I recall correctly, this is optional, means behaviour equals before if not added.
Maybe to write: `Image generation can optionally be configured...`
But @fschade can clarify best.

2023-10-16 14:26 UTC, fschade commented
@michaelstingl scalingup has no effect if i remember correctly, `a` is new to me, i can add a fallback if you want, but please let me add it in a separate pr.

2023-10-16 14:27 UTC, fschade commented on services/thumbnails/README.md
> +Returned: 15x10
not sure, i have to have a look into the codebase, to be honest, i do not know every thumbnail service detail. please create a issue if we should change something.

2023-10-16 14:29 UTC, fschade commented on services/thumbnails/README.md
> +To apply one of those, a query parameter has to be added to the request, e.g. `?processor=fit`
if no processor is provided it uses the default behaviour as before (Resize fort gif, Thumbnail for everything else)

2023-10-16 18:15 UTC, michaelstingl commented on services/thumbnails/README.md
> +Returned: 15x10
Okay, I’ll play with it and I’ll open new issues if needed.

2023-10-16 18:16 UTC, michaelstingl commented
Okay, I’ll play with it and I’ll open new issues if needed.

2023-10-17 07:44 UTC, kobergj approved these changes

2023-10-17 07:44 UTC, merged