the default language added to the setting service
owncloud/ocis pull request #7417
Opened 2023-10-05 14:38 UTC by 2403905

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2023-10-05 15:20 UTC, mmattel commented on services/settings/pkg/config/config.go
> +	DefaultLanguage string `yaml:"default_language" env:"SETTINGS_DEFAULT_LANGUAGE" desc:"The default language. If not defined, the English will be used as default."`
```suggestion
	DefaultLanguage string `yaml:"default_language" env:"SETTINGS_DEFAULT_LANGUAGE" desc:"The default language. If not defined, English will be used as default."`
```
Do we work with language codes, or what to enter?

2023-10-05 15:20 UTC, mmattel commented on services/settings/README.md
> +The default language can be defined via SETTINGS_DEFAULT_LANGUAGE environment variable. If this variable is not defined, the English language will be used as default.
```suggestion
The default language can be defined via SETTINGS_DEFAULT_LANGUAGE environment variable. If this variable is not defined, English will be used as default.
```

2023-10-05 15:25 UTC, mmattel commented
What are the values that can be entered for a language and how to identify which languages are available?

2023-10-05 15:33 UTC, 2403905 commented
> What are the values that can be entered for a language and how to identify which languages are available?

Good catch. I'll add

2023-10-06 09:39 UTC, kobergj requested changes

2023-10-06 09:39 UTC, kobergj commented on services/settings/pkg/service/v0/servicedecorator.go
> +		defaultLanguage = "en"
can we extract `"en"` to a global `var _defaultLanguage`?

2023-10-06 09:39 UTC, kobergj commented on services/settings/pkg/service/v0/servicedecorator.go
> +	}
Shouldn't we only add the language if it was actually requested? I mean `GetValueByUniqueIdentifier` sounds to me like I can also get other settings except language here. But if request another value and it is not found, I would still get the default language setting...

2023-10-06 09:39 UTC, kobergj commented on services/settings/pkg/service/v0/servicedecorator.go
> +			Id:          "",
Doesn't it need an ID?

2023-10-06 14:51 UTC, mmattel commented on services/settings/README.md
> +The default language can be defined via SETTINGS_DEFAULT_LANGUAGE environment variable. If this variable is not defined, English will be used as default. The value has ISO 639-1 format ("de", "en", e
```suggestion
The default language can be defined via SETTINGS_DEFAULT_LANGUAGE environment variable. If this variable is not defined, English will be used as default. The value has the ISO 639-1 format ("de", "en", etc.) and is limited by the list supported languages. This setting can be used to set the default language for invitation emails.
```

2023-10-06 14:53 UTC, mmattel commented
> The value has the ISO 639-1 format ("de", "en", etc.) and is limited by the list supported languages.

Do we have a fallback if one sets an unsupported language to use the default?
If not, this must be implemented, if yes we should add this behaviour to readme.md.

2023-10-09 07:26 UTC, kobergj approved these changes

2023-10-09 07:52 UTC, mmattel commented on services/settings/README.md
> +## Default language
```suggestion
## Default Language
```

2023-10-09 08:57 UTC, mmattel commented on services/settings/README.md
> +The default language can be defined via SETTINGS_DEFAULT_LANGUAGE environment variable. If this variable is not defined, English will be used as default. The value has the ISO 639-1 format ("de", "en
```suggestion
The default language can be defined via SETTINGS_DEFAULT_LANGUAGE environment variable. If this variable is not defined, English will be used as default. The value has the ISO 639-1 format ("de", "en", etc.) and is limited by the list supported languages. This setting can be used to set the default language for invitation emails.

Important developer note: the list of supported languages is at the moment not easy defineable, as it is the minimum intersection of languages shown in the WebUI and languages defined in the ocis code for the use of notifications. Even more, not all languages where there are translations available on transifex, are available in the WebUI respectively for ocis notifications, and the translation rate for existing languages is partially not that high. You will see therefore quite often English default strings though a supported language may exist and was selected.
```

2023-10-09 09:00 UTC, mmattel approved these changes
Looks good from a docs POV

2023-10-09 13:31 UTC, merged