fix: search capabilities format
owncloud/ocis pull request #7551
Opened 2023-10-20 09:22 UTC by fschade

## Description
fix search capabilities format, needs reva PR

## Related Issue
- Base https://github.com/cs3org/reva/pull/4271

2023-10-20 09:28 UTC, 2403905 approved these changes

2023-10-20 09:51 UTC, kobergj requested changes
Can you add the PR to `changelog/unreleased/bump-reva.md`? It bumps reva and we need to keep track of reva changes

2023-10-20 15:53 UTC, 2403905 approved these changes

2023-10-23 07:28 UTC, kobergj approved these changes

2023-10-23 07:28 UTC, merged