bump mockery, add test stub for oidc_auth.go
owncloud/ocis pull request #8321
Opened 2024-01-30 14:52 UTC by butonic

to test the oidc_auth.go we need to mock the oidc client ... which turns out is broken with older versions of mockery so we bump that as well.

I'll change the other mocks to use the new tooling as well.

2024-01-31 14:07 UTC, aduffeck commented
:+1: for using `{{.PackageName}}/mocks` consistently. the `PackagePath` default adds quite some clutter and collecting all mocks in a single package doesn't help with cleanness either.

2024-01-31 15:14 UTC, butonic commented
Ok, but for the protobuf generated code we should maybe generate the mocks in the protogen package

2024-01-31 17:49 UTC, butonic commented
ok, I moved all mocks to a more meaningful place, if the interface is
1. defined in the current package put the mockh into a `mocks` sub package
2. generated (e.g. protobuf) put them into a `mocks` sub package of the generated code
3. in ocis-pkg but it in a `mocks` sub package there, but use it from tests in e.g. the services
4. defined in an external package put it into a `mocks` sub package of the test that uses it

all good? If so ✔️ and merge!

2024-02-01 08:31 UTC, aduffeck requested changes

2024-02-01 08:31 UTC, aduffeck commented on services/proxy/pkg/middleware/oidc_auth_test.go
> +	)
The whole `ub` var seems to be unused and could be removed, no?
```suggestion
```

2024-02-01 08:44 UTC, aduffeck approved these changes

2024-02-01 09:07 UTC, merged