[tests-only][full-ci]resourcetype variable deleted from testcode
owncloud/ocis pull request #8370
Opened 2024-02-06 06:36 UTC by S-Panta

This PR deletes the step implementation of test code along with its related steps regarding resource type variable.
Related issue: https://github.com/owncloud/ocis/issues/8349

2024-02-07 10:34 UTC, PrajwolAmatya reviewed
lgtm

2024-02-08 12:48 UTC, saw-jan requested changes
we should keep this

2024-02-08 12:48 UTC, saw-jan commented on tests/acceptance/features/apiSharingNg/deletePermissions.feature
> +    When user "Alice" removes the share permission of link from "FolderToShare" of space "Personal" using the Graph API
```suggestion
    When user "Alice" removes the share permission of link from folder "FolderToShare" of space "Personal" using the Graph API
```

2024-02-08 12:48 UTC, saw-jan commented on tests/acceptance/features/bootstrap/SharingNgContext.php
> +	 * @When /^user "([^"]*)" removes the share permission of (user|group) "([^"]*)" from "([^"]*)" of space "([^"]*)" using the Graph API$/
```suggestion
	 * @When /^user "([^"]*)" removes the share permission of (user|group) "([^"]*)" from (?:file|folder) "([^"]*)" of space "([^"]*)" using the Graph API$/
```

2024-02-08 12:48 UTC, saw-jan commented on tests/acceptance/features/bootstrap/SharingNgContext.php
> +	 * @When /^user "([^"]*)" removes the share permission of link from "([^"]*)" of space "([^"]*)" using the Graph API$/
```suggestion
	 * @When /^user "([^"]*)" removes the share permission of link from (?:file|folder) "([^"]*)" of space "([^"]*)" using the Graph API$/
```

2024-02-09 08:17 UTC, saw-jan approved these changes

2024-02-09 08:17 UTC, merged