enhancement: allow sending multiple userIDs in one SSE event
owncloud/ocis pull request #8379
Opened 2024-02-06 13:41 UTC by fschade

## Description
Sending multiple user ids in one sse event is now possible which reduces the number of sent events.

## Related Issue
* https://github.com/cs3org/reva/pull/4501

## Motivation and Context
Reduce events

2024-02-06 13:55 UTC, kobergj approved these changes

2024-02-06 13:56 UTC, kobergj requested changes
please vendor

2024-02-06 13:57 UTC, kobergj approved these changes

2024-02-07 09:46 UTC, rhafer approved these changes

2024-02-07 10:12 UTC, merged