[tests-only][full-ci] add tests to list space files shared with group when auto sync is dis…
owncloud/ocis pull request #8414
Opened 2024-02-09 04:04 UTC by nabim777

## Description

In this PR following scenarios are added related to sharingNG:
- Scenario: group member lists the file shared with them when auto-sync is disabled
- Scenario: group member lists the space folder shared with them when auto-sync is disabled

## Related Issue

- Part of https://github.com/owncloud/ocis/issues/8318

## Motivation and Context

## How Has This Been Tested?

- locally
- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [X] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2024-02-12 03:46 UTC, S-Panta commented
LGTM

2024-02-13 05:43 UTC, saw-jan commented on tests/acceptance/features/apiSharingNg/sharedWithMe.feature
> +  Scenario: group member lists the file shared with them when auto-sync is disabled
This scenario is for project space so would be better to indicate that in scenario title
```suggestion
  Scenario: group member lists the file shared with them when auto-sync is disabled
```

2024-02-13 05:44 UTC, saw-jan requested changes

2024-02-13 05:44 UTC, saw-jan commented on tests/acceptance/features/apiSharingNg/sharedWithMe.feature
> +
tests with `auto-sync` can be moved it it's on feature file. the file has already become too long

2024-02-14 05:40 UTC, amrita-shrestha commented on tests/acceptance/features/apiSharingNg/sharedWithMe.feature
> +    And user "Brian" has disabled the auto-sync share
if brain set auto-sync disable in all scenario then we can shift this step to background

2024-02-15 10:59 UTC, SagarGi commented on tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
> +    And user "Carol" has been created with default attributes and without skeleton files
is carol even needed for this scenario?

2024-02-15 10:59 UTC, SagarGi commented on tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
> +      | Carol    | grp1      |
```suggestion
```

2024-02-15 11:52 UTC, nabim777 commented on tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
> +    And user "Carol" has been created with default attributes and without skeleton files
Yes its not needed

2024-02-15 11:56 UTC, saw-jan approved these changes
LGTM :+1:

2024-02-16 03:35 UTC, SagarGi approved these changes
LGTM :+1:

2024-02-16 03:36 UTC, merged