[full-ci] [tests-only] Added tests to list sharedWithMe for file with same name shared by multiple users
owncloud/ocis pull request #8448
Opened 2024-02-14 09:45 UTC by grgprarup

## Description
Added scenario:
-  Scenario: user lists the file with same name shared by two users with him/her
-   Scenario: user lists the folder with same name shared by two users with him/her

## Related Issue

- Part of https://github.com/owncloud/ocis/issues/7826

## How Has This Been Tested?

- Locally
- :robot:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2024-02-15 04:56 UTC, amrita-shrestha approved these changes
lgtm

2024-02-15 10:35 UTC, SagarGi reviewed
LGTM :+1:

2024-02-15 11:09 UTC, nabim777 commented on tests/acceptance/features/apiSharingNg/sharedWithMe.feature
> +                          "required": ["displayName", "id"],
```suggestion
                          "required": ["displayName", "id"],
```
if id not needed to check then can be removed from required

2024-02-15 11:22 UTC, nabim777 commented on tests/acceptance/features/apiSharingNg/sharedWithMe.feature
> +                    "id",
```suggestion
```
if not needed to check then we can remove them

2024-02-15 11:33 UTC, nabim777 approved these changes

2024-02-15 11:46 UTC, saw-jan commented on tests/acceptance/features/apiSharingNg/sharedWithMe.feature
> +              "oneOf": [
```suggestion
            "minItems": 2,
            "maxItems": 2,
            "items": {
              "oneOf": [
```

2024-02-15 11:46 UTC, saw-jan commented on tests/acceptance/features/apiSharingNg/sharedWithMe.feature
> +            "items": {
```suggestion
            "type": "array",
            "minItems": 2,
            "maxItems": 2,
            "items": {
```

2024-02-15 11:47 UTC, saw-jan requested changes
let's use `minItems` and `maxItems` to make more stricter checks

2024-02-20 07:15 UTC, saw-jan approved these changes
looking good :sparkles:

2024-02-20 08:15 UTC, merged