[full-ci][tests-only]add tests coverage for removing expiration date from share link
owncloud/ocis pull request #8490
Opened 2024-02-20 06:31 UTC by amrita-shrestha

## Description
This PR adds tests for removing expiration date from share link

## Related Issue

- Fixes <https://github.com/owncloud/ocis/issues/8428>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2024-02-20 07:25 UTC, saw-jan approved these changes
LGTM :+1:

2024-02-20 07:26 UTC, saw-jan requested changes

2024-02-20 07:26 UTC, saw-jan commented on tests/acceptance/features/apiSharingNg/updateShareInvitations.feature
> +  Scenario: user remove expiration date of a share
```suggestion
  Scenario: user removes expiration date of a share
```

2024-02-21 04:03 UTC, amrita-shrestha commented on tests/acceptance/features/apiSharingNg/linkShare.feature
> +
issue has been added

2024-02-21 04:04 UTC, grgprarup commented on tests/acceptance/features/bootstrap/SharingNgContext.php
> +			$body["expirationDateTime"] = empty($bodyRows["expirationDateTime"]) ? null : $bodyRows["expirationDateTime"];
```suggestion
			$body['expirationDateTime'] = empty($bodyRows['expirationDateTime']) ? null : $bodyRows['expirationDateTime'];
```
Let's make a uniform.

2024-02-21 04:05 UTC, grgprarup approved these changes
LGTM :+1:

2024-02-21 04:23 UTC, SagarGi reviewed
LGTM :+1:

2024-02-21 06:31 UTC, saw-jan commented on tests/acceptance/features/apiSharingNg/linkShare.feature
> +
let's add the issue tags

2024-02-21 06:34 UTC, saw-jan commented on tests/acceptance/features/apiSharingNg/updateShareInvitations.feature
> +  Scenario: user removes expiration date of a share
issue tags will be helpful to check the coverage and know the related issues with the scenario

2024-02-21 08:19 UTC, saw-jan approved these changes

2024-02-21 09:09 UTC, merged