Create onlyoffice extension
owncloud/ocis pull request #857
Opened 2020-11-15 20:06 UTC by LukasHirt

2020-11-18 12:15 UTC, LukasHirt commented
Just realising now. I've actually added the extension as default into the config.json in ocis-phoenix which doesn't make sense because it won't work yet in pure ocis setup. Need to think about how do we want to deliver this in bridge setup.

2020-11-25 20:28 UTC, kulmann requested changes
I discovered some files that are not needed, some files that need to be one folder level higher, some occurrences of `ocis-onlyoffice` and some code that can be deleted.

Also, please contact @C0rby on how to implement the version command here and how to add it to the boilr template, so that we have it in every new service.

Good to see this extension! Really nice progress.

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/.drone.star
> +def main(ctx):
This file is not needed. The extension has to be added to the top level `.drone.star` instead.

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/.github/config.yml
> +# Configuration for update-docs - https://github.com/behaviorbot/update-docs
file is not needed

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/.editorconfig
> +# http://editorconfig.org
file is not needed

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/.github/settings.yml
> +---
file is not needed.

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/.gitignore
> +coverage.out
file is not needed. Have a look at the top level `.gitignore` if something needs to be added.

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/LICENSE
> +
we have the license file in all other extension folders as well, but IMO it should only be needed on the top level of the repository.

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/Makefile
> +# $(GOPATH)/bin/protoc-gen-go:
Remove the protoc and protobuf parts. Not needed to have it commented. We have enough other references to copy it over later.

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/README.md
> +# ownCloud Infinite Scale: ONLYOFFICE
file is not needed

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/changelog/CHANGELOG.tmpl
> +{{ $allVersions := . }}
file is not needed

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/changelog/README.md
> +# Changelog
file is not needed

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/changelog/TEMPLATE
> +Bugfix: Fix behavior for foobar (in present tense)
file is not needed

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/cmd/ocis-onlyoffice/main.go
> +package main
rename folder `onlyoffice/cmd/ocis-onlyoffice` to `onlyoffice/cmd/onlyoffice`

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/docs/_index.md
> +---
docs should live in the top level `docs` folder

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/docs/building.md
> +---
docs should live in the top level docs folder

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/docs/getting-started.md
> +---
docs should live in the top level docs folder

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/docs/building.md
> +Finally you should have the binary within the `bin/` folder now, give it a try with `./bin/ocis-onlyoffice -h` to see all available options.
`./bin/onlyoffice` instead of `./bin/ocis-onlyoffice`

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/docs/license.md
> +---
docs should live in the top level docs folder

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/package.json
> +  "name": "ocis-onlyoffice",
rename to `onlyoffice`

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/pkg/command/root.go
> +		Usage:    "Onlyoffice ocis extension",
Change to `OnlyOffice ocis extension` (branding)

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/pkg/command/root.go
> +		Name:     "ocis-onlyoffice",
Change to `onlyoffice`

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/pkg/service/v0/service.go
> +func (g Onlyoffice) Dummy(w http.ResponseWriter, r *http.Request) {
Not needed

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/pkg/service/v0/tracing.go
> +func (t tracing) Dummy(w http.ResponseWriter, r *http.Request) {
Not needed

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/ui/dev/public/index.html
> +    <title>Extension Demo</title>
Replace `Extension Demo` with `OnlyOffice` in this entire file, if the file is needed.

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/pkg/service/v0/instrument.go
> +func (i instrument) Dummy(w http.ResponseWriter, r *http.Request) {
not needed

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/pkg/service/v0/logging.go
> +func (l logging) Dummy(w http.ResponseWriter, r *http.Request) {
Not needed

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/pkg/service/v0/service.go
> +	Dummy(http.ResponseWriter, *http.Request)
Not needed

2020-11-25 20:28 UTC, kulmann commented on onlyoffice/pkg/service/v0/service.go
> +	m.Route(options.Config.HTTP.Root, func(r chi.Router) {
Not needed

2020-11-26 10:26 UTC, LukasHirt commented
@kulmann I've addressed all your comments. Regarding the versions command, I would like to tackle that in separate PR to finally get this one merged.

2020-11-26 11:25 UTC, kulmann approved these changes
Fix the staticcheck, then it's good to go 🚀

2020-12-01 10:50 UTC, merged