[tests-only][full-ci] add test for downloading resouces by user when auto sync is enabled
owncloud/ocis pull request #8697
Opened 2024-03-20 06:42 UTC by nabim777

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2024-03-20 06:56 UTC, grgprarup commented on tests/acceptance/features/apiSharingNg/sharedWithMe.feature
> +
Why are these scenarios in `sharedWithMe.feature`?

2024-03-21 06:11 UTC, saw-jan requested changes

2024-03-21 06:11 UTC, saw-jan commented on services/userlog/pkg/service/l10n/locale/ru/LC_MESSAGES/userlog.po
> +"POT-Creation-Date: 2024-03-20 03:43+0000\n"
Please, revert the changes

2024-03-26 03:42 UTC, S-Panta commented on tests/acceptance/features/apiArchiver/downloadById.feature
> +  Scenario Outline: user download the folder shared with them using sharingNg API
```suggestion
  Scenario Outline: download the folder shared with them
```
it sounds like the user is downloading the file using sharingNG API. Also, isn't this scenario already in the previous step? 
IMO, the given step in the above step should be refactored to sharingNG API. Therefore this scenario might be redundant.

2024-03-26 03:42 UTC, S-Panta commented on tests/acceptance/features/apiArchiver/downloadById.feature
> +  Scenario: user download the file shared with them using sharingNG API
```suggestion
  Scenario: user download the file shared with them
```

2024-03-26 03:44 UTC, S-Panta commented
Also, `auto-sync enabled` is the default condition for ocis . It generally mean downloading the file/folder shared to receiver

2024-03-26 10:12 UTC, nabim777 commented
The scenario will be covered in this line while doing the issue 8717.
- https://github.com/owncloud/ocis/blob/8f0b536ef75c552703d84e5e541d99727e6a5c31/tests/acceptance/features/apiSpacesDavOperation/getFileByFileId.feature#L11
- https://github.com/owncloud/ocis/blob/8f0b536ef75c552703d84e5e541d99727e6a5c31/tests/acceptance/features/apiArchiver/downloadById.feature#L75

So, this PR is closed since it will be raised as a duplicate scenario.

2024-03-26 10:12 UTC, closed without merging