fix: typos, naming clashes, error messages and deprecations
owncloud/ocis pull request #8770
Opened 2024-04-03 12:56 UTC by DeepDiver1975

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2024-04-03 13:16 UTC, rhafer requested changes

2024-04-03 13:16 UTC, rhafer commented on ocis-pkg/log/log.go
> +// Configure initializes a service-specific logger instance.
This is wrong the method is called `LoggerFromConfig`, so the comment should start with that.

2024-04-03 13:22 UTC, DeepDiver1975 commented on services/proxy/pkg/config/config.go
> +// PoliciesMiddleware configures the proxy policies' middleware.
it is the middleware of the proxy policies - the policies' middleware .... :shrug:

2024-04-03 13:27 UTC, kobergj commented on services/proxy/pkg/config/config.go
> +// PoliciesMiddleware configures the proxy policies' middleware.
Yes but what does the `'` mean?

2024-04-03 13:28 UTC, kobergj commented on services/proxy/pkg/config/config.go
> +// PoliciesMiddleware configures the proxy policies' middleware.
Ah now I get it. But that is not true.. It is the `policies middleware` of the proxy service

2024-04-03 13:33 UTC, DeepDiver1975 commented on services/proxy/pkg/config/config.go
> +// PoliciesMiddleware configures the proxy policies' middleware.
```go
// PoliciesMiddleware configures the proxy's policies middleware.
```

2024-04-03 13:40 UTC, kobergj approved these changes

2024-04-03 21:42 UTC, DeepDiver1975 commented on ocis-pkg/log/log.go
> +		l = l.Output(f)
Quite common in the go code I have seen.....
But happy to apply a different naming standard if there is one.

Main issue here is that var names should not collide with imports.

2024-04-03 21:42 UTC, DeepDiver1975 commented on ocis-pkg/log/log.go
> +		l = l.Output(f)
But I should review this line anyhow...

2024-04-04 07:14 UTC, kobergj commented on ocis-pkg/log/log.go
> +		l = l.Output(f)
Makes sense here imho. The function is called `NewLogger` an `l` is the actual logger.

2024-04-04 07:17 UTC, micbar commented on ocis-pkg/log/log.go
> +		l = l.Output(f)
We agreed as a team that we do not want to have single chat var names. We should use speaking variable names. Exceptions are possible when a variable is only used in a for loop or so, when the readability of the code allows it.

2024-04-04 07:25 UTC, DeepDiver1975 commented on ocis-pkg/log/log.go
> +		l = l.Output(f)
This then?
```
zeroLogger = zeroLogger.Output(f)

2024-04-04 07:29 UTC, kobergj commented on ocis-pkg/log/log.go
> +		l = l.Output(f)
> when the readability of the code allows it.

Looks to me like this is the case here :wink:

2024-04-04 08:04 UTC, DeepDiver1975 commented on ocis-pkg/log/log.go
> +		l = l.Output(f)
I see no reason to diverge from go's own proposals. In the past we had so many issues in not following commonly accepted rules (e.g. in PHP where we did not follow PSR code style - contributions have been difficult for external developers).

I would just follow https://go.dev/wiki/CodeReviewComments#variable-names

Furthermore there are so many code blocks where variable names are nuts .... :shrug:

2024-04-04 08:29 UTC, micbar commented on ocis-pkg/log/log.go
> +		l = l.Output(f)
Yes, we have some bad namings where we have `resp1` or `resp2` or something like `n` for node all over a whole page.

@dragotin Has a very strong opinion on variable names. We should always choose readability over trying to make the name even shorter.

For example pointer receivers in go are always single letters, this is agreed best practise.

We are linking our coding guidelines in the Readme 😀 

https://github.com/owncloud/ocis/blob/master/CONTRIBUTING.md#styleguides

Specially this one https://dave.cheney.net/practical-go/presentations/gophercon-singapore-2019.html#_a_variables_name_should_describe_its_contents

2024-04-04 08:50 UTC, rhafer approved these changes
In general I am not a huge fan of these "let's fix everything in a single commit" PRs. They tend to make life harder when back-/forward porting stuff.

For the future I think it would be better to create separate commits to address specific problems. (Even it that would be a bit more work)

2024-04-04 09:08 UTC, DeepDiver1975 commented on ocis-pkg/log/log.go
> +		l = l.Output(f)
> Specially this one https://dave.cheney.net/practical-go/presentations/gophercon-singapore-2019.html#_a_variables_name_should_describe_its_contents

following this `l` is just fine in the discussed code location
```


Naming the *Config parameter config is redundant. We know its a *Config, it says so right there.

In this case consider conf or maybe c will do if the lifetime of the variable is short enough.

2024-04-04 09:08 UTC, merged