changed php version
owncloud/ocis pull request #8889
Opened 2024-04-18 08:30 UTC by S-Panta

2024-04-18 09:26 UTC, phil-davis commented
It worked! Here is an example pipeline:
https://drone.owncloud.com/owncloud/ocis/33863/40/5
```
8.2: Pulling from owncloudci/php
Digest: sha256:002bb6d4f3c444957db7530323dd8cdf6f1da1a8a7bc6ca25a05078555e45623
Status: Downloaded newer image for owncloudci/php:8.2
+ make -C /drone/src test-acceptance-from-core-api
make: Entering directory '/drone/src'
...
87 scenarios (81 passed, 6 failed)
866 steps (844 passed, 6 failed, 16 skipped)
3m58.22s (19.19Mb)
Checking expected failures for suite coreApiSharePublicLink2
runsh: Total 263 scenarios (233 passed, 30 failed)
runsh: Exit code after checking expected failures: 0
runsh: There were no unexpected failures.
runsh: There were no unexpected success.
make: Leaving directory '/drone/src'
```

2024-04-18 09:26 UTC, phil-davis approved these changes

2024-04-18 09:27 UTC, phil-davis commented
@S-Panta if you don't know of anything else that we should touch, then click "Ready for review" and merge it.

I suppose that we should do the same in the current stable branch.

2024-04-18 09:34 UTC, S-Panta commented
I will change php version in composer.json files and then make this PR ready

2024-04-18 10:27 UTC, saw-jan requested changes

2024-04-18 10:27 UTC, saw-jan commented on composer.json
> +      "php": "8.2"
we have `composer.json` in other places as well

2024-04-19 03:57 UTC, saw-jan approved these changes

2024-04-19 04:00 UTC, phil-davis approved these changes

2024-04-19 04:19 UTC, phil-davis commented
https://drone.owncloud.com/owncloud/ocis/33919/39/5
```
runsh: Total unexpected failed scenarios throughout the test run:
coreApiShareManagementBasicToShares/createShareToSharesFolder.feature:236
```

I restarted CI.

2024-04-19 06:46 UTC, merged