enhancement: add get share endpoint
owncloud/ocis pull request #8939
Opened 2024-04-23 16:01 UTC by fschade

## Description
PENDING, description will be added

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2024-04-23 16:18 UTC, DeepDiver1975 requested changes

2024-04-24 07:38 UTC, fschade commented on services/graph/pkg/service/v0/api_drives_drive_item.go
> +	ErrNoShare = errors.New("no shares found")
eagle eye, thanks, i did that as a prep for a pairing today, i fix it, THX 🤗

2024-05-14 08:20 UTC, rhafer approved these changes

2024-05-14 08:22 UTC, kobergj approved these changes

2024-05-14 08:30 UTC, merged