[tests-only][full-ci]Added test for hide shared resources (personal and project space) in shares
owncloud/ocis pull request #8999
Opened 2024-04-29 09:22 UTC by SagarGi

2024-04-29 11:44 UTC, saw-jan commented on tests/TestHelpers/GraphHelper.php
> +	public static function hideSharedResource(
```suggestion
	public static function hideShare(
```

2024-04-29 11:49 UTC, saw-jan requested changes

2024-04-29 11:49 UTC, saw-jan commented on tests/acceptance/features/bootstrap/SharingNgContext.php
> +	): ResponseInterface {
```suggestion
	public function hideSharedResource(string $sharee): ResponseInterface {
```

2024-04-29 11:49 UTC, saw-jan commented on tests/acceptance/features/apiSharingNg/sharedWithMe.feature
> +  Scenario Outline: user hide the shared resource from a personal space
```suggestion
  Scenario Outline: sharee hides the shared resource (Personal space)
```

2024-04-29 11:49 UTC, saw-jan commented on tests/acceptance/features/apiSharingNg/sharedWithMe.feature
> +    When user "Brian" hides the resource "<resource>" shared with me using the Graph API
```suggestion
    When user "Brian" hides the shared resource "<resource>" using the Graph API
```

2024-04-29 11:49 UTC, saw-jan commented on tests/acceptance/features/apiSharingNg/sharedWithMe.feature
> +          "enum": [true]
```suggestion
          "const": true
```

2024-04-29 11:49 UTC, saw-jan commented on tests/acceptance/features/apiSharingNg/sharedWithMe.feature
> +  Scenario Outline: user hide the shared resource from a project space
```suggestion
  Scenario Outline: sharee hides the shared resource (Project space)
```

2024-04-29 11:49 UTC, saw-jan commented on tests/acceptance/features/apiSharingNg/sharedWithMe.feature
> +  Scenario Outline: user hide and list the shared resource from a personal space
```suggestion
  Scenario Outline: sharee lists the shares after hiding (Personal space)
```

2024-04-29 11:49 UTC, saw-jan commented on tests/acceptance/features/apiSharingNg/sharedWithMe.feature
> +    And user "Brian" hidden the resource "<resource>" shared with him
```suggestion
    And user "Brian" has hidden the share "<resource>"
```

2024-04-30 04:22 UTC, saw-jan commented on tests/acceptance/features/apiSharingNg/sharedWithMe.feature
> +              "const": "<resource>"
```suggestion
              "const": "<resource>"
```

2024-04-30 04:22 UTC, saw-jan commented on tests/acceptance/features/apiSharingNg/sharedWithMe.feature
> +              "const": "<resource>"
```suggestion
              "const": "<resource>"
```

2024-04-30 11:04 UTC, PrajwolAmatya commented on tests/acceptance/features/apiSharingNg/sharedWithMe.feature
> +    Given the administrator has assigned the role "Space Admin" to user "Alice" using the Graph API
```suggestion
    Given using spaces DAV path
    And the administrator has assigned the role "Space Admin" to user "Alice" using the Graph API
```

2024-04-30 11:04 UTC, PrajwolAmatya commented on tests/acceptance/features/apiSharingNg/sharedWithMe.feature
> +    Given the administrator has assigned the role "Space Admin" to user "Alice" using the Graph API
```suggestion
    Given using spaces DAV path
    And the administrator has assigned the role "Space Admin" to user "Alice" using the Graph API
```

2024-05-03 10:38 UTC, saw-jan commented on tests/acceptance/features/bootstrap/SharingNgContext.php
> +		$shareItemId = $this->featureContext->shareNgGetLastCreatedUserGroupShareID();
```suggestion
	 * @param string $sharee
	 * @param string $shareID
	 *
	 * @return ResponseInterface
	 * @throws GuzzleException
	 * @throws JsonException
	 */
	public function hideSharedResource(string $sharee, string $shareID): ResponseInterface {
```

2024-05-03 10:38 UTC, saw-jan commented on tests/acceptance/features/bootstrap/SharingNgContext.php
> +		$response = $this->hideSharedResource($user);
```suggestion
                $shareItemId = $this->featureContext->shareNgGetLastCreatedUserGroupShareID();
		$response = $this->hideSharedResource($user, $shareItemId);
```

2024-05-03 10:38 UTC, saw-jan commented on tests/acceptance/features/bootstrap/SharingNgContext.php
> +		$response = $this->hideSharedResource($user);
```suggestion
                $shareItemId = $this->featureContext->shareNgGetLastCreatedUserGroupShareID();
		$response = $this->hideSharedResource($user, $shareItemId);
```

2024-05-06 03:53 UTC, saw-jan approved these changes

2024-05-06 05:32 UTC, merged