feat: add maximum image file size to be processed by the thumbnailer
owncloud/ocis pull request #9069
Opened 2024-05-03 14:24 UTC by DeepDiver1975

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2024-05-03 15:48 UTC, mmattel commented on services/thumbnails/pkg/config/config.go
> +	MaxInputImageFileSize uint64            `yaml:"max_input_image_file_size" env:"THUMBNAILS_MAX_INPUT_IMAGE_FILE_SIZE" desc:"The maximum file size of an input image which is being processed." introduc
We need to add the unit of the value in the description. int and uint64 is just the computational range.

**Example:**
`The maximum file size of an input image which is being processed.` -->
`The maximum file size in bytes of an input image that will be processed.`

2024-05-07 08:41 UTC, mmattel approved these changes
LGTM from a docs pov 👍

2024-05-08 11:09 UTC, rhafer requested changes
I think this need a Changelog. Looks good otherwise.

2024-05-08 11:59 UTC, DeepDiver1975 commented
> I think this need a Changelog. Looks good otherwise.

done - added to other changelog item which falls into the same topic

2024-05-08 13:34 UTC, DeepDiver1975 commented on services/thumbnails/pkg/config/config.go
> +	MaxInputImageFileSize string            `yaml:"max_input_image_file_size" env:"THUMBNAILS_MAX_INPUT_IMAGE_FILE_SIZE" desc:"The maximum file size of an input image which is being processed. Usable co
> Do we have some experience how the file size maps to memory consumption when generating a thumbnail?

not really - and this is rather complicated...

From my understanding the image dimensions are more critical to this. A rather small file can hold an image with gigantic dimensions which can blow up the thumbnailer pretty easy ....



> Just as a "unrelated" question: are there any plans to limit the concurrency for generating thumbnails, too?

I did not look into this yet. Feel free to add this to https://github.com/owncloud/enterprise/issues/6388
THX

2024-05-08 13:44 UTC, rhafer approved these changes

2024-05-08 14:28 UTC, merged