[tests-only][full-ci]changing given from ocs to graph in favoritesSharingToShares feature
owncloud/ocis pull request #9118
Opened 2024-05-09 08:46 UTC by S-Panta

## Related Issue

- Part of https://github.com/owncloud/ocis/issues/8717

2024-05-10 04:55 UTC, SagarGi requested changes

2024-05-10 04:55 UTC, SagarGi commented on tests/acceptance/features/coreApiFavorites/favoritesSharingToShares.feature
> +      | permissionsRole | File Editor           |
```suggestion
    And user "Alice" has sent the following resource share invitation:
      | resource        | PARENT/parent.txt |
      | space           | Personal          |
      | sharee          | Brian             |
      | shareType       | user              |
      | permissionsRole | File Editor       |
```

2024-05-10 04:55 UTC, SagarGi commented on tests/acceptance/features/coreApiFavorites/favoritesSharingToShares.feature
> +#    And user "Alice" has shared file "/PARENT/parent.txt" with user "Brian"
```suggestion
```

2024-05-13 05:49 UTC, saw-jan approved these changes

2024-05-13 05:54 UTC, nabim777 approved these changes

2024-05-14 04:48 UTC, SagarGi approved these changes

2024-05-14 04:48 UTC, merged