fix: token refresh in wopi deployment example
owncloud/ocis pull request #9167
Opened 2024-05-14 15:17 UTC by DeepDiver1975

## Description
When refreshing the oidc client loads ocis in an iframe - which was disallowed until this fix.

## Related Issue
- Fixes #9163 

## How Has This Been Tested?
- cd deployment/example/ocis_wopi
- docker compose up
- xdg-open https://ocis.owncloud.test/
- login
- open developer console in browser
- wait 5m
- see token expiring and being refreshed
- observe to stay logged in

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2024-05-14 15:24 UTC, rhafer requested changes
AFAIK the problem is also present in a default deployment (i.e. without wopi and any other external stuff). So I guess we need to update the default config https://github.com/owncloud/ocis/blob/master/services/proxy/pkg/config/csp.yaml as well?

2024-05-14 15:29 UTC, DeepDiver1975 commented
> AFAIK the problem is also present in a default deployment

Testing this ...

2024-05-14 15:38 UTC, DeepDiver1975 commented
Single binary has the same issue....

2024-05-14 15:42 UTC, micbar approved these changes
🎉

2024-05-14 15:43 UTC, rhafer approved these changes

2024-05-14 18:14 UTC, AlexAndBear approved these changes

2024-05-15 08:14 UTC, DeepDiver1975 commented
rebased ..... let's see if drone likes this now ..... :shrug:

2024-05-15 13:14 UTC, kulmann approved these changes

2024-05-15 14:06 UTC, micbar commented
@DeepDiver1975 The tests are failing because they expect different CSP headers.

2024-05-16 16:20 UTC, merged