Update ocis-web to 0.2.6
owncloud/ocis pull request #935
Opened 2020-11-23 21:14 UTC by LukasHirt

2020-11-23 21:26 UTC, kulmann requested changes
changelog is a bit off. maybe copy an already existing phoenix update changelog and just update the version and links

2020-11-23 21:26 UTC, kulmann commented on changelog/unreleased/add-eos copy.md
> +Enhancement: Update ocis-web to 0.2.6
rename this file

2020-11-23 21:26 UTC, kulmann commented on changelog/unreleased/add-eos copy.md
> +Enhancement: Update ocis-web to 0.2.6
version is not 0.2.6, but 0.26.0

2020-11-23 21:26 UTC, kulmann commented on changelog/unreleased/add-eos copy.md
> +We've updated ocis-web to the version 0.2.6.
adapt version here as well

2020-11-23 21:26 UTC, kulmann commented on changelog/unreleased/add-eos copy.md
> +Tags: ocis-phoenix
tag for this is supposed to be `web`

2020-11-24 08:37 UTC, LukasHirt commented
Dang it. Fixed the changelog.

2020-11-24 08:44 UTC, kulmann approved these changes

2020-11-24 09:54 UTC, phil-davis commented
There are lots of UI test fails. The latest `.drone.star` in the Phoenix repo has some different environment variables...
e.g. https://github.com/owncloud/phoenix/commit/eb1361541cffb51278c01ccd0ec9c3be2ccdc03b sorted out a lot of environment variables for the OCIS server that runs during the Phoenix CI. But I see that some of the new/changed things there are actually not mentioned in `.drone.star` of OCIS. Maybe there is some env var magic that is needed here to get things working?

2020-11-24 10:13 UTC, kulmann commented
> There are lots of UI test fails. The latest `.drone.star` in the Phoenix repo has some different environment variables...
> e.g. [owncloud/phoenix@eb13615](https://github.com/owncloud/phoenix/commit/eb1361541cffb51278c01ccd0ec9c3be2ccdc03b) sorted out a lot of environment variables for the OCIS server that runs during the Phoenix CI. But I see that some of the new/changed things there are actually not mentioned in `.drone.star` of OCIS. Maybe there is some env var magic that is needed here to get things working?

It looks like the assets were not generated correctly... I just pushed a commit with re-generated assets. Let's see what CI thinks about that.

2020-11-24 10:39 UTC, kulmann commented
Web UI tests succeeded now. 👍  waiting for the remaining api tests..

2020-11-24 11:25 UTC, phil-davis commented
It's all green. Great stuff, merging.

2020-11-24 11:25 UTC, merged