Create new 'ocis_wopi_community' deployment example
owncloud/ocis pull request #9394
Opened 2024-06-17 11:51 UTC by mmattel

Fixes: #9388 (New community ready deployment example using WOPI necessary)

This PR adds a new deployment example that focuses on community use. It derives from the `ocis_wopi` example and contains the following changes:

* Removal of the following containers and their configuration:
   * Inbucket
   * Companion
   * Onlyoffice
* Removal of:
   * Supplemental monitoring
* Updating the following containers:
   * traefik: 2.9.1 --> 3.0.1
   * collabora: 23.05.5.2.1 --> 23.05.10.1.1
   Note that the latest version 24.x is not working as it cant update a file but you need to create a copy.
   * wopiserver: 10.4.0 --> 10.5.0
* Adding the possibility to configure ocis notifications (email)
* The `.env` file has been updated accordingly and readability improved
* The `compose` file has been updated accordingly and readability improved (only minor changes)
   * Note that "dead" envvars from the original example like `REVA_GATEWAY` have been removed as they were no longer available and therefore senseless.

Comments:
* This example is now much smaller compared to `ocis_wopi` 6.1GB --> 2.7GB.
* Only a few changes necessary in the prepared admin docs currently visible on staging (just working on it).
* This example is **only compatible** with ocis v5.0.5 but not with latest. Redirection to login hangs.

Tests:
- [x] Locally tested successfully using the `*.owncloud.test` domain (self signed certificates)
- [ ] A test using an own domain with Letsencrypt is open

Imho, a double test check should be made @ScharfViktor 

Backport to `stable-5.0` necessary.

@tbsbdr @micbar

2024-06-17 14:05 UTC, ScharfViktor commented
I tested it and it works to me. 

> Adding the possibility to configure ocis notifications (email)

How? If you deleted `Inbucket`?

2024-06-17 14:16 UTC, micbar commented
I want to streamline the wopi example.

2024-06-17 14:18 UTC, micbar commented
@mmattel Please coordinate *before* starting such a large refactoring.

I do not want the wopi and community example to diverge.

2024-06-17 14:19 UTC, micbar requested changes
Please let us discuss if we need a new one or can pimp the existing one.

2024-06-17 15:30 UTC, mmattel commented
> How? If you deleted `Inbucket`?

This gets usually configured when using Letsencrypt with an own domain. Upcoming admin docs have a note in it and I took your note and added this to the main comment on top.

2024-06-18 06:48 UTC, dragonchaser commented
@micbar I like the idea of having a shrunken down wopi example without onlyoffice, inbucket and companion. I suggest just adding the `docker-compose.yaml` from this PR to the `ocis-wopi` example in the deployments directory as `docker-compose-collabora-only.yaml` and let the users pick the suiting one using `docker-compose -f`. This would give us this example and does not force us to maintain two full-blown examples.

2024-06-18 09:14 UTC, micbar commented
Please adapt the existing ocis_wopi example to make that possible. We need the modularity.

Please also adapt the .env files in the other examples.

2024-06-19 10:19 UTC, mmattel commented
Closing, superseded by #9412

2024-06-19 10:19 UTC, closed without merging