[full-ci][tests-only] Remove @skipOnRevaMaster tag from ocis
owncloud/ocis pull request #9446
Opened 2024-06-24 08:19 UTC by amrita-shrestha

## Description
This PR remove @skipOnRevaMaster tag from tests code because ocis tests doesn't run on reva master branch

## Related Issue

- https://github.com/owncloud/ocis/issues/5337

## Motivation and Context

## How Has This Been Tested?

- CI

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2024-06-25 04:58 UTC, phil-davis commented on tests/package.json
Please write something in the PR about why this file is added.

2024-06-25 05:02 UTC, amrita-shrestha commented on tests/package.json
my PR should not add this by mistake it is added

2024-06-25 05:21 UTC, phil-davis approved these changes

2024-07-04 06:34 UTC, phil-davis requested changes

2024-07-04 06:34 UTC, phil-davis commented on tests/package.json
The file is still here.

2024-07-08 08:41 UTC, phil-davis commented on tests/package.json
The file is still here @amrita-shrestha

2024-07-08 09:45 UTC, phil-davis commented
https://drone.owncloud.com/owncloud/ocis/36804/50/5
```
       Failed step: When user "Alice" uploads file "filesForUpload/zerobyte.txt" to "textfile.txt" using the TUS protocol on the WebDAV API

        Server error: `POST https://ocis-server:9200/remote.php/dav/spaces/de166e33-ba92-4fad-8716-efaa6f657100$0e2f9596-456e-4cda-92d7-91f0231a8fc8/` resulted in a `500 Internal Server Error` response (GuzzleHttp\Exception\ServerException)
```
I restarted CI.
Is that a flaky test?

2024-07-08 10:13 UTC, phil-davis approved these changes

2024-07-08 10:14 UTC, merged