[tests-only][full-ci] added test for updating admin password via cli
owncloud/ocis pull request #9593
Opened 2024-07-12 07:43 UTC by S-Panta

## Description
Added cli test for updating administrator credentials

## Related Issue

- Part of https://github.com/owncloud/ocis/issues/9581

## How Has This Been Tested?

- test environment:
- locally and CI
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2024-07-16 05:46 UTC, saw-jan requested changes

2024-07-16 05:46 UTC, saw-jan commented on tests/acceptance/features/bootstrap/CliContext.php
> +	 * @Given /^the administrator (stops|has stopped) the server$/
```suggestion
	 * @Given /^the administrator (?:stops|has stopped) the server$/
```

2024-07-16 05:46 UTC, saw-jan commented on tests/acceptance/features/bootstrap/CliContext.php
> +	 * @Given /^the administrator (starts|has started) the server$/
```suggestion
	 * @Given /^the administrator (?:starts|has started) the server$/
```

2024-07-16 05:46 UTC, saw-jan commented on tests/acceptance/features/bootstrap/GraphContext.php
> +		// Sometimes listing shares might not return the `update`d shares list
```suggestion
		// Sometimes listing shares might not return the updated shares list
```

2024-07-16 05:46 UTC, saw-jan commented on tests/acceptance/features/cliCommands/resetUserPassword.feature
> +    And user "Alice" has changed it's own username to "superUser"
```suggestion
    And user "Alice" has changed the username to "superUser"
```

2024-07-16 05:46 UTC, saw-jan commented on tests/acceptance/features/bootstrap/GraphContext.php
> +		$this->featureContext->addUserToCreatedUsersList($userName, $this->featureContext->getUserPassword($byUser));
```suggestion
		$this->featureContext->theHTTPStatusCodeShouldBe(200, '', $response);
		$this->featureContext->addUserToCreatedUsersList($userName, $this->featureContext->getUserPassword($byUser));
		<also delete the previous one>
```

2024-07-17 06:49 UTC, saw-jan commented on tests/acceptance/features/bootstrap/GraphContext.php
> +		// Sometimes listing shares might not return the `updated` shares list
```suggestion
		// Sometimes listing shares might not return the updated shares list
```

2024-07-17 06:50 UTC, saw-jan commented on tests/acceptance/features/bootstrap/GraphContext.php
> +			__METHOD__ . " cannot create user '$user' using Graph API.\nResponse:" .
```suggestion
			__METHOD__ . " cannot create new user '$user' by user '$byUser'.\nResponse:" .
```

2024-07-17 06:50 UTC, saw-jan commented on tests/acceptance/features/bootstrap/GraphContext.php
> +		$this->featureContext->addUserToCreatedUsersList($user, '', null, null, null);
others should be default
```suggestion
		$this->featureContext->addUserToCreatedUsersList($user);
```

2024-07-17 06:51 UTC, saw-jan commented on tests/acceptance/features/bootstrap/GraphContext.php
> +		$this->featureContext->replaceActualUserNameFromCreatedUserList($byUser, $userName);
```suggestion
		$this->featureContext->updateUsernameInCreatedUserList($byUser, $userName);
```

2024-07-17 06:52 UTC, saw-jan commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function replaceActualUserNameFromCreatedUserList(string $oldUserName, string $newUserName) :void {
```suggestion
	public function updateUsernameInCreatedUserList(string $oldUserName, string $newUserName) :void {
```

2024-07-17 06:52 UTC, saw-jan commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 *
```suggestion
	/**
```

2024-07-18 03:49 UTC, saw-jan commented on tests/acceptance/features/bootstrap/GraphContext.php
> +		// Sometimes listing shares might not return the `updated` shares list
this should be reverted

2024-07-18 03:50 UTC, saw-jan commented on tests/acceptance/features/bootstrap/GraphContext.php
> +		);
null should be default ones
```suggestion
			''
		);
```

2024-07-18 04:05 UTC, saw-jan approved these changes
:+1:

2024-07-18 04:47 UTC, saw-jan requested changes
@S-Panta Could you squash the commits or reword to meaningful one?

2024-07-18 06:24 UTC, saw-jan approved these changes

2024-07-18 06:35 UTC, ScharfViktor approved these changes
LGTM

2024-07-18 07:11 UTC, merged