[tests-only][full-ci] search: reindex command for spaces
owncloud/ocis pull request #9630
Opened 2024-07-17 08:57 UTC by ishabaral

## Description
Adding test scenario for reindexing spaces via cli

## Related Issue
- Part of https://github.com/owncloud/ocis/issues/9529

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1: locally
- test case 2: CI
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2024-07-18 05:35 UTC, saw-jan reviewed
You could update to other methods where the return type is missing

2024-07-18 05:35 UTC, saw-jan commented on tests/acceptance/features/bootstrap/CliContext.php
> +	public function userReindexesAllSpacesUsingTheCli($user) {
```suggestion
	public function userReindexesAllSpacesUsingTheCli($user): void {
```

2024-07-18 05:35 UTC, saw-jan commented on tests/acceptance/features/bootstrap/CliContext.php
> +	public function theAdministratorReindexesASpaceWithSpaceidUsingTheCli(string $user, string $spaceName) {
```suggestion
	public function theAdministratorReindexesASpaceWithSpaceidUsingTheCli(string $user, string $spaceName): void {
```

2024-07-18 06:39 UTC, saw-jan requested changes

2024-07-18 06:39 UTC, saw-jan commented on tests/acceptance/features/bootstrap/CliContext.php
> +	 * @When /^user "([^"]*)" reindexes all spaces using the CLI$/
```suggestion
	 * @When /^the administrator reindexes all spaces using the CLI$/
```

2024-07-18 06:39 UTC, saw-jan commented on tests/acceptance/features/bootstrap/CliContext.php
> +	public function userReindexesAllSpacesUsingTheCli($user): void {
```suggestion
	 *
	 * @return void
	 */
	public function userReindexesAllSpacesUsingTheCli(): void {
```

2024-07-18 06:39 UTC, saw-jan commented on tests/acceptance/features/bootstrap/CliContext.php
> +	 * @When /^user "([^"]*)" reindexes a space with spaceName "([^"]*)" using the CLI$/
```suggestion
	 * @When /^the administrator reindexes a space "([^"]*)" using the CLI$/
```

2024-07-18 06:39 UTC, saw-jan commented on tests/acceptance/features/bootstrap/CliContext.php
> +	public function userReindexesASpaceWithSpacenameUsingTheCli(string $user, string $spaceName): void {
```suggestion
	 * @param string $spaceName
	 *
	 * @return void
	 */
	public function userReindexesASpaceWithSpacenameUsingTheCli(string $spaceName): void {
```

2024-07-18 06:39 UTC, saw-jan commented on tests/acceptance/features/bootstrap/CliContext.php
> +		$spaceId = $this->featureContext->spacesContext->getSpaceIdByName($user, $spaceName);
```suggestion
		$spaceId = $this->featureContext->spacesContext->getSpaceIdByName(<admin-user>, $spaceName);
```

2024-07-18 06:59 UTC, ScharfViktor commented on tests/acceptance/features/cliCommands/searchReIndex.feature
> +    Then the command should be successful
I would check that search works after reindex
maybe we can add step where we found `textfile.txt` file?

2024-07-18 11:15 UTC, saw-jan commented on tests/acceptance/features/bootstrap/CliContext.php
> +		$spaceId = $this->featureContext->spacesContext->getSpaceIdByName("admin", $spaceName);
```suggestion
		$spaceId = $this->featureContext->spacesContext->getSpaceIdByName($this->featureContext->getAdminUsername(), $spaceName);
```

2024-07-18 11:34 UTC, saw-jan commented on tests/acceptance/features/cliCommands/searchReIndex.feature
> +    Given user "Alice" has created the following tags for file "textfile.txt" of the space "new-space":
```suggestion
  Scenario: reindex a space
    Given using spaces DAV path
    And user "Alice" has created the following tags for file "textfile.txt" of the space "new-space":
```

2024-07-19 04:24 UTC, saw-jan commented on tests/acceptance/features/bootstrap/CliContext.php
> +		$spaceId = $this->featureContext->spacesContext->getSpaceIdByName($this->featureContext->getAdminUsername(), $spaceName);
`spacesContext` is available in this context
```suggestion
		$spaceId = $this->spacesContext->getSpaceIdByName($this->featureContext->getAdminUsername(), $spaceName);
```

2024-07-19 04:25 UTC, saw-jan commented on tests/acceptance/features/bootstrap/CliContext.php
> +	public function theAdministratorReindexesASpaceWithSpacenameUsingTheCli(string $spaceName): void {
```suggestion
	public function theAdministratorReindexesASpaceUsingTheCli(string $spaceName): void {
```

2024-07-19 05:46 UTC, saw-jan approved these changes
:+1:

2024-07-19 05:52 UTC, merged