reuse node id when registering services
owncloud/ocis pull request #9656
Opened 2024-07-19 13:22 UTC by butonic

@kobergj like this.

yes, the service delemiter is actually `-`. as it is, the registry is backwards compatible ... but ... I'd actually prefer a `_serviceDelimiter = "-"`. however that is also not collision free when two services were called e.g. `auth` and `auth-blarg`. then listing `auth` services would still also list all `auth-blarg` services.

2024-07-19 14:45 UTC, kobergj requested changes
Good idea using the nodeID. Do we know where it is created. I see clashes between different services:
```
&{Name:com.owncloud.sse.sse Version:6.1.0+56b6b43daa Metadata:map[] Endpoints:[] Nodes:[0xc002a1fbc0]}
        &{Metadata:map[broker:NoOp protocol:http registry:cache server:http] Id:com.owncloud.sse.sse-a2607824-3c57-4268-9ca7-0a98acf2f8cc Address:127.0.0.1:46219}
&{Name:com.owncloud.web.idp Version:6.1.0+56b6b43daa Metadata:map[] Endpoints:[] Nodes:[0xc002a1fd10]}
        &{Metadata:map[broker:NoOp protocol:http registry:cache server:http] Id:com.owncloud.web.idp-a2607824-3c57-4268-9ca7-0a98acf2f8cc Address:127.0.0.1:9130}
```
Note that sse and idp use the same uuid. This is not a problem when it is different services, but be could become one if it is the same service.

2024-07-19 14:45 UTC, kobergj commented on ocis-pkg/natsjsregistry/registry.go
> +	return n.listServices(store.ListPrefix(s))
This will fail. See line above!

2024-07-19 14:48 UTC, kobergj commented
>  however that is also not collision free when two services were called e.g. auth and auth-blarg. then listing auth services would still also list all auth-blarg services.

This is why I used `/`. Any other character would also do. We just need to make sure it isn't used in service names. `-` unfortunately is.

2024-07-23 08:41 UTC, kobergj approved these changes
Now I like :+1:

2024-07-23 09:02 UTC, kobergj approved these changes

2024-07-24 13:04 UTC, kobergj requested changes
Looks good. Just one question.

2024-07-24 13:04 UTC, kobergj commented on ocis/pkg/runtime/service/service.go
This file still contains a
```
	// halt listens for interrupt signals and blocks.
	halt := make(chan os.Signal, 1)
	signal.Notify(halt, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT, syscall.SIGHUP)
```

Do we still need this? Since we are now listening in `runtime/runtime.go` to the same signals.

2024-07-25 14:17 UTC, butonic commented
Ok, I am running load tests ... and it does not look good.
## v5.0.0-rc4 the originally deployed version
```
# k6 run ~/cdperf/packages/k6-tests/artifacts/koko-platform-000-mixed-ramping-k6.js

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: /root/cdperf/packages/k6-tests/artifacts/koko-platform-000-mixed-ramping-k6.js
     output: -

  scenarios: (100.00%) 8 scenarios, 75 max VUs, 6m30s max duration (incl. graceful stop):
           * add_remove_tag_100: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: add_remove_tag_100, gracefulStop: 30s)
           * create_remove_group_share_090: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: create_remove_group_share_090, gracefulStop: 30s)
           * create_space_080: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: create_space_080, gracefulStop: 30s)
           * create_upload_rename_delete_folder_and_file_040: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: create_upload_rename_delete_folder_and_file_040, gracefulStop: 30s)
           * download_050: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: download_050, gracefulStop: 30s)
           * navigate_file_tree_020: Up to 10 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: navigate_file_tree_020, gracefulStop: 30s)
           * sync_client_110: Up to 20 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: sync_client_110, gracefulStop: 30s)
           * user_group_search_070: Up to 20 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: user_group_search_070, gracefulStop: 30s)


     ✓ authn -> loginPageResponse - status
     ✓ authn -> authorizationResponse - status
     ✓ authn -> accessTokenResponse - status
     ✓ client -> search.searchForSharees - status
     ✓ client -> role.getMyDrives - status
     ✓ client -> resource.getResourceProperties - status
     ✓ client -> application.createDrive - status
     ✓ client -> resource.createResource - status
     ✓ client -> drive.deactivateDrive - status
     ✓ client -> drive.deleteDrive - status
     ✓ client -> share.createShare - status
     ✓ client -> share.deleteShare - status
     ✓ client -> resource.uploadResource - status
     ✓ client -> resource.deleteResource - status
     ✓ client -> tag.getTags - status -- (SKIPPED)
     ✓ client -> tag.createTag - status -- (SKIPPED)
     ✓ client -> resource.moveResource - status
     ✗ client -> tag.addTagToResource - status
      ↳  0% — ✓ 0 / ✗ 47
     ✗ client -> tag.removeTagToResource - status
      ↳  0% — ✓ 0 / ✗ 47
     ✓ client -> resource.downloadResource - status

     checks.........................: 97.87% ✓ 4338      ✗ 94  
     data_received..................: 1.7 GB 4.4 MB/s
     data_sent......................: 811 MB 2.1 MB/s
     http_req_blocked...............: avg=908.96µs min=181ns   med=290ns    max=49.54ms  p(90)=601ns    p(95)=1.21µs  
     http_req_connecting............: avg=313.23µs min=0s      med=0s       max=19.35ms  p(90)=0s       p(95)=0s      
     http_req_duration..............: avg=385.19ms min=2.93ms  med=317.22ms max=8.6s     p(90)=561.37ms p(95)=786.86ms
       { expected_response:true }...: avg=390.77ms min=2.93ms  med=320.28ms max=8.6s     p(90)=566.07ms p(95)=794.71ms
     http_req_failed................: 2.06%  ✓ 94        ✗ 4469
     http_req_receiving.............: avg=8.3ms    min=24.25µs med=97.4µs   max=3.48s    p(90)=214.67µs p(95)=50.4ms  
     http_req_sending...............: avg=1.64ms   min=28.25µs med=92.46µs  max=876.76ms p(90)=153.03µs p(95)=185.03µs
     http_req_tls_handshaking.......: avg=583.56µs min=0s      med=0s       max=32.89ms  p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=375.24ms min=2.78ms  med=314.76ms max=8.6s     p(90)=544.16ms p(95)=753.72ms
     http_reqs......................: 4563   11.699981/s
     iteration_duration.............: avg=6.91s    min=1.19s   med=1.36s    max=43.49s   p(90)=15.64s   p(95)=18.17s  
     iterations.....................: 3335   8.551268/s
     vus............................: 1      min=0       max=75
     vus_max........................: 75     min=75      max=75


running (6m30.0s), 00/75 VUs, 3335 complete and 3 interrupted iterations
add_remove_tag_100             ✓ [======================================] 0/5 VUs    6m0s
create_remove_group_share_090  ✓ [======================================] 0/5 VUs    6m0s
create_space_080               ✓ [======================================] 0/5 VUs    6m0s
create_upload_rename_delete... ✓ [======================================] 0/5 VUs    6m0s
download_050                   ✓ [======================================] 0/5 VUs    6m0s
navigate_file_tree_020         ✓ [======================================] 00/10 VUs  6m0s
sync_client_110                ✓ [======================================] 00/20 VUs  6m0s
user_group_search_070          ✓ [======================================] 00/20 VUs  6m0s
```

## 5.0.6
something seems broken
```
# k6 run ~/cdperf/packages/k6-tests/artifacts/koko-platform-000-mixed-ramping-k6.js

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: /root/cdperf/packages/k6-tests/artifacts/koko-platform-000-mixed-ramping-k6.js
     output: -

  scenarios: (100.00%) 8 scenarios, 75 max VUs, 6m30s max duration (incl. graceful stop):
           * add_remove_tag_100: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: add_remove_tag_100, gracefulStop: 30s)
           * create_remove_group_share_090: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: create_remove_group_share_090, gracefulStop: 30s)
           * create_space_080: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: create_space_080, gracefulStop: 30s)
           * create_upload_rename_delete_folder_and_file_040: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: create_upload_rename_delete_folder_and_file_040, gracefulStop: 30s)
           * download_050: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: download_050, gracefulStop: 30s)
           * navigate_file_tree_020: Up to 10 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: navigate_file_tree_020, gracefulStop: 30s)
           * sync_client_110: Up to 20 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: sync_client_110, gracefulStop: 30s)
           * user_group_search_070: Up to 20 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: user_group_search_070, gracefulStop: 30s)

WARN[0026] Request Failed                                error="stream error: stream ID 3; INTERNAL_ERROR; received from peer"
WARN[0260] Request Failed                                error="stream error: stream ID 29; INTERNAL_ERROR; received from peer"

     ✓ authn -> loginPageResponse - status
     ✓ authn -> authorizationResponse - status
     ✓ authn -> accessTokenResponse - status
     ✓ client -> search.searchForSharees - status
     ✓ client -> role.getMyDrives - status
     ✗ client -> resource.getResourceProperties - status
      ↳  50% — ✓ 1572 / ✗ 1546
     ✗ client -> application.createDrive - status
      ↳  52% — ✓ 46 / ✗ 41
     ✗ client -> resource.createResource - status
      ↳  61% — ✓ 52 / ✗ 33
     ✗ client -> drive.deactivateDrive - status
      ↳  50% — ✓ 44 / ✗ 43
     ✗ client -> drive.deleteDrive - status
      ↳  49% — ✓ 43 / ✗ 44
     ✗ client -> share.createShare - status
      ↳  54% — ✓ 23 / ✗ 19
     ✗ client -> share.deleteShare - status
      ↳  42% — ✓ 18 / ✗ 24
     ✗ client [...]

2024-07-25 14:51 UTC, butonic commented
Things I fixed to get the tests to run with the helm charts `next` branch:
- https://github.com/owncloud/ocis-charts/pull/663
- https://github.com/owncloud/ocis/pull/9692

2024-07-26 06:25 UTC, butonic commented
weird ...
## 1.  the service account id was not missing
```
The service account id has not been configured for storage-users. Make sure your /etc/ocis config contains the proper values (e.g. by running ocis init or setting it manually in the config/corresponding environment variable).
```
the service account is configured properly in the charts:
```
            - name: STORAGE_USERS_SERVICE_ACCOUNT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "config.authService" . }}
                  key: service-account-id
            - name: STORAGE_USERS_SERVICE_ACCOUNT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.serviceAccountSecret" . }}
                  key: service-account-secret
```

maybe the config maps or secrets were not deployed for a moment?

## storage-system is still active after a night of sleep
```
 Context: garden-420505--de-lasttest-external      <a>      Attach     <l>       Logs            <f> Show PortForward                                                            ____  __.________        
 Cluster: garden-420505--de-lasttest-external      <ctrl-d> Delete     <p>       Logs Previous   <t> Transfer                                                                   |    |/ _/   __   \______ 
 User:    garden-420505--de-lasttest               <d>      Describe   <shift-f> Port-Forward    <y> YAML                                                                       |      < \____    /  ___/ 
 K9s Rev: v0.32.4 ⚡️v0.32.5                        <e>      Edit       <z>       Sanitize                                                                                       |    |  \   /    /\___ \  
 K8s Rev: v1.28.8                                  <?>      Help       <s>       Shell                                                                                          |____|__ \ /____//____  > 
 CPU:     13%                                      <ctrl-k> Kill       <o>       Show Node                                                                                              \/            \/  
 MEM:     51%                                                                                                                                                                                             
┌────────────────────────────────────────────────────────────────────── Pods(school-91001/storagesystem)[10] </app=storagesystem> ───────────────────────────────────────────────────────────────────────┐
│ NAME↑                            PF  READY   STATUS       RESTARTS   CPU   MEM   %CPU/R   %CPU/L   %MEM/R   %MEM/L IP              NODE                                                      AGE       │
│ storagesystem-6b94df54dd-8wvbp   ●   1/1     Running             0   246   152      492      n/a      202       50 10.96.0.253     shoot--420505--de-lasttest-worker-icb8m-z1-5579f-spg66    4h14m     │
│ storagesystem-6b94df54dd-c4j2b   ●   1/1     Running             0   186   144      372      n/a      192       48 10.96.10.175    shoot--420505--de-lasttest-worker-icb8m-z1-5579f-j794c    8h        │
│ storagesystem-6b94df54dd-cgw25   ●   1/1     Running             0   193   124      386      n/a      165       41 10.96.16.184    shoot--420505--de-lasttest-worker-icb8m-z1-5579f-hd9tk    8h        │
│ storagesystem-6b94df54dd-glj2b   ●   1/1     Running             0   194   156      388      n/a      208       52 10.96.7.139     shoot--420505--de-lasttest-worker-icb8m-z1-5579f-qjxlh    8h        │
│ storagesystem-6b94df54dd-kchzk   ●   1/1     Running             0   147   200      294      n/a      267       66 10.96.9.250     shoot--420505--de-lasttest-worker-icb8m-z1-5579f-d6zbx    8h        │
│ storagesystem-6b94df54dd-nj29k   ●   1/1     Running             0   130   138      260      n/a      184       46 10.96.6.90      shoot--420505--de-lasttest-worker-icb8m-z1-5579f-n4ktd    8h        │
│ storagesystem-6b94df54dd-rr77p   ●   1/1     Running             0   203   263      405      n/a      351       87 10.96.19.169    shoot--420505--de-lasttest-worker-icb8m-z1-5579f-7nh4b    8h        │
│ storagesystem-6b94df54dd-tqtx9   ●   1/1     Running             0   504   249     1008      n/a      333       83 10.96.5.107     shoot--420505--de-lasttest-worker-icb8m-z1-5579f-jm4xw    5h46m     │
│ storagesystem-6b94df54dd-vllfc   ●   1/1     Running             0   252   129      504      n/a      172       43 10.96.3.246     shoot--420505--de-lasttest-worker-icb8m-z1-5579f-rchrr    138m      │
│ storagesystem-6b94df54dd-z2k88   ●   1/1     Running             0   143   242      286      n/a      322       80 10.96.8.20      shoot--420505--de-lasttest-worker-icb8m-z1-5579f-48c45    9h        │
```

2024-07-26 07:31 UTC, butonic commented
```
# k6 run ~/cdperf/packages/k6-tests/artifacts/koko-platform-000-mixed-ramping-k6.js

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: /root/cdperf/packages/k6-tests/artifacts/koko-platform-000-mixed-ramping-k6.js
     output: -

  scenarios: (100.00%) 8 scenarios, 75 max VUs, 6m30s max duration (incl. graceful stop):
           * add_remove_tag_100: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: add_remove_tag_100, gracefulStop: 30s)
           * create_remove_group_share_090: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: create_remove_group_share_090, gracefulStop: 30s)
           * create_space_080: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: create_space_080, gracefulStop: 30s)
           * create_upload_rename_delete_folder_and_file_040: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: create_upload_rename_delete_folder_and_file_040, gracefulStop: 30s)
           * download_050: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: download_050, gracefulStop: 30s)
           * navigate_file_tree_020: Up to 10 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: navigate_file_tree_020, gracefulStop: 30s)
           * sync_client_110: Up to 20 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: sync_client_110, gracefulStop: 30s)
           * user_group_search_070: Up to 20 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: user_group_search_070, gracefulStop: 30s)


     ✓ authn -> loginPageResponse - status
     ✓ authn -> authorizationResponse - status
     ✓ authn -> accessTokenResponse - status
     ✗ client -> role.getMyDrives - status
      ↳  96% — ✓ 48 / ✗ 2
     ✗ client -> search.searchForSharees - status
      ↳  99% — ✓ 400 / ✗ 1
     ✗ client -> resource.getResourceProperties - status
      ↳  66% — ✓ 2018 / ✗ 995
     ✗ client -> application.createDrive - status
      ↳  88% — ✓ 75 / ✗ 10
     ✗ client -> resource.createResource - status
      ↳  61% — ✓ 52 / ✗ 32
     ✗ client -> drive.deactivateDrive - status
      ↳  78% — ✓ 67 / ✗ 18
     ✗ client -> drive.deleteDrive - status
      ↳  77% — ✓ 66 / ✗ 19
     ✗ client -> share.createShare - status
      ↳  0% — ✓ 0 / ✗ 44
     ✗ client -> share.deleteShare - status
      ↳  0% — ✓ 0 / ✗ 44
     ✗ client -> resource.deleteResource - status
      ↳  51% — ✓ 43 / ✗ 41
     ✓ client -> tag.getTags - status -- (SKIPPED)
     ✓ client -> tag.createTag - status -- (SKIPPED)
     ✗ client -> tag.addTagToResource - status
      ↳  0% — ✓ 0 / ✗ 47
     ✗ client -> tag.removeTagToResource - status
      ↳  0% — ✓ 0 / ✗ 47
     ✗ client -> resource.uploadResource - status
      ↳  70% — ✓ 28 / ✗ 12
     ✗ client -> resource.moveResource - status
      ↳  55% — ✓ 22 / ✗ 18
     ✗ client -> resource.downloadResource - status
      ↳  75% — ✓ 72 / ✗ 24

     checks.........................: 70.67% ✓ 3263      ✗ 1354
     data_received..................: 1.4 GB 3.5 MB/s
     data_sent......................: 671 MB 1.7 MB/s
     http_req_blocked...............: avg=1.73ms   min=200ns   med=290ns    max=1.05s    p(90)=571ns    p(95)=878ns   
     http_req_connecting............: avg=892.03µs min=0s      med=0s       max=1.03s    p(90)=0s       p(95)=0s      
     http_req_duration..............: avg=309.26ms min=3.78ms  med=238.17ms max=39.57s   p(90)=428.75ms p(95)=606.57ms
       { expected_response:true }...: avg=350.57ms min=3.78ms  med=273.58ms max=39.57s   p(90)=489.04ms p(95)=640.74ms
     http_req_failed................: 28.51% ✓ 1354      ✗ 3394
     http_req_receiving.............: avg=9.79ms   min=22.01µs med=79.8µs   max=10.64s   p(90)=176.31µs p(95)=51.64ms 
     http_req_sending...............: avg=24.5ms   min=25.12µs med=84.68µs  max=30.5s    p(90)=137.54µs p(95)=174.39µs
     http_req_tls_handshaking.......: avg=824.37µs min=0s      med=0s       max=238.63ms p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=274.96ms min=3.65ms  med=237.23ms max=9.97s    p(90)=413.7ms  p(95)=577.97ms
     http_reqs......................: 4748   12.174314/s
     iteration_duration.............: avg=6.56s    min=1.04s   med=1.29s    max=1m13s    p(90)=15.56s   p(95)=18.23s  
     iterations.....................: 3513   9.007659/s
     vus............................: 1      min=0       max=75
     vus_max........................: 75     min=75      max=75


running (6m30.0s), 00/75 VUs, 3513 complete and 2 interrupted iterations
add_remove_tag_100             ✓ [======================================] 0/5 VUs    6m0s
create_remove_group_share_090  ✓ [======================================] 0/5 VUs    6m0s
create_space_080               ✓ [======================================] 0/5 VUs    6m0s
create_upload_rename_delete... ✓ [======================================] 0/5 VUs    6m0s
download_050                   ✓ [======================================] 0/5 VUs    6m0s
navigate_file_tree_020         ✓ [======================================] 00/10 VUs  6m0s
sync_client_110                ✓ [======================================] 00/20 VUs  6m0s
user_group_search_070          ✓ [======================================] 00/20 VUs  6m0s
```

I tried to get all error level logs and manually extracted some lines that marked the start and end of connection errors:
```json
➜  91001.drive.cloudspeicher-bayern.de git:(proxy-events-support) ✗ kubectl logs -n school-91001 -l app.kubernetes.io/name=ocis -f --max-log-requests 200
...
➜  cat interesting-logs.json | jq -s 'sort_by(.time)'
[
  {
    "level": "error",
    "service": "gateway",
    "pkg": "rgrpc",
    "traceid": "3749a397848210cfeed081bef18b286d",
    "user-agent": "grpc-go/1.65.0",
    "from": "tcp://10.96.11.196:49028",
    "uri": "/cs3.gateway.v1beta1.GatewayAPI/Stat",
    "start": "26/Jul/2024:06:33:47 +0000",
    "end": "26/Jul/2024:06:33:47 +0000",
    "time_ns": 1941184,
    "code": "Unavailable",
    "time": "2024-07-26T06:33:47Z",
    "message": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 10.96.9.247:9157: connect: connection refused\""
  },
  {
    "level": "error",
    "service": "gateway",
    "pkg": "rgrpc",
    "traceid": "d573044bd6ff468e890189b7aca87470",
    "user-agent": "k6/0.45.0 (https://k6.io/)",
    "from": "tcp://10.96.8.213:56856",
    "uri": "/cs3.gateway.v1beta1.GatewayAPI/Stat",
    "start": "26/Jul/2024:06:34:13 +0000",
    "end": "26/Jul/2024:06:34:13 +0000",
    "time_ns": 2866651,
    "code": "Unavailable",
    "time": "2024-07-26T06:34:13Z",
    "message": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 10.96.9.247:9157: connect: connection refused\""
  },
  {
    "level": "error",
    "service": "gateway",
    "pkg": "rgrpc",
    "traceid": "acebe737a6478f55f0714a3a9263a657",
    "user-agent": "k6/0.45.0 (https://k6.io/)",
    "from": "tcp://10.96.8.213:56856",
    "uri": "/cs3.gateway.v1beta1.GatewayAPI/Stat",
    "start": "26/Jul/2024:06:34:37 +0000",
    "end": "26/Jul/2024:06:34:37 +0000",
    "time_ns": 912784,
    "code": "Unavailable",
    "time": "2024-07-26T06:34:37Z",
    "message": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 10.96.9.247:9157: connect: connection refused\""
  },
  {
    "level": "error",
    "service": "ocdav",
    "name": "com.owncloud.web.ocdav",
    "traceid": "df98ca9c27bde0dbafcd33869bd1cd05",
    "request-id": "6258be7c04b26b9fb31615c9b2934f52",
    "path": "/resource/small.zip",
    "spaceid": "55b65915-d282-4be3-88f7-a07a3d092c01$27b724ae-fc60-4f4a-b85f-9227aaac862e",
    "handler": "get",
    "status": {
      "code": 15,
      "message": "gat [...]

2024-07-26 07:56 UTC, butonic commented
one of the graph services keeps a hight cpu:
```
Context: garden-420505--de-lasttest-external      <a>      Attach     <l>       Logs            <f> Show PortForward                       ____  __.________        
 Cluster: garden-420505--de-lasttest-external      <ctrl-d> Delete     <p>       Logs Previous   <t> Transfer                              |    |/ _/   __   \______ 
 User:    garden-420505--de-lasttest               <d>      Describe   <shift-f> Port-Forward    <y> YAML                                  |      < \____    /  ___/ 
 K9s Rev: v0.32.4 ⚡️v0.32.5                        <e>      Edit       <z>       Sanitize                                                  |    |  \   /    /\___ \  
 K8s Rev: v1.28.8                                  <?>      Help       <s>       Shell                                                     |____|__ \ /____//____  > 
 CPU:     11%                                      <ctrl-k> Kill       <o>       Show Node                                                         \/            \/  
 MEM:     57%                                                                                                                                                        
┌──────────────────────────────────────────────────────────── Pods(school-91001/graph)[3] </app=graph> ─────────────────────────────────────────────────────────────┐
│ NAME↑                   PF READY STATUS   RESTARTS CPU MEM %CPU/R %CPU/L %MEM/R %MEM/L IP            NODE                                                    AGE  │
│ graph-576d884c58-96dpj  ●  1/1   Running         0   1  32      2    n/a     21     16 10.96.8.147   shoot--420505--de-lasttest-worker-icb8m-z1-5579f-48c45  7m47 │
│ graph-576d884c58-fm9kh  ●  1/1   Running         0  10 181     20    n/a    121     90 10.96.16.103  shoot--420505--de-lasttest-worker-icb8m-z1-5579f-hd9tk  94m  │
│ graph-576d884c58-mcfwz  ●  1/1   Running         0 221 198    442    n/a    132     99 10.96.9.246   shoot--420505--de-lasttest-worker-icb8m-z1-5579f-d6zbx  93m  │
```

2024-07-26 11:37 UTC, butonic commented
urgh 9157 is the storage-users service ... so ... we seem to have problems connecting to it ... 🤔

2024-07-26 11:39 UTC, butonic commented
it seems only one of them is getting traffic:
```
 Context: garden-420505--de-lasttest-external      <a>      Attach     <l>       Logs            <f> Show PortForward                                                         ____  __.________        
 Cluster: garden-420505--de-lasttest-external      <ctrl-d> Delete     <p>       Logs Previous   <t> Transfer                                                                |    |/ _/   __   \______ 
 User:    garden-420505--de-lasttest               <d>      Describe   <shift-f> Port-Forward    <y> YAML                                                                    |      < \____    /  ___/ 
 K9s Rev: v0.32.4 ⚡️v0.32.5                        <e>      Edit       <z>       Sanitize                                                                                    |    |  \   /    /\___ \  
 K8s Rev: v1.28.8                                  <?>      Help       <s>       Shell                                                                                       |____|__ \ /____//____  > 
 CPU:     16%                                      <ctrl-k> Kill       <o>       Show Node                                                                                           \/            \/  
 MEM:     60%                                                                                                                                                                                          
┌────────────────────────────────────────────────────────────────────── Pods(school-91001/storageusers)[3] </app=storageusers> ───────────────────────────────────────────────────────────────────────┐
│ NAME↑                           PF  READY  STATUS             RESTARTS  CPU  MEM  %CPU/R  %CPU/L  %MEM/R  %MEM/L IP             NODE                                                      AGE       │
│ storageusers-5bfdbc9ddd-4945b   ●   0/1    PodInitializingΔ          0    0    0       0     n/a       0       0 10.96.14.38    shoot--420505--de-lasttest-worker-icb8m-z1-5579f-fwgs8    2s        │
│ storageusers-5bfdbc9ddd-fwr9f   ●   1/1    Running                   3    0    0       0     n/a       0       0 10.96.8.247    shoot--420505--de-lasttest-worker-icb8m-z1-5579f-48c45    5m42s     │
│ storageusers-5bfdbc9ddd-zt92m   ●   1/1    Running                   1  278  113     278     n/a      37       7 10.96.4.213    shoot--420505--de-lasttest-worker-icb8m-z1-5579f-qdgd9    5m47s     │
```
oh and the other one is OOM killed!?!
```
 Context: garden-420505--de-lasttest-external      <a>      Attach     <l>       Logs            <f> Show PortForward                                                         ____  __.________        
 Cluster: garden-420505--de-lasttest-external      <ctrl-d> Delete     <p>       Logs Previous   <t> Transfer                                                                |    |/ _/   __   \______ 
 User:    garden-420505--de-lasttest               <d>      Describe   <shift-f> Port-Forward    <y> YAML                                                                    |      < \____    /  ___/ 
 K9s Rev: v0.32.4 ⚡️v0.32.5                        <e>      Edit       <z>       Sanitize                                                                                    |    |  \   /    /\___ \  
 K8s Rev: v1.28.8                                  <?>      Help       <s>       Shell                                                                                       |____|__ \ /____//____  > 
 CPU:     16%                                      <ctrl-k> Kill       <o>       Show Node                                                                                           \/            \/  
 MEM:     60%                                                                                                                                                                                          
┌────────────────────────────────────────────────────────────────────── Pods(school-91001/storageusers)[3] </app=storageusers> ───────────────────────────────────────────────────────────────────────┐
│ NAME↑                           PF  READY  STATUS        RESTARTS   CPU   MEM   %CPU/R   %CPU/L   %MEM/R   %MEM/L IP             NODE                                                      AGE      │
│ storageusers-5bfdbc9ddd-4945b   ●   1/1    Running              0     0     0        0      n/a        0        0 10.96.14.38    shoot--420505--de-lasttest-worker-icb8m-z1-5579f-fwgs8    24s      │
│ storageusers-5bfdbc9ddd-fwr9f   ●   1/1    Running              3   153    65      153      n/a       21        4 10.96.8.247    shoot--420505--de-lasttest-worker-icb8m-z1-5579f-48c45    6m4s     │
│ storageusers-5bfdbc9ddd-zt92m   ●   0/1    OOMKilled            1     0     0        0      n/a        0        0 10.96.4.213    shoot--420505--de-lasttest-worker-icb8m-z1-5579f-qdgd9    6m9s     
```

2024-07-26 11:40 UTC, butonic commented
but the third does not get traffic:
```
Context: garden-420505--de-lasttest-external      <a>      Attach     <l>       Logs            <f> Show PortForward                                                         ____  __.________        
 Cluster: garden-420505--de-lasttest-external      <ctrl-d> Delete     <p>       Logs Previous   <t> Transfer                                                                |    |/ _/   __   \______ 
 User:    garden-420505--de-lasttest               <d>      Describe   <shift-f> Port-Forward    <y> YAML                                                                    |      < \____    /  ___/ 
 K9s Rev: v0.32.4 ⚡️v0.32.5                        <e>      Edit       <z>       Sanitize                                                                                    |    |  \   /    /\___ \  
 K8s Rev: v1.28.8                                  <?>      Help       <s>       Shell                                                                                       |____|__ \ /____//____  > 
 CPU:     16%                                      <ctrl-k> Kill       <o>       Show Node                                                                                           \/            \/  
 MEM:     60%                                                                                                                                                                                          
┌────────────────────────────────────────────────────────────────────── Pods(school-91001/storageusers)[3] </app=storageusers> ───────────────────────────────────────────────────────────────────────┐
│ NAME↑                           PF  READY  STATUS       RESTARTS   CPU   MEM   %CPU/R   %CPU/L   %MEM/R   %MEM/L IP             NODE                                                      AGE       │
│ storageusers-5bfdbc9ddd-4945b   ●   1/1    Running             0    18    41       18      n/a       13        2 10.96.14.38    shoot--420505--de-lasttest-worker-icb8m-z1-5579f-fwgs8    2m        │
│ storageusers-5bfdbc9ddd-fwr9f   ●   1/1    Running             3   225    89      225      n/a       29        5 10.96.8.247    shoot--420505--de-lasttest-worker-icb8m-z1-5579f-48c45    7m40s     │
│ storageusers-5bfdbc9ddd-zt92m   ●   1/1    Running             3     0     0        0      n/a        0        0 10.96.4.213    shoot--420505--de-lasttest-worker-icb8m-z1-5579f-qdgd9    7m45s     │
```

2024-07-26 11:41 UTC, butonic commented
and one gets OOM killed:
```
 Context: garden-420505--de-lasttest-external      <a>      Attach     <l>       Logs            <f> Show PortForward                                                         ____  __.________        
 Cluster: garden-420505--de-lasttest-external      <ctrl-d> Delete     <p>       Logs Previous   <t> Transfer                                                                |    |/ _/   __   \______ 
 User:    garden-420505--de-lasttest               <d>      Describe   <shift-f> Port-Forward    <y> YAML                                                                    |      < \____    /  ___/ 
 K9s Rev: v0.32.4 ⚡️v0.32.5                        <e>      Edit       <z>       Sanitize                                                                                    |    |  \   /    /\___ \  
 K8s Rev: v1.28.8                                  <?>      Help       <s>       Shell                                                                                       |____|__ \ /____//____  > 
 CPU:     15%                                      <ctrl-k> Kill       <o>       Show Node                                                                                           \/            \/  
 MEM:     60%                                                                                                                                                                                          
┌────────────────────────────────────────────────────────────────────── Pods(school-91001/storageusers)[3] </app=storageusers> ───────────────────────────────────────────────────────────────────────┐
│ NAME↑                           PF  READY  STATUS       RESTARTS   CPU   MEM   %CPU/R   %CPU/L   %MEM/R   %MEM/L IP             NODE                                                      AGE       │
│ storageusers-5bfdbc9ddd-4945b   ●   1/1    Running             0   147    64      147      n/a       21        4 10.96.14.38    shoot--420505--de-lasttest-worker-icb8m-z1-5579f-fwgs8    2m34s     │
│ storageusers-5bfdbc9ddd-fwr9f   ●   0/1    OOMKilled           3   214    91      214      n/a       30        6 10.96.8.247    shoot--420505--de-lasttest-worker-icb8m-z1-5579f-48c45    8m14s     │
│ storageusers-5bfdbc9ddd-zt92m   ●   1/1    Running             3     0     0        0      n/a        0        0 10.96.4.213    shoot--420505--de-lasttest-worker-icb8m-z1-5579f-qdgd9    8m19s   
```

2024-07-26 13:18 UTC, butonic commented
I increased the resources for storageusers:
```yaml
          storageusers:
            resources:
              limits:
                memory: 1500Mi
              requests:
                cpu: 100m
                memory: 300Mi
```

but it seems it is already killed at 300m
```
Name:             shoot--420505--de-lasttest-worker-icb8m-z1-5579f-d6zbx.17e5c470723da57b                                                                                                                               Namespace:        default                                                                                                                                                                                               Labels:           <none>                                                                                                                                                                                                Annotations:      <none>                                                                                                                                                                                                API Version:      v1                                                                                                                                                                                                    Count:            1                                                                                                                                                                                                     Event Time:       <nil>                                                                                                                                                                                                 First Timestamp:  2024-07-26T12:53:39Z                                                                                                                                                                                  Involved Object:                                                                                                                                                                                                          Kind:          Node                                                                                                                                                                                                     Name:          shoot--420505--de-lasttest-worker-icb8m-z1-5579f-d6zbx                                                                                                                                                   UID:           shoot--420505--de-lasttest-worker-icb8m-z1-5579f-d6zbx                                                                                                                                                 Kind:            Event                                                                                                                                                                                                  Last Timestamp:  2024-07-26T12:53:39Z                                                                                                                                                                                   Message:         Memory cgroup out of memory: Killed process 3739589 (ocis) total-vm:1328588kB, anon-rss:31848kB, file-rss:56240kB, shmem-rss:0kB, UID:1000 pgtables:332kB oom_score_adj:997                            Metadata:                                                                                                                                                                                                                 Creation Timestamp:  2024-07-26T12:53:39Z                                                                                                                                                                               Resource Version:    2027123                                                                                                                                                                                            UID:                 8b0d467f-feda-4b77-bc85-63438e47293a                                                                                                                                                             Reason:                OOMKilling                                                                                                                                                                                       Reporting Component:                                                                                                                                                                                                    Reporting Instance:                                                                                                                                                                                                     Source:                                                                                                                                                                                                                   Component:  kernel-monitor                                                                                                                                                                                              Host:       shoot--420505--de-lasttest-worker-icb8m-z1-5579f-d6zbx                                                                                                                                                    Type:         Warning                                                                                                                                                                                                   Events:       <none>
```

which leads me to https://github.com/kubernetes/kubernetes/issues/43916#issuecomment-2249191975
> A concrete use case is https://github.com/kubernetes/kubernetes/issues/43916. The summary of that longstanding issue is that some apps read many files into memory, filling the page cache. Eventually, this may result in cgroup OOM even though the memory could be reclaimed. Some users have written workarounds like agents that proactively force reclaim https://github.com/linchpiner/cgroup-memory-manager. The goal is that with this feature, this will not be necessary, as memory.high (a bit before the limit) would be reached, and the memory would be reclaimed automatically.

😞

2024-07-26 15:19 UTC, butonic commented
ok ... ramping up the storageusers memory limit does help with the OOM killing:
```
# k6 run ~/cdperf/packages/k6-tests/artifacts/koko-platform-000-mixed-ramping-k6.js

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: /root/cdperf/packages/k6-tests/artifacts/koko-platform-000-mixed-ramping-k6.js
     output: -

  scenarios: (100.00%) 8 scenarios, 75 max VUs, 6m30s max duration (incl. graceful stop):
           * add_remove_tag_100: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: add_remove_tag_100, gracefulStop: 30s)
           * create_remove_group_share_090: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: create_remove_group_share_090, gracefulStop: 30s)
           * create_space_080: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: create_space_080, gracefulStop: 30s)
           * create_upload_rename_delete_folder_and_file_040: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: create_upload_rename_delete_folder_and_file_040, gracefulStop: 30s)
           * download_050: Up to 5 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: download_050, gracefulStop: 30s)
           * navigate_file_tree_020: Up to 10 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: navigate_file_tree_020, gracefulStop: 30s)
           * sync_client_110: Up to 20 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: sync_client_110, gracefulStop: 30s)
           * user_group_search_070: Up to 20 looping VUs for 6m0s over 3 stages (gracefulRampDown: 30s, exec: user_group_search_070, gracefulStop: 30s)


     ✓ authn -> loginPageResponse - status
     ✓ authn -> authorizationResponse - status
     ✓ authn -> accessTokenResponse - status
     ✓ client -> search.searchForSharees - status
     ✓ client -> role.getMyDrives - status
     ✓ client -> application.createDrive - status
     ✓ client -> resource.getResourceProperties - status
     ✓ client -> resource.createResource - status
     ✓ client -> drive.deactivateDrive - status
     ✓ client -> drive.deleteDrive - status
     ✗ client -> share.createShare - status
      ↳  0% — ✓ 0 / ✗ 44
     ✗ client -> share.deleteShare - status
      ↳  0% — ✓ 0 / ✗ 44
     ✓ client -> resource.deleteResource - status
     ✓ client -> resource.downloadResource - status
     ✓ client -> resource.uploadResource - status
     ✓ client -> tag.getTags - status -- (SKIPPED)
     ✓ client -> tag.createTag - status -- (SKIPPED)
     ✓ client -> resource.moveResource - status
     ✗ client -> tag.addTagToResource - status
      ↳  0% — ✓ 0 / ✗ 46
     ✗ client -> tag.removeTagToResource - status
      ↳  0% — ✓ 0 / ✗ 46

     checks.........................: 96.03% ✓ 4355     ✗ 180 
     data_received..................: 1.7 GB 4.5 MB/s
     data_sent......................: 811 MB 2.1 MB/s
     http_req_blocked...............: avg=901.52µs min=200ns   med=271ns    max=52.46ms  p(90)=571ns    p(95)=840ns   
     http_req_connecting............: avg=317.45µs min=0s      med=0s       max=19.56ms  p(90)=0s       p(95)=0s      
     http_req_duration..............: avg=324.18ms min=2.7ms   med=258.37ms max=12.09s   p(90)=502.97ms p(95)=638.34ms
       { expected_response:true }...: avg=331.48ms min=2.7ms   med=262.55ms max=12.09s   p(90)=511.1ms  p(95)=645.1ms 
     http_req_failed................: 3.85%  ✓ 180      ✗ 4488
     http_req_receiving.............: avg=8.91ms   min=27.76µs med=88.89µs  max=8.53s    p(90)=192.62µs p(95)=50.42ms 
     http_req_sending...............: avg=1.57ms   min=25.76µs med=87.11µs  max=673.28ms p(90)=141.99µs p(95)=177.1µs 
     http_req_tls_handshaking.......: avg=569.85µs min=0s      med=0s       max=35.39ms  p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=313.7ms  min=2.55ms  med=256.88ms max=12.09s   p(90)=481.65ms p(95)=625.26ms
     http_reqs......................: 4668   12.21598/s
     iteration_duration.............: avg=6.72s    min=1.16s   med=1.29s    max=47.15s   p(90)=15.59s   p(95)=18.32s  
     iterations.....................: 3430   8.97618/s
     vus............................: 1      min=0      max=75
     vus_max........................: 75     min=75     max=75


running (6m22.1s), 00/75 VUs, 3430 complete and 2 interrupted iterations
add_remove_tag_100             ✓ [======================================] 0/5 VUs    6m0s
create_remove_group_share_090  ✓ [======================================] 0/5 VUs    6m0s
create_space_080               ✓ [======================================] 0/5 VUs    6m0s
create_upload_rename_delete... ✓ [======================================] 0/5 VUs    6m0s
download_050                   ✓ [======================================] 0/5 VUs    6m0s
navigate_file_tree_020         ✓ [======================================] 00/10 VUs  6m0s
sync_client_110                ✓ [======================================] 00/20 VUs  6m0s
user_group_search_070          ✓ [======================================] 00/20 VUs  6m0s
```

2024-07-29 13:51 UTC, butonic commented
The changes in this PR are all fixing the situation. This PR can be merged as is. I will followup with other PRs to fine tune he load tests.

2024-07-30 09:41 UTC, kobergj approved these changes

2024-07-30 09:42 UTC, merged