[full-ci] return 403 when the copy forbidden
owncloud/ocis pull request #9677
Opened 2024-07-23 10:53 UTC by 2403905

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2024-07-24 09:57 UTC, S-Panta commented
I've pulled this PR , build the ocis and run the test of this PR https://github.com/owncloud/ocis/pull/9445 and it passes.

2024-07-25 07:07 UTC, kobergj requested changes

2024-07-25 07:07 UTC, kobergj commented on changelog/unreleased/fix-copy-responce.md
Mind adding a line also to `changelog/unreleased/bump-reva.md` ?

2024-07-25 09:07 UTC, kobergj approved these changes
LGTM :+1:

2024-07-25 09:26 UTC, merged