Remove config options that ain't available in web anymore
owncloud/ocis pull request #9679
Opened 2024-07-23 12:27 UTC by AlexAndBear

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2024-07-23 12:32 UTC, kulmann commented on changelog/unreleased/remove-unavailable-web-config-options.md
> +We've removed config options from the web package, that are no longer available in web.
please add something like `Please check the web changelog for more details.`

2024-07-23 14:03 UTC, ScharfViktor commented
<img width="1649" alt="Screenshot 2024-07-23 at 16 01 37" src="https://github.com/user-attachments/assets/f56b89d7-de07-4b3b-82e5-9a18167dafa0">

I guess we need https://github.com/owncloud/web/pull/11251/commits/89f3cb0f4ee2b98f73e818546295cf7bc557ad50

2024-07-23 14:09 UTC, ScharfViktor commented
> @ScharfViktor I have no idea how to bring it in, do we need a new web release ? :O

Let's see what CI has to say. If we have failed tests again, we'll need to make a new web release

2024-07-23 14:10 UTC, ScharfViktor commented
now this test is green https://drone.owncloud.com/owncloud/ocis/37429/55/9

2024-07-24 03:52 UTC, kulmann requested changes

2024-07-24 03:52 UTC, kulmann commented on services/web/pkg/config/defaults/defaultconfig.go
> +						ID:     "preview",
Now with the mime types config being removed you can remove the preview app from the external apps entirely and add `preview` to the `Apps` slice in line 101. We only had it as external app to be able to pass config.

2024-07-24 06:41 UTC, kulmann approved these changes
thank you 🥇

2024-07-24 09:25 UTC, merged