[tests-only][full-ci]add test coverage for `/app/` endpoint
owncloud/ocis pull request #9885
Opened 2024-08-21 11:01 UTC by PrajwolAmatya

## Description

## Related Issue

- https://github.com/owncloud/ocis/issues/9682

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2024-08-23 07:18 UTC, SagarGi reviewed
LGTM :+1: if CI is green

2024-08-26 07:22 UTC, saw-jan requested changes

2024-08-26 07:22 UTC, saw-jan commented on .drone.star
> +        "apiAppProvider": {
```suggestion
        "apiWopi": {
```

2024-08-26 07:22 UTC, saw-jan commented on tests/acceptance/features/apiAppProvider/appProvider.feature
`apiCollaboration/wopi.feature`

2024-08-26 07:22 UTC, saw-jan commented on .drone.star
> +                                     (collaborationService(extra_environment = params["extraCollaborationEnvironment"]) if params["collaborationServiceNeeded"] else []) +
```suggestion
                                     (collaborationService(params["extraCollaborationEnvironment"]) if params["collaborationServiceNeeded"] else []) +
```

2024-08-26 07:22 UTC, saw-jan commented on tests/config/drone/app-registry.yaml
> +      description: FakeOffice text document
```suggestion
      name: OpenDocument
      description: OpenDocument text document
```

2024-08-26 07:22 UTC, saw-jan commented on tests/acceptance/config/behat.yml
> +      paths:
Please, move it above cli suites

2024-08-26 07:22 UTC, saw-jan commented on .drone.star
> +def fakeOffice():
reuse it in other existing pipelines as well

2024-08-26 07:22 UTC, saw-jan commented on .drone.star
> +def collaborationService(extra_environment = {}):
reuse it in other existing pipelines as well.

2024-08-26 07:22 UTC, saw-jan commented on tests/acceptance/features/apiAppProvider/appProvider.feature
> +Feature: App Provider
```suggestion
Feature: collaboration (wopi)
```

2024-08-26 07:22 UTC, saw-jan commented on tests/acceptance/features/apiAppProvider/appProvider.feature
> +  So that I can collaborate with other users
I find it hard to properly write user story for API feature

2024-08-26 07:22 UTC, saw-jan commented on tests/acceptance/features/apiAppProvider/appProvider.feature
> +            "pattern": "^https:\\/\\/(.*?)\\?WOPISrc=http%3A%2F%2F(.*?)%3A9300%2Fwopi%2Ffiles%2F[a-fA-F0-9]{64}$"
```suggestion
            "pattern": "^.*\\?WOPISrc=.*wopi%2Ffiles%2F[a-fA-F0-9]{64}$"
```

2024-08-26 07:25 UTC, saw-jan commented on .drone.star
> +            },
Is it possible to list the required services and use it in the pipeline services
```suggestion
            "extraServerEnvironment": {
                "GATEWAY_GRPC_ADDR": "0.0.0.0:9142",
            },
            "extraServices": [
                fakeOffice,
            ],
```

2024-08-27 04:14 UTC, saw-jan commented on .drone.star
> +            },
will more changes in this PR. can be done in coming PRs

2024-08-27 04:15 UTC, saw-jan commented on .drone.star
> +        "extraServices": [],
```suggestion
        },
```

2024-08-27 04:15 UTC, saw-jan commented on .drone.star
> -            "skip": False,
:arrows_counterclockwise:

2024-08-27 04:48 UTC, saw-jan commented on tests/acceptance/features/apiCollaboration/wopi.feature
> +  Scenario Outline: open file with .odt extension with collaboration app
```suggestion
  Scenario Outline: open file with .odt extension
```

2024-08-27 05:01 UTC, saw-jan approved these changes
LGTM

2024-08-27 05:37 UTC, merged