[tests-only][full-ci] add tests to check versions of file in a space shared via link with viewer/editor role
owncloud/ocis pull request #9982
Opened 2024-09-05 05:50 UTC by prashant-gurung899

## Description
This PR adds tests to check versions of a file inside a space that is shared via link with viewer and editor roles.

## Related Issue

- Related to: https://github.com/owncloud/ocis/issues/9955

## Motivation and Context

## How Has This Been Tested?

- 

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2024-09-05 11:14 UTC, anon-pradip commented on tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
> +    And user "Alice" has created the following space link share:
```suggestion
    Given user "Alice" has created the following space link share:
```

2024-09-06 06:06 UTC, amrita-shrestha commented on tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
> +  Scenario Outline: check the versions of a file in a personal space shared via link as viewer
```suggestion
  Scenario Outline: check the versions of a file in a personal space shared via link
```
if we include all possible role then maybe we can skip mentioning role name

2024-09-06 06:06 UTC, amrita-shrestha commented on tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
> +  Scenario Outline: check the versions of a file in a space shared via link as viewer/editor
same comment like below

2024-09-10 03:45 UTC, amrita-shrestha approved these changes
lgtm

2024-09-10 05:01 UTC, saw-jan requested changes

2024-09-10 05:01 UTC, saw-jan commented on tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
> +    When the public tries to get the number of versions of file "/text.txt" using password "%public%" using file-id path "/meta/<<FILEID>>/v"
```suggestion
    When the public tries to get the number of versions of file "/text.txt" with password "%public%" using file-id path "/meta/<<FILEID>>/v"
```

2024-09-10 05:01 UTC, saw-jan commented on tests/acceptance/bootstrap/FilesVersionsContext.php
> +	public function thePublicGetsTheNumberOfVersionsOfFileWithPasswordUsingFileIdPath(string $file, string $password, string $endpoint) {
```suggestion
	public function thePublicGetsTheNumberOfVersionsOfFileWithPasswordUsingFileIdPath(string $file, string $password, string $endpoint): void {
```

2024-09-11 04:57 UTC, saw-jan approved these changes

2024-09-11 04:57 UTC, merged